version: '3'

tasks:
  lock:
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - fish ../build/run.fish npm install --package-lock-only --ignore-scripts
  deps:
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - fish ../build/run.fish npm ci
  setup:
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - fish ../build/run.fish rustup target list --installed
      - fish ../build/run.fish wasm-bindgen --version
  build:
    dir: "{{.TASKFILE_DIR}}"
    deps: [deps, setup]
    cmds:
      - fish ../build/run.fish cargo build --locked --features ssr
      - fish ../build/run.fish npm run css
      - fish ../build/run.fish cargo build --locked --release --lib --target wasm32-unknown-unknown --no-default-features --features hydrate
      - fish ../build/run.fish wasm-bindgen target/wasm32-unknown-unknown/release/medtracker_ui_preview.wasm --out-dir public/pkg --target web
  test:
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - fish ../build/run.fish cargo test --locked --features ssr
  fmt:
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - fish ../build/run.fish cargo fmt --check
  format:
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - fish ../build/run.fish cargo fmt
  lint:
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - fish ../build/run.fish cargo clippy --locked --all-targets --features ssr -- -D warnings
