import { test, expect } from './care-fixtures.mjs';
import { fileURLToPath } from 'node:url';
import { measureCareContrast } from './care-contrast.mjs';

test.use({ actionTimeout: 10000 });

test('medication creation, stale editing and guarded deletion work through real pages', async ({ page, careFixture }, testInfo) => {
  test.setTimeout(180000);
  await page.goto('/login');
  await page.getByLabel('Email address', { exact: true }).fill('persistence@example.test');
  await page.getByLabel('Password', { exact: true }).fill('password');
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await page.getByRole('link', { name: 'Synthetic household', exact: true }).click();
  await expect(page.getByRole('link', { name: 'Add Medication', exact: true })).toBeVisible({ timeout: 5000 });
  await page.getByRole('link', { name: 'Add Medication', exact: true }).click();
  await page.getByLabel('Name', { exact: true }).fill('Synthetic browser medicine');
  await page.getByLabel('Location', { exact: true }).selectOption({ label: 'Synthetic cabinet' });
  await page.getByLabel('Dose', { exact: true }).fill('2');
  await page.getByLabel('Unit', { exact: true }).selectOption('tablet');
  await page.getByLabel('Starting Supply', { exact: true }).fill('10');
  await page.getByLabel('Reorder Threshold', { exact: true }).fill('2');
  await page.getByLabel('Barcode', { exact: true }).fill('invalid');
  const invalid = page.waitForResponse(response => response.request().method() === 'POST' && response.url().endsWith('/medications'));
  await page.getByRole('button', { name: 'Save Medication', exact: true }).click();
  expect((await invalid).status()).toBe(422);
  await expect(page.getByLabel('Name', { exact: true })).toHaveValue('Synthetic browser medicine');
  await expect(page.getByLabel('Barcode', { exact: true })).toHaveValue('invalid');
  await expect(page.getByRole('alert')).toContainText('Barcode');
  const barcodeMessage = await page.locator('[role="alert"] a[href="#barcode"]').innerText();
  await expect(page.getByLabel('Barcode', { exact: true })).toHaveAccessibleDescription(barcodeMessage);
  await measureCareContrast(page);
  await page.getByLabel('Barcode', { exact: true }).fill('');
  await page.getByRole('button', { name: 'Save Medication', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Synthetic browser medicine', exact: true })).toBeVisible();
  await expect(page.getByTestId('current-supply')).toHaveText('10 tablets');
  const createdDetail = page.url();
  await page.getByRole('link', { name: 'Edit Medication', exact: true }).click();
  const stale = await page.context().newPage();
  await stale.goto(page.url());
  await page.getByLabel('Display name', { exact: true }).fill('Synthetic display name');
  await page.getByRole('button', { name: 'Save Medication', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Synthetic display name', exact: true })).toBeVisible();
  await stale.getByLabel('Display name', { exact: true }).fill('Stale submitted name');
  const conflicted = stale.waitForResponse(response => response.request().method() === 'POST');
  await stale.getByRole('button', { name: 'Save Medication', exact: true }).click();
  expect((await conflicted).status()).toBe(409);
  await expect(stale.getByLabel('Display name', { exact: true })).toHaveValue('Stale submitted name');
  await expect(stale.getByRole('link', { name: 'Review latest details', exact: true })).toBeVisible();
  await measureCareContrast(stale);
  expect(await stale.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await stale.screenshot({ path: fileURLToPath(new URL(`../../docs/screenshots/loco-medication-edit-${testInfo.project.name}.png`, import.meta.url)), fullPage: true });
  await stale.close();
  await page.getByRole('button', { name: 'Delete Medication', exact: true }).click();
  await page.getByRole('dialog', { name: 'Delete Medication', exact: true }).getByRole('button', { name: 'Delete', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Medications', exact: true })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Synthetic display name', exact: true })).toHaveCount(0);
  expect((await page.request.get(createdDetail, { maxRedirects: 0 })).status()).toBe(404);
  await page.getByRole('link', { name: 'Synthetic tablets', exact: true }).click();
  await page.getByRole('button', { name: 'Record dose', exact: true }).click();
  await expect(page.getByTestId('current-supply')).toHaveText('8 tablets');
  await page.getByRole('button', { name: 'Delete Medication', exact: true }).click();
  const refused = page.waitForResponse(response => response.request().method() === 'POST');
  await page.getByRole('dialog', { name: 'Delete Medication', exact: true }).getByRole('button', { name: 'Delete', exact: true }).click();
  expect((await refused).status()).toBe(422);
  await expect(page.getByRole('alert')).toContainText('cannot be deleted');
  await expect(page.getByTestId('current-supply')).toHaveText('8 tablets');
  const stored = await careFixture.probe();
  expect(stored.takes).toBe(1);
  expect(stored.supply).toBe('8.00');
});
