import { test, expect } from './care-fixtures.mjs';

test.use({ actionTimeout: 10000 });

test('locations can be created, edited, used by medication and safely deleted', async ({ page, careFixture }, testInfo) => {
  test.setTimeout(180000);
  await page.goto('/login');
  await page.getByLabel('Email address', { exact: true }).fill('persistence@example.test');
  await page.getByLabel('Password', { exact: true }).fill('password');
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await page.getByRole('link', { name: 'Synthetic household', exact: true }).click();
  await expect(page.getByRole('link', { name: 'Locations', exact: true })).toBeVisible({ timeout: 5000 });
  await page.getByRole('link', { name: 'Locations', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Locations', exact: true })).toBeVisible();
  const locationsUrl = page.url();
  await page.getByRole('link', { name: 'Add Location', exact: true }).click();
  await page.getByLabel('Name', { exact: true }).fill('synthetic cabinet');
  await page.getByLabel('Description', { exact: true }).fill('Keep this submitted description');
  const invalid = page.waitForResponse(response => response.request().method() === 'POST');
  await page.getByRole('button', { name: 'Save Location', exact: true }).click();
  expect((await invalid).status()).toBe(422);
  await expect(page.getByLabel('Name', { exact: true })).toHaveValue('synthetic cabinet');
  await expect(page.getByLabel('Description', { exact: true })).toHaveValue('Keep this submitted description');
  const message = await page.locator('[role="alert"] a[href="#name"]').innerText();
  await expect(page.getByLabel('Name', { exact: true })).toHaveAccessibleDescription(message);
  await page.getByLabel('Name', { exact: true }).fill('Synthetic browser location');
  await page.getByRole('button', { name: 'Save Location', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Synthetic browser location', exact: true })).toBeVisible();
  await page.getByRole('link', { name: 'Edit Location', exact: true }).click();
  await page.getByLabel('Name', { exact: true }).fill('Synthetic edited location');
  await page.getByLabel('Description', { exact: true }).fill('Ready for medication');
  await page.getByRole('button', { name: 'Save Location', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Synthetic edited location', exact: true })).toBeVisible();
  await expect(page.getByText('Ready for medication', { exact: true })).toBeVisible();
  const locationDetail = page.url();
  await page.getByRole('link', { name: 'Medications', exact: true }).click();
  await page.getByRole('link', { name: 'Add Medication', exact: true }).click();
  await page.getByLabel('Location', { exact: true }).selectOption({ label: 'Synthetic edited location' });
  await page.getByLabel('Name', { exact: true }).fill('Synthetic location medicine');
  await page.getByLabel('Dose', { exact: true }).fill('1');
  await page.getByLabel('Unit', { exact: true }).selectOption('tablet');
  await page.getByLabel('Starting Supply', { exact: true }).fill('5');
  await page.getByRole('button', { name: 'Save Medication', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Synthetic location medicine', exact: true })).toBeVisible();
  await page.goto(locationDetail);
  await expect(page.getByRole('link', { name: 'Synthetic location medicine', exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath(`loco-location-${testInfo.project.name}.png`), fullPage: true });
  await page.getByRole('button', { name: 'Delete Location', exact: true }).click();
  await page.getByRole('dialog', { name: 'Delete Location', exact: true }).getByRole('button', { name: 'Delete', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Locations', exact: true })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Synthetic edited location', exact: true })).toHaveCount(0);
  expect((await page.request.get(locationDetail, { maxRedirects: 0 })).status()).toBe(404);
  await page.getByRole('link', { name: 'Medications', exact: true }).click();
  await expect(page.getByRole('link', { name: 'Synthetic location medicine', exact: true })).toHaveCount(0);
  await page.getByRole('link', { name: 'Synthetic tablets', exact: true }).click();
  await page.getByRole('button', { name: 'Record a dose', exact: true }).click();
  await page.getByRole('dialog', { name: 'Record dose', exact: true }).getByRole('button', { name: 'Record dose', exact: true }).click();
  await expect(page.getByTestId('current-supply')).toHaveText('8 tablets');
  await page.goto(locationsUrl);
  await page.getByRole('link', { name: 'Synthetic cabinet', exact: true }).click();
  await page.getByRole('button', { name: 'Delete Location', exact: true }).click();
  const refused = page.waitForResponse(response => response.request().method() === 'POST');
  await page.getByRole('dialog', { name: 'Delete Location', exact: true }).getByRole('button', { name: 'Delete', exact: true }).click();
  expect((await refused).status()).toBe(422);
  await expect(page.getByRole('alert')).toContainText('cannot be deleted');
  await expect(page.getByRole('link', { name: 'Synthetic tablets', exact: true })).toBeVisible();
  const stored = await careFixture.probe();
  expect(stored.takes).toBe(1);
  expect(stored.supply).toBe('8.00');
});
