import { test, expect } from './care-fixtures.mjs';

test.use({ actionTimeout: 10000 });

test('people creation and editing preserve dependent care and existing medication access', async ({ page, careFixture }, testInfo) => {
  test.setTimeout(180000);
  const before = await careFixture.peopleProbe();
  await page.goto('/login');
  await page.getByLabel('Email address', { exact: true }).fill('persistence@example.test');
  await page.getByLabel('Password', { exact: true }).fill('password');
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await page.getByRole('link', { name: 'Synthetic household', exact: true }).click();
  await expect(page.getByRole('link', { name: 'People', exact: true })).toBeVisible({ timeout: 5000 });
  await page.getByRole('link', { name: 'People', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'People', exact: true })).toBeVisible();
  const peopleUrl = page.url();
  await expect(page.getByRole('link', { name: 'Synthetic minor', exact: true })).toHaveCount(0);
  await page.getByRole('link', { name: 'Add Person', exact: true }).click();
  await page.getByLabel('Name', { exact: true }).fill(' ');
  await page.getByLabel('Email', { exact: true }).fill('synthetic-browser-minor@example.test');
  await page.getByLabel('Date of Birth', { exact: true }).fill('2015-02-03');
  await page.getByLabel('Person Type', { exact: true }).selectOption('minor');
  await page.getByLabel('Has capacity to manage own medication', { exact: true }).uncheck();
  const invalid = page.waitForResponse(response => response.request().method() === 'POST');
  await page.getByRole('button', { name: 'Create Person', exact: true }).click();
  expect((await invalid).status()).toBe(422);
  await expect(page.getByLabel('Email', { exact: true })).toHaveValue('synthetic-browser-minor@example.test');
  await expect(page.getByLabel('Date of Birth', { exact: true })).toHaveValue('2015-02-03');
  const nameError = await page.locator('[role="alert"] a[href="#name"]').innerText();
  await expect(page.getByLabel('Name', { exact: true })).toHaveAccessibleDescription(nameError);
  await page.getByLabel('Name', { exact: true }).fill('Synthetic browser minor');
  await page.getByRole('button', { name: 'Create Person', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Synthetic browser minor', exact: true })).toBeVisible();
  const created = await careFixture.peopleProbe();
  expect(created.person_type).toBe(1);
  expect(created.has_capacity).toBe(false);
  expect(created.manage_grant).toBe(true);
  expect(created.carer).toBe(true);
  expect(created.home).toBe(true);
  expect(created.permissions_version).toBeGreaterThan(before.permissions_version);
  await page.getByRole('link', { name: 'Edit Person', exact: true }).click();
  await expect(page.getByLabel('Person Type', { exact: true })).toHaveValue('minor');
  await expect(page.getByLabel('Has capacity to manage own medication', { exact: true })).not.toBeChecked();
  await page.getByLabel('Name', { exact: true }).fill(' ');
  const invalidEdit = page.waitForResponse(response => response.request().method() === 'POST');
  await page.getByRole('button', { name: 'Update Person', exact: true }).click();
  expect((await invalidEdit).status()).toBe(422);
  await expect(page.getByLabel('Name', { exact: true })).toHaveValue(' ');
  await page.getByLabel('Name', { exact: true }).fill('Synthetic edited minor');
  await page.getByRole('button', { name: 'Update Person', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Synthetic edited minor', exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath(`loco-person-${testInfo.project.name}.png`), fullPage: true });
  await page.goto(peopleUrl);
  await expect(page.getByRole('link', { name: 'Synthetic edited minor', exact: true })).toBeVisible();
  await page.getByRole('link', { name: 'Synthetic adult', exact: true }).click();
  await page.getByRole('link', { name: 'Synthetic tablets', exact: true }).click();
  await page.getByRole('button', { name: 'Record dose', exact: true }).click();
  await expect(page.getByTestId('current-supply')).toHaveText('8 tablets');
  expect((await careFixture.probe()).takes).toBe(1);
  expect([403, 404]).toContain((await page.request.get(`${peopleUrl}/73002`, { maxRedirects: 0 })).status());
});
