generatorName: kotlin
library: jvm-okhttp4
packageName: io.medtracker.client
apiPackage: io.medtracker.password.client.apis
modelPackage: io.medtracker.client.models
invokerPackage: io.medtracker.client.infrastructure
groupId: io.medtracker
artifactId: medtracker-password-api-client
artifactVersion: 0.1.0
serializationLibrary: moshi
dateLibrary: java8
hideGenerationTimestamp: true
enumUnknownDefaultCase: true
modelNameMappings:
  Error: ApiError
reservedWordsMappings:
  Error: ApiError
sortModelPropertiesByRequiredFlag: true
