/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.medtracker.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param householdId 
 * @param membershipId 
 * @param personId 
 * @param role 
 */


data class AcceptedInvitationMembership (

    @Json(name = "household_id")
    val householdId: kotlin.String,

    @Json(name = "membership_id")
    val membershipId: kotlin.String,

    @Json(name = "person_id")
    val personId: kotlin.String?,

    @Json(name = "role")
    val role: AcceptedInvitationMembership.Role

) {

    /**
     * 
     *
     * Values: owner,administrator,member,unknown_default_open_api
     */
    @JsonClass(generateAdapter = false)
    enum class Role(val value: kotlin.String) {
        @Json(name = "owner") owner("owner"),
        @Json(name = "administrator") administrator("administrator"),
        @Json(name = "member") member("member"),
        @Json(name = "unknown_default_open_api") unknown_default_open_api("unknown_default_open_api");
    }

}

