/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.medtracker.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name 
 * @param barcode 
 * @param dmdCode 
 * @param dmdSystem 
 * @param dmdConceptClass 
 * @param category 
 * @param description 
 */


data class AiMedicationIdentity (

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "barcode")
    val barcode: kotlin.String? = null,

    @Json(name = "dmd_code")
    val dmdCode: kotlin.String? = null,

    @Json(name = "dmd_system")
    val dmdSystem: kotlin.String? = null,

    @Json(name = "dmd_concept_class")
    val dmdConceptClass: kotlin.String? = null,

    @Json(name = "category")
    val category: kotlin.String? = null,

    @Json(name = "description")
    val description: kotlin.String? = null

) {


}

