/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.medtracker.client.models

import io.medtracker.client.models.AiMedicationIdentity

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param medication 
 */


data class AiMedicationSuggestionRequest (

    @Json(name = "medication")
    val medication: AiMedicationIdentity? = null

) {


}

