/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.medtracker.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param code 
 * @param message 
 * @param requestId 
 * @param errors 
 */


data class ApiError (

    @Json(name = "code")
    val code: kotlin.String,

    @Json(name = "message")
    val message: kotlin.String,

    @Json(name = "request_id")
    val requestId: kotlin.String,

    @Json(name = "errors")
    val errors: kotlin.collections.Map<kotlin.String, kotlin.collections.List<kotlin.String>>? = null

) {


}

