/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.medtracker.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param filename 
 * @param contentType 
 * @param base64 
 */


data class BackupZipResponseData (

    @Json(name = "filename")
    val filename: kotlin.String,

    @Json(name = "content_type")
    val contentType: BackupZipResponseData.ContentType,

    @Json(name = "base64")
    val base64: kotlin.ByteArray

) {

    /**
     * 
     *
     * Values: applicationSlashZip,unknown_default_open_api
     */
    @JsonClass(generateAdapter = false)
    enum class ContentType(val value: kotlin.String) {
        @Json(name = "application/zip") applicationSlashZip("application/zip"),
        @Json(name = "unknown_default_open_api") unknown_default_open_api("unknown_default_open_api");
    }

}

