/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.medtracker.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param actions 
 * @param versionRequired 
 * @param maxPageSize 
 */


data class CapabilityMedicationReviews (

    @Json(name = "actions")
    val actions: kotlin.collections.List<CapabilityMedicationReviews.Actions>,

    @Json(name = "version_required")
    val versionRequired: kotlin.Boolean,

    @Json(name = "max_page_size")
    val maxPageSize: kotlin.Int

) {

    /**
     * 
     *
     * Values: index,show,update,unknown_default_open_api
     */
    @JsonClass(generateAdapter = false)
    enum class Actions(val value: kotlin.String) {
        @Json(name = "index") index("index"),
        @Json(name = "show") show("show"),
        @Json(name = "update") update("update"),
        @Json(name = "unknown_default_open_api") unknown_default_open_api("unknown_default_open_api");
    }

}

