/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.medtracker.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param supported Whether the MCP server is supported.
 * @param transport 
 * @param endpoint 
 * @param stdioBinary 
 * @param tools 
 * @param resources 
 */


data class CapabilityMcpServer (

    /* Whether the MCP server is supported. */
    @Json(name = "supported")
    val supported: kotlin.Boolean,

    @Json(name = "transport")
    val transport: CapabilityMcpServer.Transport,

    @Json(name = "endpoint")
    val endpoint: CapabilityMcpServer.Endpoint,

    @Json(name = "stdio_binary")
    val stdioBinary: CapabilityMcpServer.StdioBinary,

    @Json(name = "tools")
    val tools: kotlin.collections.List<kotlin.String>,

    @Json(name = "resources")
    val resources: kotlin.collections.List<kotlin.String>

) {

    /**
     * 
     *
     * Values: streamable_http,unknown_default_open_api
     */
    @JsonClass(generateAdapter = false)
    enum class Transport(val value: kotlin.String) {
        @Json(name = "streamable_http") streamable_http("streamable_http"),
        @Json(name = "unknown_default_open_api") unknown_default_open_api("unknown_default_open_api");
    }
    /**
     * 
     *
     * Values: SlashMcp,unknown_default_open_api
     */
    @JsonClass(generateAdapter = false)
    enum class Endpoint(val value: kotlin.String) {
        @Json(name = "/mcp") SlashMcp("/mcp"),
        @Json(name = "unknown_default_open_api") unknown_default_open_api("unknown_default_open_api");
    }
    /**
     * 
     *
     * Values: medtrackerMinusMcp,unknown_default_open_api
     */
    @JsonClass(generateAdapter = false)
    enum class StdioBinary(val value: kotlin.String) {
        @Json(name = "medtracker-mcp") medtrackerMinusMcp("medtracker-mcp"),
        @Json(name = "unknown_default_open_api") unknown_default_open_api("unknown_default_open_api");
    }

}

