/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.medtracker.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param actions 
 * @param maxBytes 
 * @param contentTypes 
 */


data class CapabilityAvatar (

    @Json(name = "actions")
    val actions: kotlin.collections.List<CapabilityAvatar.Actions>,

    @Json(name = "max_bytes")
    val maxBytes: kotlin.Int,

    @Json(name = "content_types")
    val contentTypes: kotlin.collections.List<CapabilityAvatar.ContentTypes>

) {

    /**
     * 
     *
     * Values: show,update,destroy,unknown_default_open_api
     */
    @JsonClass(generateAdapter = false)
    enum class Actions(val value: kotlin.String) {
        @Json(name = "show") show("show"),
        @Json(name = "update") update("update"),
        @Json(name = "destroy") destroy("destroy"),
        @Json(name = "unknown_default_open_api") unknown_default_open_api("unknown_default_open_api");
    }
    /**
     * 
     *
     * Values: imageSlashPng,imageSlashJpeg,imageSlashWebp,unknown_default_open_api
     */
    @JsonClass(generateAdapter = false)
    enum class ContentTypes(val value: kotlin.String) {
        @Json(name = "image/png") imageSlashPng("image/png"),
        @Json(name = "image/jpeg") imageSlashJpeg("image/jpeg"),
        @Json(name = "image/webp") imageSlashWebp("image/webp"),
        @Json(name = "unknown_default_open_api") unknown_default_open_api("unknown_default_open_api");
    }

}

