/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.medtracker.client.models

import io.medtracker.client.models.CapabilityAdministration
import io.medtracker.client.models.CapabilityAuthentication
import io.medtracker.client.models.CapabilityBackups
import io.medtracker.client.models.CapabilityClientTools
import io.medtracker.client.models.CapabilityFhir
import io.medtracker.client.models.CapabilitySync

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param format 
 * @param apiVersion 
 * @param authentication 
 * @param administration 
 * @param portableFormats 
 * @param backups 
 * @param fhir 
 * @param sync 
 * @param clientTools 
 */


data class Capabilities (

    @Json(name = "format")
    val format: Capabilities.Format,

    @Json(name = "api_version")
    val apiVersion: Capabilities.ApiVersion,

    @Json(name = "authentication")
    val authentication: CapabilityAuthentication,

    @Json(name = "administration")
    val administration: CapabilityAdministration,

    @Json(name = "portable_formats")
    val portableFormats: kotlin.collections.Set<Capabilities.PortableFormats>,

    @Json(name = "backups")
    val backups: CapabilityBackups,

    @Json(name = "fhir")
    val fhir: CapabilityFhir,

    @Json(name = "sync")
    val sync: CapabilitySync,

    @Json(name = "client_tools")
    val clientTools: CapabilityClientTools

) {

    /**
     * 
     *
     * Values: medtrackerPeriodApiPeriodCapabilitiesPeriodV1,unknown_default_open_api
     */
    @JsonClass(generateAdapter = false)
    enum class Format(val value: kotlin.String) {
        @Json(name = "medtracker.api.capabilities.v1") medtrackerPeriodApiPeriodCapabilitiesPeriodV1("medtracker.api.capabilities.v1"),
        @Json(name = "unknown_default_open_api") unknown_default_open_api("unknown_default_open_api");
    }
    /**
     * 
     *
     * Values: v1,unknown_default_open_api
     */
    @JsonClass(generateAdapter = false)
    enum class ApiVersion(val value: kotlin.String) {
        @Json(name = "v1") v1("v1"),
        @Json(name = "unknown_default_open_api") unknown_default_open_api("unknown_default_open_api");
    }
    /**
     * 
     *
     * Values: medtrackerPeriodPortablePeriodV1,medtrackerPeriodPortablePeriodEncryptedPeriodV1,medtrackerPeriodPortablePeriodV2,unknown_default_open_api
     */
    @JsonClass(generateAdapter = false)
    enum class PortableFormats(val value: kotlin.String) {
        @Json(name = "medtracker.portable.v1") medtrackerPeriodPortablePeriodV1("medtracker.portable.v1"),
        @Json(name = "medtracker.portable.encrypted.v1") medtrackerPeriodPortablePeriodEncryptedPeriodV1("medtracker.portable.encrypted.v1"),
        @Json(name = "medtracker.portable.v2") medtrackerPeriodPortablePeriodV2("medtracker.portable.v2"),
        @Json(name = "unknown_default_open_api") unknown_default_open_api("unknown_default_open_api");
    }

}

