/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.medtracker.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param supported Whether OIDC exchange is supported.
 * @param pkceRequired Whether PKCE is required.
 * @param sessionListing Whether clients may list sessions.
 * @param sessionRevocation Whether clients may revoke sessions.
 */


data class CapabilityOidcExchange (

    /* Whether OIDC exchange is supported. */
    @Json(name = "supported")
    val supported: kotlin.Boolean,

    /* Whether PKCE is required. */
    @Json(name = "pkce_required")
    val pkceRequired: kotlin.Boolean,

    /* Whether clients may list sessions. */
    @Json(name = "session_listing")
    val sessionListing: kotlin.Boolean,

    /* Whether clients may revoke sessions. */
    @Json(name = "session_revocation")
    val sessionRevocation: kotlin.Boolean

) {


}

