/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.medtracker.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param sourceTypes 
 * @param maxReadDays 
 * @param actions 
 * @param replacementRequiresVersion 
 */


data class CapabilityDoseOutcomes (

    @Json(name = "source_types")
    val sourceTypes: kotlin.collections.Set<CapabilityDoseOutcomes.SourceTypes>,

    @Json(name = "max_read_days")
    val maxReadDays: kotlin.Int,

    @Json(name = "actions")
    val actions: kotlin.collections.Set<CapabilityDoseOutcomes.Actions>,

    @Json(name = "replacement_requires_version")
    val replacementRequiresVersion: kotlin.Boolean

) {

    /**
     * 
     *
     * Values: schedule,person_medication,unknown_default_open_api
     */
    @JsonClass(generateAdapter = false)
    enum class SourceTypes(val value: kotlin.String) {
        @Json(name = "schedule") schedule("schedule"),
        @Json(name = "person_medication") person_medication("person_medication"),
        @Json(name = "unknown_default_open_api") unknown_default_open_api("unknown_default_open_api");
    }
    /**
     * 
     *
     * Values: not_taken,reopen,take,unknown_default_open_api
     */
    @JsonClass(generateAdapter = false)
    enum class Actions(val value: kotlin.String) {
        @Json(name = "not_taken") not_taken("not_taken"),
        @Json(name = "reopen") reopen("reopen"),
        @Json(name = "take") take("take"),
        @Json(name = "unknown_default_open_api") unknown_default_open_api("unknown_default_open_api");
    }

}

