/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.medtracker.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param formats 
 * @param healthHistory 
 * @param medicationReviews 
 * @param selectedPersonRequired 
 * @param healthHistoryMaxSpanDays 
 */


data class CapabilityReports (

    @Json(name = "formats")
    val formats: kotlin.collections.List<CapabilityReports.Formats>,

    @Json(name = "health_history")
    val healthHistory: kotlin.Boolean,

    @Json(name = "medication_reviews")
    val medicationReviews: kotlin.Boolean,

    @Json(name = "selected_person_required")
    val selectedPersonRequired: kotlin.Boolean,

    @Json(name = "health_history_max_span_days")
    val healthHistoryMaxSpanDays: kotlin.Int

) {

    /**
     * 
     *
     * Values: json,pdf,unknown_default_open_api
     */
    @JsonClass(generateAdapter = false)
    enum class Formats(val value: kotlin.String) {
        @Json(name = "json") json("json"),
        @Json(name = "pdf") pdf("pdf"),
        @Json(name = "unknown_default_open_api") unknown_default_open_api("unknown_default_open_api");
    }

}

