/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.medtracker.client.models

import io.medtracker.client.models.CapabilityOidcExchange

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param methods 
 * @param hostedMobile 
 * @param passwordLogin 
 * @param oidcExchange 
 */


data class CapabilityAuthentication (

    @Json(name = "methods")
    val methods: kotlin.collections.Set<CapabilityAuthentication.Methods>,

    @Json(name = "hosted_mobile")
    val hostedMobile: CapabilityAuthentication.HostedMobile,

    @Json(name = "password_login")
    val passwordLogin: CapabilityAuthentication.PasswordLogin,

    @Json(name = "oidc_exchange")
    val oidcExchange: CapabilityOidcExchange

) {

    /**
     * 
     *
     * Values: bearer_session,api_app_token,unknown_default_open_api
     */
    @JsonClass(generateAdapter = false)
    enum class Methods(val value: kotlin.String) {
        @Json(name = "bearer_session") bearer_session("bearer_session"),
        @Json(name = "api_app_token") api_app_token("api_app_token"),
        @Json(name = "unknown_default_open_api") unknown_default_open_api("unknown_default_open_api");
    }
    /**
     * 
     *
     * Values: oidc_authorization_code_pkce,unknown_default_open_api
     */
    @JsonClass(generateAdapter = false)
    enum class HostedMobile(val value: kotlin.String) {
        @Json(name = "oidc_authorization_code_pkce") oidc_authorization_code_pkce("oidc_authorization_code_pkce"),
        @Json(name = "unknown_default_open_api") unknown_default_open_api("unknown_default_open_api");
    }
    /**
     * 
     *
     * Values: development_or_migration,unknown_default_open_api
     */
    @JsonClass(generateAdapter = false)
    enum class PasswordLogin(val value: kotlin.String) {
        @Json(name = "development_or_migration") development_or_migration("development_or_migration"),
        @Json(name = "unknown_default_open_api") unknown_default_open_api("unknown_default_open_api");
    }

}

