/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.medtracker.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param actions 
 * @param versionRequired 
 * @param personMemberships 
 * @param membershipsOnlineOnly 
 */


data class CapabilityLocationManagement (

    @Json(name = "actions")
    val actions: kotlin.collections.List<CapabilityLocationManagement.Actions>,

    @Json(name = "version_required")
    val versionRequired: kotlin.Boolean,

    @Json(name = "person_memberships")
    val personMemberships: kotlin.collections.List<CapabilityLocationManagement.PersonMemberships>,

    @Json(name = "memberships_online_only")
    val membershipsOnlineOnly: kotlin.Boolean

) {

    /**
     * 
     *
     * Values: create,update,destroy,unknown_default_open_api
     */
    @JsonClass(generateAdapter = false)
    enum class Actions(val value: kotlin.String) {
        @Json(name = "create") create("create"),
        @Json(name = "update") update("update"),
        @Json(name = "destroy") destroy("destroy"),
        @Json(name = "unknown_default_open_api") unknown_default_open_api("unknown_default_open_api");
    }
    /**
     * 
     *
     * Values: create,destroy,unknown_default_open_api
     */
    @JsonClass(generateAdapter = false)
    enum class PersonMemberships(val value: kotlin.String) {
        @Json(name = "create") create("create"),
        @Json(name = "destroy") destroy("destroy"),
        @Json(name = "unknown_default_open_api") unknown_default_open_api("unknown_default_open_api");
    }

}

