/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.medtracker.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param portableId 
 * @param medicationId 
 * @param medicationPortableId 
 * @param amount 
 * @param unit 
 * @param frequency 
 * @param description 
 * @param defaultForAdults 
 * @param defaultForChildren 
 * @param defaultMaxDailyDoses 
 * @param defaultMinHoursBetweenDoses 
 * @param defaultDoseCycle 
 * @param currentSupply 
 * @param reorderThreshold 
 * @param updatedAt 
 */


data class DosageOption (

    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "portable_id")
    val portableId: java.util.UUID,

    @Json(name = "medication_id")
    val medicationId: kotlin.Int,

    @Json(name = "medication_portable_id")
    val medicationPortableId: java.util.UUID,

    @Json(name = "amount")
    val amount: kotlin.String,

    @Json(name = "unit")
    val unit: kotlin.String,

    @Json(name = "frequency")
    val frequency: kotlin.String,

    @Json(name = "description")
    val description: kotlin.String?,

    @Json(name = "default_for_adults")
    val defaultForAdults: kotlin.Boolean,

    @Json(name = "default_for_children")
    val defaultForChildren: kotlin.Boolean,

    @Json(name = "default_max_daily_doses")
    val defaultMaxDailyDoses: kotlin.Int,

    @Json(name = "default_min_hours_between_doses")
    val defaultMinHoursBetweenDoses: kotlin.String,

    @Json(name = "default_dose_cycle")
    val defaultDoseCycle: DosageOption.DefaultDoseCycle,

    @Json(name = "current_supply")
    val currentSupply: kotlin.String?,

    @Json(name = "reorder_threshold")
    val reorderThreshold: kotlin.String?,

    @Json(name = "updated_at")
    val updatedAt: java.time.OffsetDateTime

) {

    /**
     * 
     *
     * Values: daily,weekly,monthly,unknown_default_open_api
     */
    @JsonClass(generateAdapter = false)
    enum class DefaultDoseCycle(val value: kotlin.String) {
        @Json(name = "daily") daily("daily"),
        @Json(name = "weekly") weekly("weekly"),
        @Json(name = "monthly") monthly("monthly"),
        @Json(name = "unknown_default_open_api") unknown_default_open_api("unknown_default_open_api");
    }

}

