/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.medtracker.client.models

import io.medtracker.client.models.ReportHealthEvent
import io.medtracker.client.models.ReportMedicationTake
import io.medtracker.client.models.ReportMedicine
import io.medtracker.client.models.ReportPerson

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param person 
 * @param startDate 
 * @param endDate 
 * @param generatedAt 
 * @param currentMedicines 
 * @param chronology 
 * @param medicationTakes 
 */


data class HealthHistoryReport (

    @Json(name = "person")
    val person: ReportPerson,

    @Json(name = "start_date")
    val startDate: java.time.LocalDate,

    @Json(name = "end_date")
    val endDate: java.time.LocalDate,

    @Json(name = "generated_at")
    val generatedAt: java.time.OffsetDateTime,

    @Json(name = "current_medicines")
    val currentMedicines: kotlin.collections.List<ReportMedicine>,

    @Json(name = "chronology")
    val chronology: kotlin.collections.List<ReportHealthEvent>,

    @Json(name = "medication_takes")
    val medicationTakes: kotlin.collections.List<ReportMedicationTake>

) {


}

