/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.medtracker.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param role 
 * @param status 
 * @param personId 
 */


data class HouseholdMembershipAttributes (

    @Json(name = "role")
    val role: HouseholdMembershipAttributes.Role? = null,

    @Json(name = "status")
    val status: HouseholdMembershipAttributes.Status? = null,

    @Json(name = "person_id")
    val personId: kotlin.Int? = null

) {

    /**
     * 
     *
     * Values: owner,administrator,member,unknown_default_open_api
     */
    @JsonClass(generateAdapter = false)
    enum class Role(val value: kotlin.String) {
        @Json(name = "owner") owner("owner"),
        @Json(name = "administrator") administrator("administrator"),
        @Json(name = "member") member("member"),
        @Json(name = "unknown_default_open_api") unknown_default_open_api("unknown_default_open_api");
    }
    /**
     * 
     *
     * Values: active,suspended,revoked,unknown_default_open_api
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "active") active("active"),
        @Json(name = "suspended") suspended("suspended"),
        @Json(name = "revoked") revoked("revoked"),
        @Json(name = "unknown_default_open_api") unknown_default_open_api("unknown_default_open_api");
    }

}

