/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.medtracker.client.models

import io.medtracker.client.models.MeAccount
import io.medtracker.client.models.Person

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param emailAddress 
 * @param membershipRole 
 * @param active 
 * @param person 
 * @param account 
 */


data class Me (

    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "email_address")
    val emailAddress: kotlin.String,

    @Json(name = "membership_role")
    val membershipRole: Me.MembershipRole?,

    @Json(name = "active")
    val active: kotlin.Boolean,

    @Json(name = "person")
    val person: Person,

    @Json(name = "account")
    val account: MeAccount

) {

    /**
     * 
     *
     * Values: owner,administrator,member,unknown_default_open_api
     */
    @JsonClass(generateAdapter = false)
    enum class MembershipRole(val value: kotlin.String) {
        @Json(name = "owner") owner("owner"),
        @Json(name = "administrator") administrator("administrator"),
        @Json(name = "member") member("member"),
        @Json(name = "unknown_default_open_api") unknown_default_open_api("unknown_default_open_api");
    }

}

