/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.medtracker.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: Medication_search_is_temporarily_unavailablePeriod,unknown_default_open_api
 */

@JsonClass(generateAdapter = false)
enum class MedicationLookupUnavailableError(val value: kotlin.String) {

    @Json(name = "Medication search is temporarily unavailable.")
    Medication_search_is_temporarily_unavailablePeriod("Medication search is temporarily unavailable."),

    @Json(name = "unknown_default_open_api")
    unknown_default_open_api("unknown_default_open_api");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is MedicationLookupUnavailableError) "$data" else null

        /**
         * Returns a valid [MedicationLookupUnavailableError] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): MedicationLookupUnavailableError? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

