/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.medtracker.client.models

import io.medtracker.client.models.MedicationPausePeriod
import io.medtracker.client.models.PaginationMeta

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param `data` 
 * @param meta 
 */


data class MedicationPausePeriodCollectionResponse (

    @Json(name = "data")
    val `data`: kotlin.collections.List<MedicationPausePeriod>,

    @Json(name = "meta")
    val meta: PaginationMeta

) {


}

