/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.medtracker.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param sourceType 
 * @param sourceId 
 * @param reason 
 * @param note 
 */


data class MedicationPausePeriodCreateRequestMedicationPausePeriod (

    @Json(name = "source_type")
    val sourceType: MedicationPausePeriodCreateRequestMedicationPausePeriod.SourceType,

    @Json(name = "source_id")
    val sourceId: java.util.UUID,

    @Json(name = "reason")
    val reason: MedicationPausePeriodCreateRequestMedicationPausePeriod.Reason,

    @Json(name = "note")
    val note: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: schedule,person_medication,unknown_default_open_api
     */
    @JsonClass(generateAdapter = false)
    enum class SourceType(val value: kotlin.String) {
        @Json(name = "schedule") schedule("schedule"),
        @Json(name = "person_medication") person_medication("person_medication"),
        @Json(name = "unknown_default_open_api") unknown_default_open_api("unknown_default_open_api");
    }
    /**
     * 
     *
     * Values: out_of_supply,temporarily_not_needed,clinician_advice,side_effects,other,unknown_default_open_api
     */
    @JsonClass(generateAdapter = false)
    enum class Reason(val value: kotlin.String) {
        @Json(name = "out_of_supply") out_of_supply("out_of_supply"),
        @Json(name = "temporarily_not_needed") temporarily_not_needed("temporarily_not_needed"),
        @Json(name = "clinician_advice") clinician_advice("clinician_advice"),
        @Json(name = "side_effects") side_effects("side_effects"),
        @Json(name = "other") other("other"),
        @Json(name = "unknown_default_open_api") unknown_default_open_api("unknown_default_open_api");
    }

}

