/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.medtracker.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param newQuantity 
 * @param reason 
 */


data class MedicationInventoryAdjustmentRequestAdjustment (

    @Json(name = "new_quantity")
    val newQuantity: kotlin.String,

    @Json(name = "reason")
    val reason: kotlin.String? = null

) {


}

