/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.medtracker.client.models

import io.medtracker.client.models.MedicationLookupExistingMedication
import io.medtracker.client.models.MedicationLookupRelatedMedication
import io.medtracker.client.models.MedicationLookupReviewPrompt
import io.medtracker.client.models.MedicationLookupReviewPromptFilter
import io.medtracker.client.models.MedicationLookupTradeFamily

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param barcode 
 * @param code 
 * @param name 
 * @param description 
 * @param display 
 * @param system 
 * @param conceptClass 
 * @param category 
 * @param tradeFamily 
 * @param tradeFamilyGroup 
 * @param packageSize 
 * @param packageQuantity 
 * @param packageUnit 
 * @param directions 
 * @param warnings 
 * @param pilUrl 
 * @param spcUrl 
 * @param conceptClassLabel 
 * @param sourceLabel 
 * @param matchReason 
 * @param matchReasonLabel 
 * @param relatedMedications 
 * @param reviewPrompts 
 * @param reviewPromptFilter 
 * @param existingMedication 
 */


data class MedicationLookupResult (

    @Json(name = "barcode")
    val barcode: kotlin.String?,

    @Json(name = "code")
    val code: kotlin.String?,

    @Json(name = "name")
    val name: kotlin.String?,

    @Json(name = "description")
    val description: kotlin.String?,

    @Json(name = "display")
    val display: kotlin.String,

    @Json(name = "system")
    val system: kotlin.String?,

    @Json(name = "concept_class")
    val conceptClass: kotlin.String?,

    @Json(name = "category")
    val category: kotlin.String?,

    @Json(name = "trade_family")
    val tradeFamily: MedicationLookupTradeFamily?,

    @Json(name = "trade_family_group")
    val tradeFamilyGroup: MedicationLookupTradeFamily?,

    @Json(name = "package_size")
    val packageSize: kotlin.String?,

    @Json(name = "package_quantity")
    val packageQuantity: kotlin.String?,

    @Json(name = "package_unit")
    val packageUnit: kotlin.String?,

    @Json(name = "directions")
    val directions: kotlin.String?,

    @Json(name = "warnings")
    val warnings: kotlin.String?,

    @Json(name = "pil_url")
    val pilUrl: java.net.URI?,

    @Json(name = "spc_url")
    val spcUrl: java.net.URI?,

    @Json(name = "concept_class_label")
    val conceptClassLabel: kotlin.String?,

    @Json(name = "source_label")
    val sourceLabel: kotlin.String?,

    @Json(name = "match_reason")
    val matchReason: kotlin.String?,

    @Json(name = "match_reason_label")
    val matchReasonLabel: kotlin.String?,

    @Json(name = "related_medications")
    val relatedMedications: kotlin.collections.List<MedicationLookupRelatedMedication>,

    @Json(name = "review_prompts")
    val reviewPrompts: kotlin.collections.List<MedicationLookupReviewPrompt>,

    @Json(name = "review_prompt_filter")
    val reviewPromptFilter: MedicationLookupReviewPromptFilter,

    @Json(name = "existing_medication")
    val existingMedication: MedicationLookupExistingMedication? = null

) {


}

