/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.medtracker.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: needs_review,reviewed_with_practitioner,expected_prescribed_combination,not_relevant,hidden_low_signal,unknown_default_open_api
 */

@JsonClass(generateAdapter = false)
enum class MedicationReviewPromptStatus(val value: kotlin.String) {

    @Json(name = "needs_review")
    needs_review("needs_review"),

    @Json(name = "reviewed_with_practitioner")
    reviewed_with_practitioner("reviewed_with_practitioner"),

    @Json(name = "expected_prescribed_combination")
    expected_prescribed_combination("expected_prescribed_combination"),

    @Json(name = "not_relevant")
    not_relevant("not_relevant"),

    @Json(name = "hidden_low_signal")
    hidden_low_signal("hidden_low_signal"),

    @Json(name = "unknown_default_open_api")
    unknown_default_open_api("unknown_default_open_api");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is MedicationReviewPromptStatus) "$data" else null

        /**
         * Returns a valid [MedicationReviewPromptStatus] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): MedicationReviewPromptStatus? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

