/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.medtracker.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param canCreate 
 * @param canUpdate 
 */


data class MedicationLookupPermissions (

    @Json(name = "can_create")
    val canCreate: kotlin.Boolean,

    @Json(name = "can_update")
    val canUpdate: kotlin.Boolean

) {


}

