/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.medtracker.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param portableId 
 * @param clientUuid 
 * @param scheduleId 
 * @param schedulePortableId 
 * @param personMedicationId 
 * @param personMedicationPortableId 
 * @param takenFromMedicationId 
 * @param takenFromMedicationPortableId 
 * @param takenFromLocationId 
 * @param takenFromLocationPortableId 
 * @param doseAmount 
 * @param doseUnit 
 * @param takenAt 
 * @param updatedAt 
 * @param personId 
 * @param personPortableId 
 * @param medicationId 
 * @param medicationPortableId 
 */


data class MedicationTake (

    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "portable_id")
    val portableId: java.util.UUID,

    @Json(name = "client_uuid")
    val clientUuid: java.util.UUID?,

    @Json(name = "schedule_id")
    val scheduleId: kotlin.Int?,

    @Json(name = "schedule_portable_id")
    val schedulePortableId: java.util.UUID?,

    @Json(name = "person_medication_id")
    val personMedicationId: kotlin.Int?,

    @Json(name = "person_medication_portable_id")
    val personMedicationPortableId: java.util.UUID?,

    @Json(name = "taken_from_medication_id")
    val takenFromMedicationId: kotlin.Int?,

    @Json(name = "taken_from_medication_portable_id")
    val takenFromMedicationPortableId: java.util.UUID?,

    @Json(name = "taken_from_location_id")
    val takenFromLocationId: kotlin.Int?,

    @Json(name = "taken_from_location_portable_id")
    val takenFromLocationPortableId: java.util.UUID?,

    @Json(name = "dose_amount")
    val doseAmount: kotlin.String?,

    @Json(name = "dose_unit")
    val doseUnit: kotlin.String?,

    @Json(name = "taken_at")
    val takenAt: java.time.OffsetDateTime?,

    @Json(name = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    @Json(name = "person_id")
    val personId: kotlin.Int?,

    @Json(name = "person_portable_id")
    val personPortableId: java.util.UUID?,

    @Json(name = "medication_id")
    val medicationId: kotlin.Int?,

    @Json(name = "medication_portable_id")
    val medicationPortableId: java.util.UUID?

) {


}

