/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.medtracker.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param householdMembershipId 
 * @param personId 
 * @param personName 
 * @param accessLevel 
 * @param relationshipType 
 * @param expiresAt 
 * @param revokedAt 
 */


data class PersonAccessGrant (

    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "household_membership_id")
    val householdMembershipId: kotlin.Int,

    @Json(name = "person_id")
    val personId: kotlin.Int,

    @Json(name = "person_name")
    val personName: kotlin.String,

    @Json(name = "access_level")
    val accessLevel: PersonAccessGrant.AccessLevel,

    @Json(name = "relationship_type")
    val relationshipType: PersonAccessGrant.RelationshipType,

    @Json(name = "expires_at")
    val expiresAt: java.time.OffsetDateTime?,

    @Json(name = "revoked_at")
    val revokedAt: java.time.OffsetDateTime?

) {

    /**
     * 
     *
     * Values: view,record,manage,unknown_default_open_api
     */
    @JsonClass(generateAdapter = false)
    enum class AccessLevel(val value: kotlin.String) {
        @Json(name = "view") view("view"),
        @Json(name = "record") record("record"),
        @Json(name = "manage") manage("manage"),
        @Json(name = "unknown_default_open_api") unknown_default_open_api("unknown_default_open_api");
    }
    /**
     * 
     *
     * Values: self,parent,family_member,carer,professional,unknown_default_open_api
     */
    @JsonClass(generateAdapter = false)
    enum class RelationshipType(val value: kotlin.String) {
        @Json(name = "self") self("self"),
        @Json(name = "parent") parent("parent"),
        @Json(name = "family_member") family_member("family_member"),
        @Json(name = "carer") carer("carer"),
        @Json(name = "professional") professional("professional"),
        @Json(name = "unknown_default_open_api") unknown_default_open_api("unknown_default_open_api");
    }

}

