/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.medtracker.client.models

import io.medtracker.client.models.PortableRecords

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param format 
 * @param scope 
 * @param exportedAt 
 * @param sourceInstanceId 
 * @param records 
 */


data class PortableSnapshot (

    @Json(name = "format")
    val format: PortableSnapshot.Format,

    @Json(name = "scope")
    val scope: PortableSnapshot.Scope,

    @Json(name = "exported_at")
    val exportedAt: java.time.OffsetDateTime,

    @Json(name = "source_instance_id")
    val sourceInstanceId: kotlin.String,

    @Json(name = "records")
    val records: PortableRecords

) {

    /**
     * 
     *
     * Values: medtrackerPeriodPortablePeriodV1,unknown_default_open_api
     */
    @JsonClass(generateAdapter = false)
    enum class Format(val value: kotlin.String) {
        @Json(name = "medtracker.portable.v1") medtrackerPeriodPortablePeriodV1("medtracker.portable.v1"),
        @Json(name = "unknown_default_open_api") unknown_default_open_api("unknown_default_open_api");
    }
    /**
     * 
     *
     * Values: single_person,household,unknown_default_open_api
     */
    @JsonClass(generateAdapter = false)
    enum class Scope(val value: kotlin.String) {
        @Json(name = "single_person") single_person("single_person"),
        @Json(name = "household") household("household"),
        @Json(name = "unknown_default_open_api") unknown_default_open_api("unknown_default_open_api");
    }

}

