/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.medtracker.client.models

import io.medtracker.client.models.ApiError
import io.medtracker.client.models.PortableImportResult

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param `data` 
 * @param error 
 */


data class PortableImportUnprocessableResponse (

    @Json(name = "data")
    val `data`: PortableImportResult? = null,

    @Json(name = "error")
    val error: ApiError? = null

) {


}

