/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.medtracker.client.models

import io.medtracker.client.models.PushSubscriptionAttributes

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param pushSubscription 
 */


data class PushSubscriptionCreateRequest (

    @Json(name = "push_subscription")
    val pushSubscription: PushSubscriptionAttributes

) {


}

