/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.medtracker.client.models

import io.medtracker.client.models.NullableMedicationPausePeriod
import io.medtracker.client.models.ScheduleConfig

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param portableId 
 * @param personId 
 * @param personPortableId 
 * @param medicationId 
 * @param medicationPortableId 
 * @param doseAmount 
 * @param doseUnit 
 * @param frequency 
 * @param doseCycle 
 * @param startDate 
 * @param endDate 
 * @param active 
 * @param paused 
 * @param canManage 
 * @param notes 
 * @param updatedAt 
 * @param maxDailyDoses 
 * @param minHoursBetweenDoses 
 * @param scheduleType 
 * @param scheduleConfig 
 * @param currentPausePeriod 
 */


data class Schedule (

    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "portable_id")
    val portableId: java.util.UUID,

    @Json(name = "person_id")
    val personId: kotlin.Int,

    @Json(name = "person_portable_id")
    val personPortableId: java.util.UUID,

    @Json(name = "medication_id")
    val medicationId: kotlin.Int,

    @Json(name = "medication_portable_id")
    val medicationPortableId: java.util.UUID,

    @Json(name = "dose_amount")
    val doseAmount: kotlin.String,

    @Json(name = "dose_unit")
    val doseUnit: kotlin.String,

    @Json(name = "frequency")
    val frequency: kotlin.String?,

    @Json(name = "dose_cycle")
    val doseCycle: Schedule.DoseCycle?,

    @Json(name = "start_date")
    val startDate: java.time.LocalDate,

    @Json(name = "end_date")
    val endDate: java.time.LocalDate,

    @Json(name = "active")
    val active: kotlin.Boolean,

    @Json(name = "paused")
    val paused: kotlin.Boolean,

    @Json(name = "can_manage")
    val canManage: kotlin.Boolean,

    @Json(name = "notes")
    val notes: kotlin.String?,

    @Json(name = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    @Json(name = "max_daily_doses")
    val maxDailyDoses: kotlin.Int?,

    @Json(name = "min_hours_between_doses")
    val minHoursBetweenDoses: kotlin.String?,

    @Json(name = "schedule_type")
    val scheduleType: Schedule.ScheduleType,

    @Json(name = "schedule_config")
    val scheduleConfig: ScheduleConfig,

    @Json(name = "current_pause_period")
    val currentPausePeriod: NullableMedicationPausePeriod? = null

) {

    /**
     * 
     *
     * Values: daily,weekly,monthly,unknown_default_open_api
     */
    @JsonClass(generateAdapter = false)
    enum class DoseCycle(val value: kotlin.String) {
        @Json(name = "daily") daily("daily"),
        @Json(name = "weekly") weekly("weekly"),
        @Json(name = "monthly") monthly("monthly"),
        @Json(name = "unknown_default_open_api") unknown_default_open_api("unknown_default_open_api");
    }
    /**
     * 
     *
     * Values: daily,multiple_daily,weekly,specific_dates,prn,tapering,every_other_day,unknown_default_open_api
     */
    @JsonClass(generateAdapter = false)
    enum class ScheduleType(val value: kotlin.String) {
        @Json(name = "daily") daily("daily"),
        @Json(name = "multiple_daily") multiple_daily("multiple_daily"),
        @Json(name = "weekly") weekly("weekly"),
        @Json(name = "specific_dates") specific_dates("specific_dates"),
        @Json(name = "prn") prn("prn"),
        @Json(name = "tapering") tapering("tapering"),
        @Json(name = "every_other_day") every_other_day("every_other_day"),
        @Json(name = "unknown_default_open_api") unknown_default_open_api("unknown_default_open_api");
    }

}

