/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.medtracker.client.models

import io.medtracker.client.models.SyncBatchResult

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param applied Whether every operation in the batch was applied.
 * @param results 
 */


data class SyncBatchResponseData (

    /* Whether every operation in the batch was applied. */
    @Json(name = "applied")
    val applied: kotlin.Boolean,

    @Json(name = "results")
    val results: kotlin.collections.List<SyncBatchResult>

) {


}

