---
plugins:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-capybara
  - rubocop-rspec_rails
  - rubocop-factory_bot

AllCops:
  NewCops: enable

RSpec/ExampleLength:
  Max: 15
  Exclude:
    - 'spec/system/**/*'
    - 'spec/features/**/*'
    - 'spec/requests/**/*'

RSpec/MultipleExpectations:
  Max: 5
  Exclude:
    - 'spec/system/**/*'
    - 'spec/features/**/*'
    - 'spec/requests/**/*'

RSpec/MultipleMemoizedHelpers:
  Max: 5
  Exclude:
    - 'spec/system/authorization/**/*'
    - 'spec/policies/**/*'

RSpec/NestedGroups:
  Max: 3
  Exclude:
    - 'spec/policies/**/*'

Metrics/BlockLength:
  Max: 100
  Exclude:
    - 'test/system/playwright/**/*'
    - 'spec/**/*_spec.rb'
    - 'config/routes.rb'
    - 'db/schema.rb'
  AllowedMethods:
    - test

Metrics/ClassLength:
  Max: 200
  Exclude:
    - 'test/system/playwright/**/*'
    - 'test/**/*_test.rb'
    - 'db/migrate/**/*'
    - 'app/components/**/*'

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'test/system/playwright/**/*'
    - 'app/controllers/pwa_controller.rb'
    - 'manifest_icons'
    - 'db/migrate/**/*'
    - 'app/views/**/*'
    - 'app/components/**/*'
    - 'app/controllers/**/*'

Metrics/AbcSize:
  Exclude:
    - 'test/system/playwright/**/*'
    - 'db/migrate/**/*'
    - 'app/controllers/**/*'
    - 'app/models/**/*'
    - 'app/components/**/*'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/components/ruby_ui/**/*'

# Disable documentation requirement - not always necessary for Rails apps
Style/Documentation:
  Enabled: false

# Allow long lines in certain contexts
Layout/LineLength:
  Max: 120
  Exclude:
    - 'config/**/*'
    - 'db/**/*'
    - 'app/views/**/*'
    - 'app/controllers/**/*'
    - 'app/components/ruby_ui/**/*'

# Allow case-when for size classes in UI components
Style/HashLikeCase:
  Exclude:
    - 'app/components/ruby_ui/**/*'

# Allow missing super in component base classes
Lint/MissingSuper:
  Exclude:
    - 'app/components/**/*'

# Allow variable numbers in test fixtures
Naming/VariableNumber:
  Exclude:
    - 'test/**/*'

# Allow single-letter form parameter names (f) in components
Naming/MethodParameterName:
  Exclude:
    - 'app/components/**/*'

# Allow useless constant scoping in PWA controller for clarity
Lint/UselessConstantScoping:
  Exclude:
    - 'app/controllers/pwa_controller.rb'

# Ignore boolean column constraint in existing migrations
Rails/ThreeStateBooleanColumn:
  Exclude:
    - 'db/migrate/20250625135502_add_active_to_presciptions.rb'

# Allow non-reversible migrations when intentional (cleanup migrations)
Rails/ReversibleMigration:
  Exclude:
    - 'db/migrate/20250930220140_create_carer_relationships.rb'

# Allow hardcoded notice strings in admin controllers for now
# TODO: Move to locale files when implementing full i18n
Rails/I18nLocaleTexts:
  Exclude:
    - 'app/controllers/admin/**/*'
