---
plugins:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-capybara
  - rubocop-rspec_rails

RSpec/ExampleLength:
  Max: 15
  Exclude:
    - 'spec/system/**/*'
    - 'spec/features/**/*'
    - 'spec/requests/**/*'

RSpec/MultipleExpectations:
  Max: 5
  Exclude:
    - 'spec/system/**/*'
    - 'spec/features/**/*'

Metrics/BlockLength:
  Max: 100
  Exclude:
    - 'test/system/playwright/**/*'
    - 'spec/**/*_spec.rb'
    - 'config/routes.rb'
    - 'db/schema.rb'
  ExcludedMethods:
    - test

Metrics/ClassLength:
  Max: 200
  Exclude:
    - 'test/system/playwright/**/*'
    - 'test/**/*_test.rb'
    - 'db/migrate/**/*'

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'test/system/playwright/**/*'
    - 'app/controllers/pwa_controller.rb'
    - 'manifest_icons'
    - 'db/migrate/**/*'
    - 'app/views/**/*'
    - 'app/components/**/*'
    - 'app/controllers/**/*'

Metrics/AbcSize:
  Exclude:
    - 'test/system/playwright/**/*'
    - 'db/migrate/**/*'
    - 'app/controllers/**/*'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/components/ruby_ui/**/*'

# Disable documentation requirement - not always necessary for Rails apps
Style/Documentation:
  Enabled: false

# Allow long lines in certain contexts
Layout/LineLength:
  Max: 120
  Exclude:
    - 'config/**/*'
    - 'db/**/*'
    - 'app/views/**/*'
    - 'app/controllers/**/*'

# Allow case-when for size classes in UI components
Style/HashLikeCase:
  Exclude:
    - 'app/components/ruby_ui/**/*'

# Allow missing super in component base classes
Lint/MissingSuper:
  Exclude:
    - 'app/components/**/*'

# Allow variable numbers in test fixtures
Naming/VariableNumber:
  Exclude:
    - 'test/**/*'
