---
version: '3'
silent: true

includes:
  dev:
    taskfile: Taskfiles/dev.yml
  test:
    taskfile: Taskfiles/test.yml
  internal:
    taskfile: Taskfiles/internal.yml

tasks:
  default:
    desc: List all available tasks
    summary: Default task - shows all available commands
    silent: true
    cmds: [task --list]

  test:
    desc: Run tests in Docker (optionally specify TEST_FILE=path/to/spec)
    summary: |
      Run RSpec tests in Docker environment
      Usage: task test
      Usage: task test TEST_FILE=spec/models/user_spec.rb
    silent: true
    cmds:
      - task: internal:run
        vars:
          ENVIRONMENT: test
          SERVICE: web
          COMMAND: 'bundle exec rspec {{ .TEST_FILE | default "spec" }}'
          TEST_FILE: '{{ .TEST_FILE | default "spec" }}'


  test-rebuild:
    desc: Rebuild test server (drops database)
    summary: |
      Rebuild test environment and run tests (fresh database)
      Usage: task test-rebuild
    cmds:
      - task: test:rebuild

  rubocop:
    desc: Run RuboCop linter (optionally with autocorrect)
    summary: |
      Run RuboCop linter with optional autocorrect
      Usage: task rubocop
      Usage: task rubocop AUTOCORRECT=true
    vars:
      autocorrect: '{{ .AUTOCORRECT | default "false" }}'
    cmds:
      - 'bundle exec rubocop {{ if eq .autocorrect "true" }}-A{{ end }}'
