---
version: '3'

tasks:
  playwright:
    desc: Run Playwright tests (installs Playwright, sets up DB, runs RSpec)
    cmds:
      - npx playwright install --with-deps chromium
      - bundle exec rails db:create RAILS_ENV=test
      - bundle exec rails db:schema:load RAILS_ENV=test
      - bundle exec rails assets:precompile RAILS_ENV=test
      - bundle exec rspec
    env:
      RAILS_ENV: test

  playwright:quick:
    desc: Run Playwright tests using Docker Compose
    cmds:
      - docker compose -f docker-compose.test.yml build
      - docker compose -f docker-compose.test.yml up -d --force-recreate db_test
      - docker compose -f docker-compose.test.yml up --exit-code-from test
      - docker compose -f docker-compose.test.yml down -v
