---
version: "3"
silent: true

includes:
  dev:
    taskfile: Taskfiles/dev.yml
  test:
    taskfile: Taskfiles/test.yml
  local:
    taskfile: Taskfiles/local.yml
  prod:
    taskfile: Taskfiles/prod.yml
  internal:
    taskfile: Taskfiles/internal.yml
  lighthouse:
    taskfile: Taskfiles/lighthouse.yml
  docs:
    taskfile: Taskfiles/docs.yml

tasks:
  default:
    desc: List all available tasks
    summary: Default task - shows all available commands
    silent: true
    cmds: [task --list]

  test:
    desc: Run tests in Docker (optionally specify TEST_FILE=path/to/spec)
    summary: |
      Run RSpec tests in Docker environment
      Usage: task test
      Usage: task test TEST_FILE=spec/models/user_spec.rb
    silent: true
    cmds:
      - task: internal:run
        vars:
          ENVIRONMENT: test
          COMMAND: 'bundle exec rspec --profile 20 --format documentation {{ .TEST_FILE | default "spec" }}'
          TEST_FILE: '{{ .TEST_FILE | default "spec" }}'

  status:
    desc: Get current status of the project
    summary: |
      Run RSpec tests in Docker and verify project readiness with bd ready
      Usage: task status
    silent: true
    cmds:
      - task: internal:run
        vars:
          ENVIRONMENT: test
          COMMAND: "bundle exec rspec --format json"
      - cmd: bd ready

  stop-all:
    desc: Stop all services for this worktree (dev, test, prod)
    summary: |
      Stop all Docker containers, networks, and services for this branch/worktree.
      Use when finished with a branch or worktree.
      Usage: task stop-all
    cmds:
      - task: internal:stop
        vars: { ENVIRONMENT: dev }
      - task: internal:stop
        vars: { ENVIRONMENT: test }
      - task: internal:stop
        vars: { ENVIRONMENT: prod }

  rubocop:
    desc: Run RuboCop linter (optionally with autocorrect)
    summary: |
      Run RuboCop linter with optional autocorrect
      Usage: task rubocop
      Usage: task rubocop AUTOCORRECT=true
    vars:
      autocorrect: '{{ .AUTOCORRECT | default "false" }}'
    cmds:
      - 'bundle exec rubocop --force-exclusion {{ if eq .autocorrect "true" }}-A{{ end }}'
