---
# Main Taskfile - Entry point for all task commands
# See Taskfiles/README.md for detailed documentation
version: '3'
silent: true

# Include modular taskfiles under namespaces
# - dev: Development environment commands (task dev:up, dev:rebuild, etc.)
# - test: Test environment commands (task test:up, test:rebuild, etc.)
# - internal: Reusable Docker Compose operations (internal use only)
includes:
  dev:
    taskfile: Taskfiles/dev.yml
  test:
    taskfile: Taskfiles/test.yml
  internal:
    taskfile: Taskfiles/internal.yml

tasks:
  # Default task - shows all available commands
  default:
    desc: List all available tasks
    silent: true
    cmds:
      - task --list

  # Run RSpec tests in Docker
  # Usage: task test
  # Usage: task test TEST_FILE=spec/models/user_spec.rb
  test:
    desc: Run tests in Docker (optionally specify TEST_FILE=path/to/spec)
    silent: true
    cmds:
      # - task: internal:build
      #   vars:
      #     ENVIRONMENT: test
      - task: internal:run
        vars:
          ENVIRONMENT: test
          SERVICE: web
          COMMAND: 'bundle exec rspec {{ .TEST_FILE | default "spec" }}'
          TEST_FILE: '{{ .TEST_FILE | default "spec" }}'
      # - task: internal:stop
      #   vars:
      #     ENVIRONMENT: test

  # Run RuboCop linter
  # Usage: task rubocop
  # Usage: task rubocop AUTOCORRECT=true
  rubocop:
    desc: Run RuboCop linter (optionally with autocorrect)
    vars:
      autocorrect: '{{ .AUTOCORRECT | default "false" }}'
    cmds:
      - 'bundle exec rubocop {{ if eq .autocorrect "true" }}-A{{ end }}'
