---
version: '3'
includes:
  internal:
    taskfile: Taskfile.internal.yml

tasks:
  test:
    desc: Run tests in Docker (optionally specify TEST_FILE=path/to/spec)
    cmds:
      - task: internal:build
        vars:
          ENVIRONMENT: test
      - task: internal:run
        vars:
          ENVIRONMENT: test
          SERVICE: web
        COMMAND: 'bundle exec rspec {{ .TEST_FILE | default "spec" }}'
      - task: internal:stop
        vars:
          ENVIRONMENT: test

  dev-up:
    cmds:
      - task: internal:up
        vars: {ENVIRONMENT: dev}

  dev-seed:
    desc: Seed development database with fixtures
    cmds:
      - task: internal:seed
        vars: {ENVIRONMENT: dev}

  dev-stop:
    desc: Stop development server
    cmds:
      - task: internal:stop
        vars: {ENVIRONMENT: dev}

  dev-rebuild:
    desc: Rebuild development server
    cmds:
      - task: internal:stop
        vars: {ENVIRONMENT: dev}
      - task: internal:build
        vars:
          ENVIRONMENT: dev
          NO_CACHE: true
      - task: internal:up
        vars: {ENVIRONMENT: dev}
      - task: internal:seed
        vars: {ENVIRONMENT: dev}

  dev-logs:
    desc: View development server logs
    cmds:
      - task: internal:logs
        vars: {ENVIRONMENT: dev}

  test-up:
    cmds:
      - task: internal:up
        vars: {ENVIRONMENT: test}

  test-seed:
    desc: Seed test database with fixtures
    cmds:
      - task: internal:seed
        vars: {ENVIRONMENT: test}

  test-stop:
    desc: Stop test server
    cmds:
      - task: internal:stop
        vars: {ENVIRONMENT: test}

  test-rebuild:
    desc: Rebuild test server
    cmds:
      - task: internal:stop
        vars: {ENVIRONMENT: test}
      - cmd: docker compose build --no-cache web
      - task: internal:up
        vars: {ENVIRONMENT: test}
      - task: internal:seed
        vars: {ENVIRONMENT: test}

  test-logs:
    desc: View test server logs
    cmds:
      - task: internal:logs
        vars: {ENVIRONMENT: test}
