---
version: '3'

tasks:
  local:test:
    desc: Run Playwright tests (installs Playwright, sets up DB, runs RSpec)
    cmds:
      - npx playwright install --with-deps chromium
      - bin/test-local
    env:
      RAILS_ENV: test

  local:rubocop:
    desc: Run Rubocop tests (installs Playwright, sets up DB, runs RSpec)
    cmds:
      - bundle exec rubocop

  compose:test:
    desc: Run RSpecs tests using Docker Compose
    vars:
      ENVIRONMENT: test
    cmds:
      - docker compose -f docker-compose.{{ .ENVIRONMENT }}.yml build
      - docker compose -f docker-compose.{{ .ENVIRONMENT }}.yml run {{ .ENVIRONMENT }}
      - docker compose -f docker-compose.{{ .ENVIRONMENT }}.yml down

  compose:dev:
    desc: Run Rails server using Docker Compose
    vars:
      ENVIRONMENT: dev
    cmds:
      - docker compose -f docker-compose.{{ .ENVIRONMENT }}.yml up -d
      - echo "Visit http://localhost:3000 to see the app"

  compose:dev:stop:
    desc: Stop Rails server using Docker Compose
    cmds:
      - docker compose -f docker-compose.dev.yml down

  compose:dev:logs:
    desc: Follow logs for Rails server using Docker Compose
    cmds:
      - docker compose -f docker-compose.dev.yml logs
