generatorName: swift6
library: urlsession
projectName: MedTrackerAPI
useSPMFileStructure: true
hideGenerationTimestamp: true
enumUnknownDefaultCase: true
validatable: false
modelNameMappings:
  Error: ApiError
reservedWordsMappings:
  Error: ApiError
sortModelPropertiesByRequiredFlag: true
