[package]
name = "medtracker-web"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.9"
chrono = "0.4.45"
chrono-tz = "0.10.4"
leptos = { version = "0.8.21", features = ["ssr"] }
leptodon = { git = "https://github.com/openanalytics/leptodon.git", rev = "195c8fd78b13718004b1e26b2aad8aee5b451585", features = ["ssr"] }
medtracker-ui-preview = { path = "../ui-preview" }
tokio = { version = "1.53.1", features = ["macros", "net", "rt-multi-thread"] }
