---
# Development Environment Tasks
# All tasks operate on the 'dev' profile (compose.yaml)
# Usage: task dev:<command>
version: "3"

tasks:
  build:
    desc: Build development Docker images
    summary: |
      Build Docker images for development environment.
      Use NO_CACHE=true to force a fresh build.
      Usage: task dev:build
      Usage: task dev:build NO_CACHE=true
    cmds:
      - task: :internal:build
        vars:
          ENVIRONMENT: dev
          NO_CACHE: '{{ .NO_CACHE | default "" }}'

  up:
    desc: Start development server
    summary: |
      Start the development server with all services running in detached mode.
      Database data persists between restarts.

      File changes are automatically synced via bind mount (.:/app).
      Code changes in app/, config/, lib/ are immediately reflected.
      For Gemfile changes, rebuild with: task dev:build && task dev:up

      Usage: task dev:up
    cmds:
      - task: :internal:up
        vars: { ENVIRONMENT: dev }

  seed:
    desc: Seed development database with fixtures
    summary: |
      Seed the development database with fixtures from db/seeds.rb.
      Safe to run multiple times (idempotent if seeds are written correctly).
      Usage: task dev:seed
    cmds:
      - task: :internal:seed
        vars: { ENVIRONMENT: dev }

  stop:
    desc: Stop development server
    summary: |
      Stop the development server and remove containers.
      Database volumes are preserved.
      Usage: task dev:stop
    cmds:
      - task: :internal:stop
        vars: { ENVIRONMENT: dev }

  ps:
    desc: List current status of Docker Compose Stack
    summary: |
      List current status of Docker Compose Stack
      Usage: task dev:ps
    cmds:
      - task: :internal:ps
        vars: { ENVIRONMENT: dev }

  db-migrate:
    desc: Run Rails migrations
    summary: |
      Run Rails migrations on the development database
      Usage: task dev:db-migrate
    cmds:
      - task: :internal:db-migrate
        vars: { ENVIRONMENT: dev }

  rebuild:
    desc: Rebuild development server (drops database)
    summary: |
      Rebuild the development environment from scratch.
      WARNING: This drops the database and all data!
      Use when database migrations have changed or you need a fresh start.
      Usage: task dev:rebuild
    # prompt: This removes all data and rebuilds the development environment. Are you sure?
    cmds:
      - task: :internal:stop
        vars: { ENVIRONMENT: dev, REMOVE_VOLUMES: "true" }
      - task: :internal:build
        vars: { ENVIRONMENT: dev }
      - task: :internal:up
        vars: { ENVIRONMENT: dev }
      - task: :internal:seed
        vars: { ENVIRONMENT: dev }
      - task: :internal:open-ui
        vars: { ENVIRONMENT: dev }

  logs:
    desc: View development server logs
    summary: |
      View and follow development server logs in real-time.
      Press Ctrl+C to stop following.
      Usage: task dev:logs
    cmds:
      - task: :internal:logs
        vars: { ENVIRONMENT: dev }

  seed-medicines:
    desc: Seed medicines from db/seeds/medicines.yml
    summary: |
      Seed the development database with medicines from db/seeds/medicines.yml.
      Idempotent — safe to run multiple times.
      Usage: task dev:seed-medicines
    cmds:
      - task: :internal:run
        vars:
          ENVIRONMENT: dev
          COMMAND: 'rails runner ''load Rails.root.join("db/seeds/seed_medicines.rb")'''

  seed-users:
    desc: Seed initial users via invitations from db/seeds/users.yml
    summary: |
      Send invitation emails to users listed in db/seeds/users.yml.
      Idempotent — skips emails that already have an account or pending invitation.
      Emails are delivered to letter_opener / mailcatcher in development.
      Usage: task dev:seed-users
    cmds:
      - task: :internal:run
        vars:
          ENVIRONMENT: dev
          COMMAND: 'rails runner ''load Rails.root.join("db/seeds/seed_users.rb")'''

  port:
    desc: Print the host port of the running development server
    summary: |
      Print the host port that the development web container is listening on.
      Useful for constructing URLs or scripting against the dev server.
      Usage: task dev:port
    cmds:
      - task: :internal:port
        vars: { ENVIRONMENT: dev }

  open-ui:
    desc: Open development server UI
    summary: |
      Open the development server UI in your default browser.
      Usage: task dev:open-ui
    cmds:
      - task: :internal:open-ui
        vars: { ENVIRONMENT: dev }
