---
# Development Environment Tasks
# All tasks operate on the 'dev' environment (docker-compose.dev.yml)
# Usage: task dev:<command>
version: '3'

tasks:
  # Start the development server
  # Creates and starts all containers in detached mode
  # Database data persists between restarts
  # Usage: task dev:up
  up:
    desc: Start development server
    cmds:
      - task: :internal:up
        vars:
          ENVIRONMENT: dev

  # Seed the development database with fixtures
  # Loads data from db/seeds.rb
  # Safe to run multiple times (idempotent if seeds are written correctly)
  # Usage: task dev:seed
  seed:
    desc: Seed development database with fixtures
    cmds:
      - task: :internal:seed
        vars:
          ENVIRONMENT: dev

  # Stop the development server
  # Removes containers but preserves database volumes
  # Usage: task dev:stop
  stop:
    desc: Stop development server
    cmds:
      - task: :internal:stop
        vars:
          ENVIRONMENT: dev

  # Rebuild development environment from scratch
  # WARNING: This drops the database and all data!
  # Use this when:
  # - Database migrations have changed
  # - Docker images need to be rebuilt
  # - You want a fresh start
  # Usage: task dev:rebuild
  rebuild:
    desc: Rebuild development server (drops database)
    cmds:
      - task: :internal:stop
        vars:
          ENVIRONMENT: dev
      - docker compose -f docker-compose.dev.yml down -v  # Remove volumes (drops database)
      - task: :internal:build
        vars:
          ENVIRONMENT: dev
      - task: :internal:up
        vars:
          ENVIRONMENT: dev
      - task: :internal:run
        vars:
          ENVIRONMENT: dev
          SERVICE: web
          COMMAND: 'rails db:create db:migrate'
      - task: :internal:seed
        vars:
          ENVIRONMENT: dev
      - task: :internal:open-ui
        vars:
          ENVIRONMENT: dev

    # View and follow development server logs
    # Press Ctrl+C to stop following
    # Usage: task dev:logs
    logs:
      desc: View development server logs
      cmds:
      - task: :internal:logs
        vars:
          ENVIRONMENT: dev

  open-ui:
    desc: Open development server UI
    cmds:
      - task: :internal:open-ui
        vars:
          ENVIRONMENT: dev
