---
# Development Environment Tasks
# All tasks operate on the 'dev' environment (docker-compose.dev.yml)
# Usage: task dev:<command>
version: "3"
vars:
  ENVIRONMENT: dev

tasks:
  build:
    desc: Build development Docker images
    summary: |
      Build Docker images for development environment.
      Use NO_CACHE=true to force a fresh build.
      Usage: task dev:build
      Usage: task dev:build NO_CACHE=true
    cmds:
      - task: :internal:build
        vars:
          ENVIRONMENT: dev
          NO_CACHE: '{{ .NO_CACHE | default "" }}'

  up:
    desc: Start development server
    summary: |
      Start the development server with all services running in detached mode.
      Database data persists between restarts.

      File changes are automatically synced via bind mount (.:/app).
      Code changes in app/, config/, lib/ are immediately reflected.
      For Gemfile changes, rebuild with: task dev:build && task dev:up

      Usage: task dev:up
    cmds:
      - task: :internal:up

  seed:
    desc: Seed development database with fixtures
    summary: |
      Seed the development database with fixtures from db/seeds.rb.
      Safe to run multiple times (idempotent if seeds are written correctly).
      Usage: task dev:seed
    cmds:
      - task: :internal:seed

  stop:
    desc: Stop development server
    summary: |
      Stop the development server and remove containers.
      Database volumes are preserved.
      Usage: task dev:stop
    cmds:
      - task: :internal:stop

  build:
    desc: Build development Docker images
    summary: |
      Build Docker images for the development environment.
      For automatic rebuilds on file changes, use 'task dev:watch' instead.
      Usage: task dev:build
    cmds:
      - task: :internal:build

  rebuild:
    desc: Rebuild development server (drops database)
    summary: |
      Rebuild the development environment from scratch.
      WARNING: This drops the database and all data!
      Use when database migrations have changed or you need a fresh start.
      Usage: task dev:rebuild
    cmds:
      - task: :internal:stop
      - docker compose -f docker-compose.dev.yml down -v # Remove volumes (drops database)
      - task: :internal:build
      - task: :internal:up
      - task: :internal:run
        vars:
          SERVICE: web
          COMMAND: "rails db:create db:migrate"
      - task: :internal:seed
      - task: :internal:open-ui

  logs:
    desc: View development server logs
    summary: |
      View and follow development server logs in real-time.
      Press Ctrl+C to stop following.
      Usage: task dev:logs
    cmds:
      - task: :internal:logs

  open-ui:
    desc: Open development server UI
    summary: |
      Open the development server UI in your default browser.
      Usage: task dev:open-ui
    cmds:
      - task: :internal:open-ui
