/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.medtracker.client.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import io.medtracker.client.models.ErrorEnvelope
import io.medtracker.client.models.NativeDeviceTokenCreateRequest
import io.medtracker.client.models.PushSubscriptionCreateRequest
import io.medtracker.client.models.PushTestFailedErrorEnvelope
import io.medtracker.client.models.RateLimitErrorEnvelope

import com.squareup.moshi.Json

import io.medtracker.client.infrastructure.ApiClient
import io.medtracker.client.infrastructure.ApiResponse
import io.medtracker.client.infrastructure.ClientException
import io.medtracker.client.infrastructure.ClientError
import io.medtracker.client.infrastructure.ServerException
import io.medtracker.client.infrastructure.ServerError
import io.medtracker.client.infrastructure.MultiValueMap
import io.medtracker.client.infrastructure.PartConfig
import io.medtracker.client.infrastructure.RequestConfig
import io.medtracker.client.infrastructure.RequestMethod
import io.medtracker.client.infrastructure.ResponseType
import io.medtracker.client.infrastructure.Success
import io.medtracker.client.infrastructure.toMultiValue

open class DevicesApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "/api/v1")
        }
    }

    /**
     * POST /households/{household_id}/native_device_tokens
     * Register a native device token.
     * 
     * @param householdId 
     * @param nativeDeviceTokenCreateRequest 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun createNativeDeviceToken(householdId: kotlin.Int, nativeDeviceTokenCreateRequest: NativeDeviceTokenCreateRequest) : Unit {
        val localVarResponse = createNativeDeviceTokenWithHttpInfo(householdId = householdId, nativeDeviceTokenCreateRequest = nativeDeviceTokenCreateRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /households/{household_id}/native_device_tokens
     * Register a native device token.
     * 
     * @param householdId 
     * @param nativeDeviceTokenCreateRequest 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun createNativeDeviceTokenWithHttpInfo(householdId: kotlin.Int, nativeDeviceTokenCreateRequest: NativeDeviceTokenCreateRequest) : ApiResponse<Unit?> {
        val localVariableConfig = createNativeDeviceTokenRequestConfig(householdId = householdId, nativeDeviceTokenCreateRequest = nativeDeviceTokenCreateRequest)

        return request<NativeDeviceTokenCreateRequest, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createNativeDeviceToken
     *
     * @param householdId 
     * @param nativeDeviceTokenCreateRequest 
     * @return RequestConfig
     */
    fun createNativeDeviceTokenRequestConfig(householdId: kotlin.Int, nativeDeviceTokenCreateRequest: NativeDeviceTokenCreateRequest) : RequestConfig<NativeDeviceTokenCreateRequest> {
        val localVariableBody = nativeDeviceTokenCreateRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/households/{household_id}/native_device_tokens".replace("{"+"household_id"+"}", encodeURIComponent(householdId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /households/{household_id}/push_subscription
     * Register a web push subscription.
     * 
     * @param householdId 
     * @param pushSubscriptionCreateRequest 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun createPushSubscription(householdId: kotlin.Int, pushSubscriptionCreateRequest: PushSubscriptionCreateRequest) : Unit {
        val localVarResponse = createPushSubscriptionWithHttpInfo(householdId = householdId, pushSubscriptionCreateRequest = pushSubscriptionCreateRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /households/{household_id}/push_subscription
     * Register a web push subscription.
     * 
     * @param householdId 
     * @param pushSubscriptionCreateRequest 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun createPushSubscriptionWithHttpInfo(householdId: kotlin.Int, pushSubscriptionCreateRequest: PushSubscriptionCreateRequest) : ApiResponse<Unit?> {
        val localVariableConfig = createPushSubscriptionRequestConfig(householdId = householdId, pushSubscriptionCreateRequest = pushSubscriptionCreateRequest)

        return request<PushSubscriptionCreateRequest, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createPushSubscription
     *
     * @param householdId 
     * @param pushSubscriptionCreateRequest 
     * @return RequestConfig
     */
    fun createPushSubscriptionRequestConfig(householdId: kotlin.Int, pushSubscriptionCreateRequest: PushSubscriptionCreateRequest) : RequestConfig<PushSubscriptionCreateRequest> {
        val localVariableBody = pushSubscriptionCreateRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/households/{household_id}/push_subscription".replace("{"+"household_id"+"}", encodeURIComponent(householdId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /households/{household_id}/native_device_tokens/{id}
     * Revoke a native device token.
     * 
     * @param householdId 
     * @param id 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun deleteNativeDeviceToken(householdId: kotlin.Int, id: kotlin.String) : Unit {
        val localVarResponse = deleteNativeDeviceTokenWithHttpInfo(householdId = householdId, id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /households/{household_id}/native_device_tokens/{id}
     * Revoke a native device token.
     * 
     * @param householdId 
     * @param id 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun deleteNativeDeviceTokenWithHttpInfo(householdId: kotlin.Int, id: kotlin.String) : ApiResponse<Unit?> {
        val localVariableConfig = deleteNativeDeviceTokenRequestConfig(householdId = householdId, id = id)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation deleteNativeDeviceToken
     *
     * @param householdId 
     * @param id 
     * @return RequestConfig
     */
    fun deleteNativeDeviceTokenRequestConfig(householdId: kotlin.Int, id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/households/{household_id}/native_device_tokens/{id}".replace("{"+"household_id"+"}", encodeURIComponent(householdId.toString())).replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /households/{household_id}/push_subscription
     * Revoke a web push subscription.
     * 
     * @param householdId 
     * @param endpoint 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun deletePushSubscription(householdId: kotlin.Int, endpoint: java.net.URI) : Unit {
        val localVarResponse = deletePushSubscriptionWithHttpInfo(householdId = householdId, endpoint = endpoint)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /households/{household_id}/push_subscription
     * Revoke a web push subscription.
     * 
     * @param householdId 
     * @param endpoint 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun deletePushSubscriptionWithHttpInfo(householdId: kotlin.Int, endpoint: java.net.URI) : ApiResponse<Unit?> {
        val localVariableConfig = deletePushSubscriptionRequestConfig(householdId = householdId, endpoint = endpoint)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation deletePushSubscription
     *
     * @param householdId 
     * @param endpoint 
     * @return RequestConfig
     */
    fun deletePushSubscriptionRequestConfig(householdId: kotlin.Int, endpoint: java.net.URI) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("endpoint", listOf(endpoint.toString()))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/households/{household_id}/push_subscription".replace("{"+"household_id"+"}", encodeURIComponent(householdId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /households/{household_id}/push_subscription/test
     * Send a test push notification.
     * 
     * @param householdId 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun testPushSubscription(householdId: kotlin.Int) : Unit {
        val localVarResponse = testPushSubscriptionWithHttpInfo(householdId = householdId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /households/{household_id}/push_subscription/test
     * Send a test push notification.
     * 
     * @param householdId 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun testPushSubscriptionWithHttpInfo(householdId: kotlin.Int) : ApiResponse<Unit?> {
        val localVariableConfig = testPushSubscriptionRequestConfig(householdId = householdId)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation testPushSubscription
     *
     * @param householdId 
     * @return RequestConfig
     */
    fun testPushSubscriptionRequestConfig(householdId: kotlin.Int) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/households/{household_id}/push_subscription/test".replace("{"+"household_id"+"}", encodeURIComponent(householdId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
