/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.medtracker.client.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import io.medtracker.client.models.ErrorEnvelope
import io.medtracker.client.models.HealthEventCollectionResponse
import io.medtracker.client.models.HealthEventCreateRequest
import io.medtracker.client.models.HealthEventResponse
import io.medtracker.client.models.HealthEventUpdateRequest
import io.medtracker.client.models.RateLimitErrorEnvelope

import com.squareup.moshi.Json

import io.medtracker.client.infrastructure.ApiClient
import io.medtracker.client.infrastructure.ApiResponse
import io.medtracker.client.infrastructure.ClientException
import io.medtracker.client.infrastructure.ClientError
import io.medtracker.client.infrastructure.ServerException
import io.medtracker.client.infrastructure.ServerError
import io.medtracker.client.infrastructure.MultiValueMap
import io.medtracker.client.infrastructure.PartConfig
import io.medtracker.client.infrastructure.RequestConfig
import io.medtracker.client.infrastructure.RequestMethod
import io.medtracker.client.infrastructure.ResponseType
import io.medtracker.client.infrastructure.Success
import io.medtracker.client.infrastructure.toMultiValue

open class HealthEventsApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "/api/v1")
        }
    }

    /**
     * POST /households/{household_id}/health_events
     * Create a health event.
     * 
     * @param householdId 
     * @param healthEventCreateRequest 
     * @return HealthEventResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun createHealthEvent(householdId: kotlin.Int, healthEventCreateRequest: HealthEventCreateRequest) : HealthEventResponse {
        val localVarResponse = createHealthEventWithHttpInfo(householdId = householdId, healthEventCreateRequest = healthEventCreateRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as HealthEventResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /households/{household_id}/health_events
     * Create a health event.
     * 
     * @param householdId 
     * @param healthEventCreateRequest 
     * @return ApiResponse<HealthEventResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun createHealthEventWithHttpInfo(householdId: kotlin.Int, healthEventCreateRequest: HealthEventCreateRequest) : ApiResponse<HealthEventResponse?> {
        val localVariableConfig = createHealthEventRequestConfig(householdId = householdId, healthEventCreateRequest = healthEventCreateRequest)

        return request<HealthEventCreateRequest, HealthEventResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createHealthEvent
     *
     * @param householdId 
     * @param healthEventCreateRequest 
     * @return RequestConfig
     */
    fun createHealthEventRequestConfig(householdId: kotlin.Int, healthEventCreateRequest: HealthEventCreateRequest) : RequestConfig<HealthEventCreateRequest> {
        val localVariableBody = healthEventCreateRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/households/{household_id}/health_events".replace("{"+"household_id"+"}", encodeURIComponent(householdId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /households/{household_id}/health_events/{id}
     * Read a health event.
     * 
     * @param householdId 
     * @param id 
     * @return HealthEventResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getHealthEvent(householdId: kotlin.Int, id: kotlin.String) : HealthEventResponse {
        val localVarResponse = getHealthEventWithHttpInfo(householdId = householdId, id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as HealthEventResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /households/{household_id}/health_events/{id}
     * Read a health event.
     * 
     * @param householdId 
     * @param id 
     * @return ApiResponse<HealthEventResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getHealthEventWithHttpInfo(householdId: kotlin.Int, id: kotlin.String) : ApiResponse<HealthEventResponse?> {
        val localVariableConfig = getHealthEventRequestConfig(householdId = householdId, id = id)

        return request<Unit, HealthEventResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getHealthEvent
     *
     * @param householdId 
     * @param id 
     * @return RequestConfig
     */
    fun getHealthEventRequestConfig(householdId: kotlin.Int, id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/households/{household_id}/health_events/{id}".replace("{"+"household_id"+"}", encodeURIComponent(householdId.toString())).replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /households/{household_id}/health_events
     * List visible health events.
     * 
     * @param householdId 
     * @param page  (optional, default to 1)
     * @param perPage  (optional, default to 20)
     * @param updatedSince  (optional)
     * @return HealthEventCollectionResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun listHealthEvents(householdId: kotlin.Int, page: kotlin.Int? = 1, perPage: kotlin.Int? = 20, updatedSince: java.time.OffsetDateTime? = null) : HealthEventCollectionResponse {
        val localVarResponse = listHealthEventsWithHttpInfo(householdId = householdId, page = page, perPage = perPage, updatedSince = updatedSince)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as HealthEventCollectionResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /households/{household_id}/health_events
     * List visible health events.
     * 
     * @param householdId 
     * @param page  (optional, default to 1)
     * @param perPage  (optional, default to 20)
     * @param updatedSince  (optional)
     * @return ApiResponse<HealthEventCollectionResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun listHealthEventsWithHttpInfo(householdId: kotlin.Int, page: kotlin.Int?, perPage: kotlin.Int?, updatedSince: java.time.OffsetDateTime?) : ApiResponse<HealthEventCollectionResponse?> {
        val localVariableConfig = listHealthEventsRequestConfig(householdId = householdId, page = page, perPage = perPage, updatedSince = updatedSince)

        return request<Unit, HealthEventCollectionResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listHealthEvents
     *
     * @param householdId 
     * @param page  (optional, default to 1)
     * @param perPage  (optional, default to 20)
     * @param updatedSince  (optional)
     * @return RequestConfig
     */
    fun listHealthEventsRequestConfig(householdId: kotlin.Int, page: kotlin.Int?, perPage: kotlin.Int?, updatedSince: java.time.OffsetDateTime?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
                if (perPage != null) {
                    put("per_page", listOf(perPage.toString()))
                }
                if (updatedSince != null) {
                    put("updated_since", listOf(parseDateToQueryString(updatedSince)))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/households/{household_id}/health_events".replace("{"+"household_id"+"}", encodeURIComponent(householdId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /households/{household_id}/health_events/{id}
     * Replace a health event.
     * 
     * @param householdId 
     * @param id 
     * @param healthEventUpdateRequest 
     * @param ifMatch  (optional)
     * @return HealthEventResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun replaceHealthEvent(householdId: kotlin.Int, id: kotlin.String, healthEventUpdateRequest: HealthEventUpdateRequest, ifMatch: kotlin.String? = null) : HealthEventResponse {
        val localVarResponse = replaceHealthEventWithHttpInfo(householdId = householdId, id = id, healthEventUpdateRequest = healthEventUpdateRequest, ifMatch = ifMatch)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as HealthEventResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /households/{household_id}/health_events/{id}
     * Replace a health event.
     * 
     * @param householdId 
     * @param id 
     * @param healthEventUpdateRequest 
     * @param ifMatch  (optional)
     * @return ApiResponse<HealthEventResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun replaceHealthEventWithHttpInfo(householdId: kotlin.Int, id: kotlin.String, healthEventUpdateRequest: HealthEventUpdateRequest, ifMatch: kotlin.String?) : ApiResponse<HealthEventResponse?> {
        val localVariableConfig = replaceHealthEventRequestConfig(householdId = householdId, id = id, healthEventUpdateRequest = healthEventUpdateRequest, ifMatch = ifMatch)

        return request<HealthEventUpdateRequest, HealthEventResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation replaceHealthEvent
     *
     * @param householdId 
     * @param id 
     * @param healthEventUpdateRequest 
     * @param ifMatch  (optional)
     * @return RequestConfig
     */
    fun replaceHealthEventRequestConfig(householdId: kotlin.Int, id: kotlin.String, healthEventUpdateRequest: HealthEventUpdateRequest, ifMatch: kotlin.String?) : RequestConfig<HealthEventUpdateRequest> {
        val localVariableBody = healthEventUpdateRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        ifMatch?.apply { localVariableHeaders["If-Match"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/households/{household_id}/health_events/{id}".replace("{"+"household_id"+"}", encodeURIComponent(householdId.toString())).replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PATCH /households/{household_id}/health_events/{id}
     * Update a health event.
     * 
     * @param householdId 
     * @param id 
     * @param healthEventUpdateRequest 
     * @param ifMatch  (optional)
     * @return HealthEventResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun updateHealthEvent(householdId: kotlin.Int, id: kotlin.String, healthEventUpdateRequest: HealthEventUpdateRequest, ifMatch: kotlin.String? = null) : HealthEventResponse {
        val localVarResponse = updateHealthEventWithHttpInfo(householdId = householdId, id = id, healthEventUpdateRequest = healthEventUpdateRequest, ifMatch = ifMatch)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as HealthEventResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PATCH /households/{household_id}/health_events/{id}
     * Update a health event.
     * 
     * @param householdId 
     * @param id 
     * @param healthEventUpdateRequest 
     * @param ifMatch  (optional)
     * @return ApiResponse<HealthEventResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun updateHealthEventWithHttpInfo(householdId: kotlin.Int, id: kotlin.String, healthEventUpdateRequest: HealthEventUpdateRequest, ifMatch: kotlin.String?) : ApiResponse<HealthEventResponse?> {
        val localVariableConfig = updateHealthEventRequestConfig(householdId = householdId, id = id, healthEventUpdateRequest = healthEventUpdateRequest, ifMatch = ifMatch)

        return request<HealthEventUpdateRequest, HealthEventResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation updateHealthEvent
     *
     * @param householdId 
     * @param id 
     * @param healthEventUpdateRequest 
     * @param ifMatch  (optional)
     * @return RequestConfig
     */
    fun updateHealthEventRequestConfig(householdId: kotlin.Int, id: kotlin.String, healthEventUpdateRequest: HealthEventUpdateRequest, ifMatch: kotlin.String?) : RequestConfig<HealthEventUpdateRequest> {
        val localVariableBody = healthEventUpdateRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        ifMatch?.apply { localVariableHeaders["If-Match"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/households/{household_id}/health_events/{id}".replace("{"+"household_id"+"}", encodeURIComponent(householdId.toString())).replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
