/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.medtracker.client.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import io.medtracker.client.models.AdminWriteForbiddenErrorEnvelope
import io.medtracker.client.models.ApiAppTokenCollectionResponse
import io.medtracker.client.models.ApiAppTokenCreateRequest
import io.medtracker.client.models.ApiAppTokenCreateResponse
import io.medtracker.client.models.ErrorEnvelope
import io.medtracker.client.models.HouseholdAdminSettingsResponse
import io.medtracker.client.models.HouseholdAdminSettingsUpdateRequest
import io.medtracker.client.models.HouseholdInvitationCollectionResponse
import io.medtracker.client.models.HouseholdInvitationCreateRequest
import io.medtracker.client.models.HouseholdInvitationResponse
import io.medtracker.client.models.HouseholdMembershipCollectionResponse
import io.medtracker.client.models.HouseholdMembershipResponse
import io.medtracker.client.models.HouseholdMembershipUpdateRequest
import io.medtracker.client.models.PersonAccessGrantCollectionResponse
import io.medtracker.client.models.PersonAccessGrantCreateRequest
import io.medtracker.client.models.PersonAccessGrantResponse
import io.medtracker.client.models.RateLimitErrorEnvelope
import io.medtracker.client.models.SecurityAuditEventCollectionResponse

import com.squareup.moshi.Json

import io.medtracker.client.infrastructure.ApiClient
import io.medtracker.client.infrastructure.ApiResponse
import io.medtracker.client.infrastructure.ClientException
import io.medtracker.client.infrastructure.ClientError
import io.medtracker.client.infrastructure.ServerException
import io.medtracker.client.infrastructure.ServerError
import io.medtracker.client.infrastructure.MultiValueMap
import io.medtracker.client.infrastructure.PartConfig
import io.medtracker.client.infrastructure.RequestConfig
import io.medtracker.client.infrastructure.RequestMethod
import io.medtracker.client.infrastructure.ResponseType
import io.medtracker.client.infrastructure.Success
import io.medtracker.client.infrastructure.toMultiValue

open class HouseholdAdministrationApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "/api/v1")
        }
    }

    /**
     * POST /households/{household_id}/admin/app_tokens
     * Create an API app token.
     * 
     * @param householdId 
     * @param apiAppTokenCreateRequest 
     * @return ApiAppTokenCreateResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun createAppToken(householdId: kotlin.Int, apiAppTokenCreateRequest: ApiAppTokenCreateRequest) : ApiAppTokenCreateResponse {
        val localVarResponse = createAppTokenWithHttpInfo(householdId = householdId, apiAppTokenCreateRequest = apiAppTokenCreateRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ApiAppTokenCreateResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /households/{household_id}/admin/app_tokens
     * Create an API app token.
     * 
     * @param householdId 
     * @param apiAppTokenCreateRequest 
     * @return ApiResponse<ApiAppTokenCreateResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun createAppTokenWithHttpInfo(householdId: kotlin.Int, apiAppTokenCreateRequest: ApiAppTokenCreateRequest) : ApiResponse<ApiAppTokenCreateResponse?> {
        val localVariableConfig = createAppTokenRequestConfig(householdId = householdId, apiAppTokenCreateRequest = apiAppTokenCreateRequest)

        return request<ApiAppTokenCreateRequest, ApiAppTokenCreateResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createAppToken
     *
     * @param householdId 
     * @param apiAppTokenCreateRequest 
     * @return RequestConfig
     */
    fun createAppTokenRequestConfig(householdId: kotlin.Int, apiAppTokenCreateRequest: ApiAppTokenCreateRequest) : RequestConfig<ApiAppTokenCreateRequest> {
        val localVariableBody = apiAppTokenCreateRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/households/{household_id}/admin/app_tokens".replace("{"+"household_id"+"}", encodeURIComponent(householdId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /households/{household_id}/admin/invitations
     * Create a household invitation.
     * 
     * @param householdId 
     * @param householdInvitationCreateRequest 
     * @return HouseholdInvitationResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun createInvitation(householdId: kotlin.Int, householdInvitationCreateRequest: HouseholdInvitationCreateRequest) : HouseholdInvitationResponse {
        val localVarResponse = createInvitationWithHttpInfo(householdId = householdId, householdInvitationCreateRequest = householdInvitationCreateRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as HouseholdInvitationResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /households/{household_id}/admin/invitations
     * Create a household invitation.
     * 
     * @param householdId 
     * @param householdInvitationCreateRequest 
     * @return ApiResponse<HouseholdInvitationResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun createInvitationWithHttpInfo(householdId: kotlin.Int, householdInvitationCreateRequest: HouseholdInvitationCreateRequest) : ApiResponse<HouseholdInvitationResponse?> {
        val localVariableConfig = createInvitationRequestConfig(householdId = householdId, householdInvitationCreateRequest = householdInvitationCreateRequest)

        return request<HouseholdInvitationCreateRequest, HouseholdInvitationResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createInvitation
     *
     * @param householdId 
     * @param householdInvitationCreateRequest 
     * @return RequestConfig
     */
    fun createInvitationRequestConfig(householdId: kotlin.Int, householdInvitationCreateRequest: HouseholdInvitationCreateRequest) : RequestConfig<HouseholdInvitationCreateRequest> {
        val localVariableBody = householdInvitationCreateRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/households/{household_id}/admin/invitations".replace("{"+"household_id"+"}", encodeURIComponent(householdId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /households/{household_id}/admin/person_access_grants
     * Create a person access grant.
     * 
     * @param householdId 
     * @param personAccessGrantCreateRequest 
     * @return PersonAccessGrantResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun createPersonAccessGrant(householdId: kotlin.Int, personAccessGrantCreateRequest: PersonAccessGrantCreateRequest) : PersonAccessGrantResponse {
        val localVarResponse = createPersonAccessGrantWithHttpInfo(householdId = householdId, personAccessGrantCreateRequest = personAccessGrantCreateRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as PersonAccessGrantResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /households/{household_id}/admin/person_access_grants
     * Create a person access grant.
     * 
     * @param householdId 
     * @param personAccessGrantCreateRequest 
     * @return ApiResponse<PersonAccessGrantResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun createPersonAccessGrantWithHttpInfo(householdId: kotlin.Int, personAccessGrantCreateRequest: PersonAccessGrantCreateRequest) : ApiResponse<PersonAccessGrantResponse?> {
        val localVariableConfig = createPersonAccessGrantRequestConfig(householdId = householdId, personAccessGrantCreateRequest = personAccessGrantCreateRequest)

        return request<PersonAccessGrantCreateRequest, PersonAccessGrantResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createPersonAccessGrant
     *
     * @param householdId 
     * @param personAccessGrantCreateRequest 
     * @return RequestConfig
     */
    fun createPersonAccessGrantRequestConfig(householdId: kotlin.Int, personAccessGrantCreateRequest: PersonAccessGrantCreateRequest) : RequestConfig<PersonAccessGrantCreateRequest> {
        val localVariableBody = personAccessGrantCreateRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/households/{household_id}/admin/person_access_grants".replace("{"+"household_id"+"}", encodeURIComponent(householdId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /households/{household_id}/admin/app_tokens/{id}
     * Revoke an API app token.
     * 
     * @param householdId 
     * @param id 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun deleteAppToken(householdId: kotlin.Int, id: kotlin.Int) : Unit {
        val localVarResponse = deleteAppTokenWithHttpInfo(householdId = householdId, id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /households/{household_id}/admin/app_tokens/{id}
     * Revoke an API app token.
     * 
     * @param householdId 
     * @param id 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun deleteAppTokenWithHttpInfo(householdId: kotlin.Int, id: kotlin.Int) : ApiResponse<Unit?> {
        val localVariableConfig = deleteAppTokenRequestConfig(householdId = householdId, id = id)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation deleteAppToken
     *
     * @param householdId 
     * @param id 
     * @return RequestConfig
     */
    fun deleteAppTokenRequestConfig(householdId: kotlin.Int, id: kotlin.Int) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/households/{household_id}/admin/app_tokens/{id}".replace("{"+"household_id"+"}", encodeURIComponent(householdId.toString())).replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /households/{household_id}/admin/invitations/{id}
     * Revoke a household invitation.
     * 
     * @param householdId 
     * @param id 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun deleteInvitation(householdId: kotlin.Int, id: kotlin.Int) : Unit {
        val localVarResponse = deleteInvitationWithHttpInfo(householdId = householdId, id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /households/{household_id}/admin/invitations/{id}
     * Revoke a household invitation.
     * 
     * @param householdId 
     * @param id 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun deleteInvitationWithHttpInfo(householdId: kotlin.Int, id: kotlin.Int) : ApiResponse<Unit?> {
        val localVariableConfig = deleteInvitationRequestConfig(householdId = householdId, id = id)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation deleteInvitation
     *
     * @param householdId 
     * @param id 
     * @return RequestConfig
     */
    fun deleteInvitationRequestConfig(householdId: kotlin.Int, id: kotlin.Int) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/households/{household_id}/admin/invitations/{id}".replace("{"+"household_id"+"}", encodeURIComponent(householdId.toString())).replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /households/{household_id}/admin/memberships/{id}
     * Revoke a household membership.
     * 
     * @param householdId 
     * @param id 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun deleteMembership(householdId: kotlin.Int, id: kotlin.Int) : Unit {
        val localVarResponse = deleteMembershipWithHttpInfo(householdId = householdId, id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /households/{household_id}/admin/memberships/{id}
     * Revoke a household membership.
     * 
     * @param householdId 
     * @param id 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun deleteMembershipWithHttpInfo(householdId: kotlin.Int, id: kotlin.Int) : ApiResponse<Unit?> {
        val localVariableConfig = deleteMembershipRequestConfig(householdId = householdId, id = id)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation deleteMembership
     *
     * @param householdId 
     * @param id 
     * @return RequestConfig
     */
    fun deleteMembershipRequestConfig(householdId: kotlin.Int, id: kotlin.Int) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/households/{household_id}/admin/memberships/{id}".replace("{"+"household_id"+"}", encodeURIComponent(householdId.toString())).replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /households/{household_id}/admin/person_access_grants/{id}
     * Revoke a person access grant.
     * 
     * @param householdId 
     * @param id 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun deletePersonAccessGrant(householdId: kotlin.Int, id: kotlin.Int) : Unit {
        val localVarResponse = deletePersonAccessGrantWithHttpInfo(householdId = householdId, id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /households/{household_id}/admin/person_access_grants/{id}
     * Revoke a person access grant.
     * 
     * @param householdId 
     * @param id 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun deletePersonAccessGrantWithHttpInfo(householdId: kotlin.Int, id: kotlin.Int) : ApiResponse<Unit?> {
        val localVariableConfig = deletePersonAccessGrantRequestConfig(householdId = householdId, id = id)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation deletePersonAccessGrant
     *
     * @param householdId 
     * @param id 
     * @return RequestConfig
     */
    fun deletePersonAccessGrantRequestConfig(householdId: kotlin.Int, id: kotlin.Int) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/households/{household_id}/admin/person_access_grants/{id}".replace("{"+"household_id"+"}", encodeURIComponent(householdId.toString())).replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /households/{household_id}/admin/settings
     * Read household administration settings.
     * 
     * @param householdId 
     * @return HouseholdAdminSettingsResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getHouseholdAdminSettings(householdId: kotlin.Int) : HouseholdAdminSettingsResponse {
        val localVarResponse = getHouseholdAdminSettingsWithHttpInfo(householdId = householdId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as HouseholdAdminSettingsResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /households/{household_id}/admin/settings
     * Read household administration settings.
     * 
     * @param householdId 
     * @return ApiResponse<HouseholdAdminSettingsResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getHouseholdAdminSettingsWithHttpInfo(householdId: kotlin.Int) : ApiResponse<HouseholdAdminSettingsResponse?> {
        val localVariableConfig = getHouseholdAdminSettingsRequestConfig(householdId = householdId)

        return request<Unit, HouseholdAdminSettingsResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getHouseholdAdminSettings
     *
     * @param householdId 
     * @return RequestConfig
     */
    fun getHouseholdAdminSettingsRequestConfig(householdId: kotlin.Int) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/households/{household_id}/admin/settings".replace("{"+"household_id"+"}", encodeURIComponent(householdId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /households/{household_id}/admin/app_tokens
     * List API app tokens.
     * 
     * @param householdId 
     * @return ApiAppTokenCollectionResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun listAppTokens(householdId: kotlin.Int) : ApiAppTokenCollectionResponse {
        val localVarResponse = listAppTokensWithHttpInfo(householdId = householdId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ApiAppTokenCollectionResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /households/{household_id}/admin/app_tokens
     * List API app tokens.
     * 
     * @param householdId 
     * @return ApiResponse<ApiAppTokenCollectionResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun listAppTokensWithHttpInfo(householdId: kotlin.Int) : ApiResponse<ApiAppTokenCollectionResponse?> {
        val localVariableConfig = listAppTokensRequestConfig(householdId = householdId)

        return request<Unit, ApiAppTokenCollectionResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listAppTokens
     *
     * @param householdId 
     * @return RequestConfig
     */
    fun listAppTokensRequestConfig(householdId: kotlin.Int) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/households/{household_id}/admin/app_tokens".replace("{"+"household_id"+"}", encodeURIComponent(householdId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /households/{household_id}/admin/audit_logs
     * List household security audit events.
     * 
     * @param householdId 
     * @return SecurityAuditEventCollectionResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun listAuditLogs(householdId: kotlin.Int) : SecurityAuditEventCollectionResponse {
        val localVarResponse = listAuditLogsWithHttpInfo(householdId = householdId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as SecurityAuditEventCollectionResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /households/{household_id}/admin/audit_logs
     * List household security audit events.
     * 
     * @param householdId 
     * @return ApiResponse<SecurityAuditEventCollectionResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun listAuditLogsWithHttpInfo(householdId: kotlin.Int) : ApiResponse<SecurityAuditEventCollectionResponse?> {
        val localVariableConfig = listAuditLogsRequestConfig(householdId = householdId)

        return request<Unit, SecurityAuditEventCollectionResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listAuditLogs
     *
     * @param householdId 
     * @return RequestConfig
     */
    fun listAuditLogsRequestConfig(householdId: kotlin.Int) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/households/{household_id}/admin/audit_logs".replace("{"+"household_id"+"}", encodeURIComponent(householdId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /households/{household_id}/admin/invitations
     * List household invitations.
     * 
     * @param householdId 
     * @return HouseholdInvitationCollectionResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun listInvitations(householdId: kotlin.Int) : HouseholdInvitationCollectionResponse {
        val localVarResponse = listInvitationsWithHttpInfo(householdId = householdId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as HouseholdInvitationCollectionResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /households/{household_id}/admin/invitations
     * List household invitations.
     * 
     * @param householdId 
     * @return ApiResponse<HouseholdInvitationCollectionResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun listInvitationsWithHttpInfo(householdId: kotlin.Int) : ApiResponse<HouseholdInvitationCollectionResponse?> {
        val localVariableConfig = listInvitationsRequestConfig(householdId = householdId)

        return request<Unit, HouseholdInvitationCollectionResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listInvitations
     *
     * @param householdId 
     * @return RequestConfig
     */
    fun listInvitationsRequestConfig(householdId: kotlin.Int) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/households/{household_id}/admin/invitations".replace("{"+"household_id"+"}", encodeURIComponent(householdId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /households/{household_id}/admin/memberships
     * List household memberships.
     * 
     * @param householdId 
     * @return HouseholdMembershipCollectionResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun listMemberships(householdId: kotlin.Int) : HouseholdMembershipCollectionResponse {
        val localVarResponse = listMembershipsWithHttpInfo(householdId = householdId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as HouseholdMembershipCollectionResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /households/{household_id}/admin/memberships
     * List household memberships.
     * 
     * @param householdId 
     * @return ApiResponse<HouseholdMembershipCollectionResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun listMembershipsWithHttpInfo(householdId: kotlin.Int) : ApiResponse<HouseholdMembershipCollectionResponse?> {
        val localVariableConfig = listMembershipsRequestConfig(householdId = householdId)

        return request<Unit, HouseholdMembershipCollectionResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listMemberships
     *
     * @param householdId 
     * @return RequestConfig
     */
    fun listMembershipsRequestConfig(householdId: kotlin.Int) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/households/{household_id}/admin/memberships".replace("{"+"household_id"+"}", encodeURIComponent(householdId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /households/{household_id}/admin/person_access_grants
     * List person access grants.
     * 
     * @param householdId 
     * @return PersonAccessGrantCollectionResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun listPersonAccessGrants(householdId: kotlin.Int) : PersonAccessGrantCollectionResponse {
        val localVarResponse = listPersonAccessGrantsWithHttpInfo(householdId = householdId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as PersonAccessGrantCollectionResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /households/{household_id}/admin/person_access_grants
     * List person access grants.
     * 
     * @param householdId 
     * @return ApiResponse<PersonAccessGrantCollectionResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun listPersonAccessGrantsWithHttpInfo(householdId: kotlin.Int) : ApiResponse<PersonAccessGrantCollectionResponse?> {
        val localVariableConfig = listPersonAccessGrantsRequestConfig(householdId = householdId)

        return request<Unit, PersonAccessGrantCollectionResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listPersonAccessGrants
     *
     * @param householdId 
     * @return RequestConfig
     */
    fun listPersonAccessGrantsRequestConfig(householdId: kotlin.Int) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/households/{household_id}/admin/person_access_grants".replace("{"+"household_id"+"}", encodeURIComponent(householdId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /households/{household_id}/admin/settings
     * Replace household administration settings.
     * 
     * @param householdId 
     * @param householdAdminSettingsUpdateRequest 
     * @return HouseholdAdminSettingsResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun replaceHouseholdAdminSettings(householdId: kotlin.Int, householdAdminSettingsUpdateRequest: HouseholdAdminSettingsUpdateRequest) : HouseholdAdminSettingsResponse {
        val localVarResponse = replaceHouseholdAdminSettingsWithHttpInfo(householdId = householdId, householdAdminSettingsUpdateRequest = householdAdminSettingsUpdateRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as HouseholdAdminSettingsResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /households/{household_id}/admin/settings
     * Replace household administration settings.
     * 
     * @param householdId 
     * @param householdAdminSettingsUpdateRequest 
     * @return ApiResponse<HouseholdAdminSettingsResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun replaceHouseholdAdminSettingsWithHttpInfo(householdId: kotlin.Int, householdAdminSettingsUpdateRequest: HouseholdAdminSettingsUpdateRequest) : ApiResponse<HouseholdAdminSettingsResponse?> {
        val localVariableConfig = replaceHouseholdAdminSettingsRequestConfig(householdId = householdId, householdAdminSettingsUpdateRequest = householdAdminSettingsUpdateRequest)

        return request<HouseholdAdminSettingsUpdateRequest, HouseholdAdminSettingsResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation replaceHouseholdAdminSettings
     *
     * @param householdId 
     * @param householdAdminSettingsUpdateRequest 
     * @return RequestConfig
     */
    fun replaceHouseholdAdminSettingsRequestConfig(householdId: kotlin.Int, householdAdminSettingsUpdateRequest: HouseholdAdminSettingsUpdateRequest) : RequestConfig<HouseholdAdminSettingsUpdateRequest> {
        val localVariableBody = householdAdminSettingsUpdateRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/households/{household_id}/admin/settings".replace("{"+"household_id"+"}", encodeURIComponent(householdId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /households/{household_id}/admin/memberships/{id}
     * Replace a household membership.
     * 
     * @param householdId 
     * @param id 
     * @param householdMembershipUpdateRequest 
     * @return HouseholdMembershipResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun replaceMembership(householdId: kotlin.Int, id: kotlin.Int, householdMembershipUpdateRequest: HouseholdMembershipUpdateRequest) : HouseholdMembershipResponse {
        val localVarResponse = replaceMembershipWithHttpInfo(householdId = householdId, id = id, householdMembershipUpdateRequest = householdMembershipUpdateRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as HouseholdMembershipResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /households/{household_id}/admin/memberships/{id}
     * Replace a household membership.
     * 
     * @param householdId 
     * @param id 
     * @param householdMembershipUpdateRequest 
     * @return ApiResponse<HouseholdMembershipResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun replaceMembershipWithHttpInfo(householdId: kotlin.Int, id: kotlin.Int, householdMembershipUpdateRequest: HouseholdMembershipUpdateRequest) : ApiResponse<HouseholdMembershipResponse?> {
        val localVariableConfig = replaceMembershipRequestConfig(householdId = householdId, id = id, householdMembershipUpdateRequest = householdMembershipUpdateRequest)

        return request<HouseholdMembershipUpdateRequest, HouseholdMembershipResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation replaceMembership
     *
     * @param householdId 
     * @param id 
     * @param householdMembershipUpdateRequest 
     * @return RequestConfig
     */
    fun replaceMembershipRequestConfig(householdId: kotlin.Int, id: kotlin.Int, householdMembershipUpdateRequest: HouseholdMembershipUpdateRequest) : RequestConfig<HouseholdMembershipUpdateRequest> {
        val localVariableBody = householdMembershipUpdateRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/households/{household_id}/admin/memberships/{id}".replace("{"+"household_id"+"}", encodeURIComponent(householdId.toString())).replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PATCH /households/{household_id}/admin/settings
     * Update household administration settings.
     * 
     * @param householdId 
     * @param householdAdminSettingsUpdateRequest 
     * @return HouseholdAdminSettingsResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun updateHouseholdAdminSettings(householdId: kotlin.Int, householdAdminSettingsUpdateRequest: HouseholdAdminSettingsUpdateRequest) : HouseholdAdminSettingsResponse {
        val localVarResponse = updateHouseholdAdminSettingsWithHttpInfo(householdId = householdId, householdAdminSettingsUpdateRequest = householdAdminSettingsUpdateRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as HouseholdAdminSettingsResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PATCH /households/{household_id}/admin/settings
     * Update household administration settings.
     * 
     * @param householdId 
     * @param householdAdminSettingsUpdateRequest 
     * @return ApiResponse<HouseholdAdminSettingsResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun updateHouseholdAdminSettingsWithHttpInfo(householdId: kotlin.Int, householdAdminSettingsUpdateRequest: HouseholdAdminSettingsUpdateRequest) : ApiResponse<HouseholdAdminSettingsResponse?> {
        val localVariableConfig = updateHouseholdAdminSettingsRequestConfig(householdId = householdId, householdAdminSettingsUpdateRequest = householdAdminSettingsUpdateRequest)

        return request<HouseholdAdminSettingsUpdateRequest, HouseholdAdminSettingsResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation updateHouseholdAdminSettings
     *
     * @param householdId 
     * @param householdAdminSettingsUpdateRequest 
     * @return RequestConfig
     */
    fun updateHouseholdAdminSettingsRequestConfig(householdId: kotlin.Int, householdAdminSettingsUpdateRequest: HouseholdAdminSettingsUpdateRequest) : RequestConfig<HouseholdAdminSettingsUpdateRequest> {
        val localVariableBody = householdAdminSettingsUpdateRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/households/{household_id}/admin/settings".replace("{"+"household_id"+"}", encodeURIComponent(householdId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PATCH /households/{household_id}/admin/memberships/{id}
     * Update a household membership.
     * 
     * @param householdId 
     * @param id 
     * @param householdMembershipUpdateRequest 
     * @return HouseholdMembershipResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun updateMembership(householdId: kotlin.Int, id: kotlin.Int, householdMembershipUpdateRequest: HouseholdMembershipUpdateRequest) : HouseholdMembershipResponse {
        val localVarResponse = updateMembershipWithHttpInfo(householdId = householdId, id = id, householdMembershipUpdateRequest = householdMembershipUpdateRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as HouseholdMembershipResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PATCH /households/{household_id}/admin/memberships/{id}
     * Update a household membership.
     * 
     * @param householdId 
     * @param id 
     * @param householdMembershipUpdateRequest 
     * @return ApiResponse<HouseholdMembershipResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun updateMembershipWithHttpInfo(householdId: kotlin.Int, id: kotlin.Int, householdMembershipUpdateRequest: HouseholdMembershipUpdateRequest) : ApiResponse<HouseholdMembershipResponse?> {
        val localVariableConfig = updateMembershipRequestConfig(householdId = householdId, id = id, householdMembershipUpdateRequest = householdMembershipUpdateRequest)

        return request<HouseholdMembershipUpdateRequest, HouseholdMembershipResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation updateMembership
     *
     * @param householdId 
     * @param id 
     * @param householdMembershipUpdateRequest 
     * @return RequestConfig
     */
    fun updateMembershipRequestConfig(householdId: kotlin.Int, id: kotlin.Int, householdMembershipUpdateRequest: HouseholdMembershipUpdateRequest) : RequestConfig<HouseholdMembershipUpdateRequest> {
        val localVariableBody = householdMembershipUpdateRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/households/{household_id}/admin/memberships/{id}".replace("{"+"household_id"+"}", encodeURIComponent(householdId.toString())).replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
