/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.medtracker.client.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import io.medtracker.client.models.ErrorEnvelope
import io.medtracker.client.models.MedicationTakeCollectionResponse
import io.medtracker.client.models.MedicationTakeCreateRequest
import io.medtracker.client.models.MedicationTakeResponse
import io.medtracker.client.models.RateLimitErrorEnvelope

import com.squareup.moshi.Json

import io.medtracker.client.infrastructure.ApiClient
import io.medtracker.client.infrastructure.ApiResponse
import io.medtracker.client.infrastructure.ClientException
import io.medtracker.client.infrastructure.ClientError
import io.medtracker.client.infrastructure.ServerException
import io.medtracker.client.infrastructure.ServerError
import io.medtracker.client.infrastructure.MultiValueMap
import io.medtracker.client.infrastructure.PartConfig
import io.medtracker.client.infrastructure.RequestConfig
import io.medtracker.client.infrastructure.RequestMethod
import io.medtracker.client.infrastructure.ResponseType
import io.medtracker.client.infrastructure.Success
import io.medtracker.client.infrastructure.toMultiValue

open class MedicationTakesApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "/api/v1")
        }
    }

    /**
     * POST /households/{household_id}/medication_takes
     * Record a medication take.
     * 
     * @param householdId 
     * @param medicationTakeCreateRequest 
     * @return MedicationTakeResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun createMedicationTake(householdId: kotlin.Int, medicationTakeCreateRequest: MedicationTakeCreateRequest) : MedicationTakeResponse {
        val localVarResponse = createMedicationTakeWithHttpInfo(householdId = householdId, medicationTakeCreateRequest = medicationTakeCreateRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MedicationTakeResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /households/{household_id}/medication_takes
     * Record a medication take.
     * 
     * @param householdId 
     * @param medicationTakeCreateRequest 
     * @return ApiResponse<MedicationTakeResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun createMedicationTakeWithHttpInfo(householdId: kotlin.Int, medicationTakeCreateRequest: MedicationTakeCreateRequest) : ApiResponse<MedicationTakeResponse?> {
        val localVariableConfig = createMedicationTakeRequestConfig(householdId = householdId, medicationTakeCreateRequest = medicationTakeCreateRequest)

        return request<MedicationTakeCreateRequest, MedicationTakeResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createMedicationTake
     *
     * @param householdId 
     * @param medicationTakeCreateRequest 
     * @return RequestConfig
     */
    fun createMedicationTakeRequestConfig(householdId: kotlin.Int, medicationTakeCreateRequest: MedicationTakeCreateRequest) : RequestConfig<MedicationTakeCreateRequest> {
        val localVariableBody = medicationTakeCreateRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/households/{household_id}/medication_takes".replace("{"+"household_id"+"}", encodeURIComponent(householdId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /households/{household_id}/medication_takes
     * List visible medication takes.
     * 
     * @param householdId 
     * @param page  (optional, default to 1)
     * @param perPage  (optional, default to 20)
     * @param updatedSince  (optional)
     * @return MedicationTakeCollectionResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun listMedicationTakes(householdId: kotlin.Int, page: kotlin.Int? = 1, perPage: kotlin.Int? = 20, updatedSince: java.time.OffsetDateTime? = null) : MedicationTakeCollectionResponse {
        val localVarResponse = listMedicationTakesWithHttpInfo(householdId = householdId, page = page, perPage = perPage, updatedSince = updatedSince)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MedicationTakeCollectionResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /households/{household_id}/medication_takes
     * List visible medication takes.
     * 
     * @param householdId 
     * @param page  (optional, default to 1)
     * @param perPage  (optional, default to 20)
     * @param updatedSince  (optional)
     * @return ApiResponse<MedicationTakeCollectionResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun listMedicationTakesWithHttpInfo(householdId: kotlin.Int, page: kotlin.Int?, perPage: kotlin.Int?, updatedSince: java.time.OffsetDateTime?) : ApiResponse<MedicationTakeCollectionResponse?> {
        val localVariableConfig = listMedicationTakesRequestConfig(householdId = householdId, page = page, perPage = perPage, updatedSince = updatedSince)

        return request<Unit, MedicationTakeCollectionResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listMedicationTakes
     *
     * @param householdId 
     * @param page  (optional, default to 1)
     * @param perPage  (optional, default to 20)
     * @param updatedSince  (optional)
     * @return RequestConfig
     */
    fun listMedicationTakesRequestConfig(householdId: kotlin.Int, page: kotlin.Int?, perPage: kotlin.Int?, updatedSince: java.time.OffsetDateTime?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
                if (perPage != null) {
                    put("per_page", listOf(perPage.toString()))
                }
                if (updatedSince != null) {
                    put("updated_since", listOf(parseDateToQueryString(updatedSince)))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/households/{household_id}/medication_takes".replace("{"+"household_id"+"}", encodeURIComponent(householdId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
