/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.medtracker.client.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import io.medtracker.client.models.ErrorEnvelope
import io.medtracker.client.models.MedicationCollectionResponse
import io.medtracker.client.models.MedicationCreateRequest
import io.medtracker.client.models.MedicationInventoryAdjustmentRequest
import io.medtracker.client.models.MedicationOrderDetailsRequest
import io.medtracker.client.models.MedicationResponse
import io.medtracker.client.models.MedicationUpdateRequest
import io.medtracker.client.models.RateLimitErrorEnvelope

import com.squareup.moshi.Json

import io.medtracker.client.infrastructure.ApiClient
import io.medtracker.client.infrastructure.ApiResponse
import io.medtracker.client.infrastructure.ClientException
import io.medtracker.client.infrastructure.ClientError
import io.medtracker.client.infrastructure.ServerException
import io.medtracker.client.infrastructure.ServerError
import io.medtracker.client.infrastructure.MultiValueMap
import io.medtracker.client.infrastructure.PartConfig
import io.medtracker.client.infrastructure.RequestConfig
import io.medtracker.client.infrastructure.RequestMethod
import io.medtracker.client.infrastructure.ResponseType
import io.medtracker.client.infrastructure.Success
import io.medtracker.client.infrastructure.toMultiValue

open class MedicationsApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "/api/v1")
        }
    }

    /**
     * PATCH /households/{household_id}/medications/{id}/adjust_inventory
     * Adjust medication inventory.
     * 
     * @param householdId 
     * @param id 
     * @param medicationInventoryAdjustmentRequest 
     * @return MedicationResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun adjustMedicationInventory(householdId: kotlin.Int, id: kotlin.String, medicationInventoryAdjustmentRequest: MedicationInventoryAdjustmentRequest) : MedicationResponse {
        val localVarResponse = adjustMedicationInventoryWithHttpInfo(householdId = householdId, id = id, medicationInventoryAdjustmentRequest = medicationInventoryAdjustmentRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MedicationResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PATCH /households/{household_id}/medications/{id}/adjust_inventory
     * Adjust medication inventory.
     * 
     * @param householdId 
     * @param id 
     * @param medicationInventoryAdjustmentRequest 
     * @return ApiResponse<MedicationResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun adjustMedicationInventoryWithHttpInfo(householdId: kotlin.Int, id: kotlin.String, medicationInventoryAdjustmentRequest: MedicationInventoryAdjustmentRequest) : ApiResponse<MedicationResponse?> {
        val localVariableConfig = adjustMedicationInventoryRequestConfig(householdId = householdId, id = id, medicationInventoryAdjustmentRequest = medicationInventoryAdjustmentRequest)

        return request<MedicationInventoryAdjustmentRequest, MedicationResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation adjustMedicationInventory
     *
     * @param householdId 
     * @param id 
     * @param medicationInventoryAdjustmentRequest 
     * @return RequestConfig
     */
    fun adjustMedicationInventoryRequestConfig(householdId: kotlin.Int, id: kotlin.String, medicationInventoryAdjustmentRequest: MedicationInventoryAdjustmentRequest) : RequestConfig<MedicationInventoryAdjustmentRequest> {
        val localVariableBody = medicationInventoryAdjustmentRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/households/{household_id}/medications/{id}/adjust_inventory".replace("{"+"household_id"+"}", encodeURIComponent(householdId.toString())).replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /households/{household_id}/medications
     * Create a medication.
     * 
     * @param householdId 
     * @param medicationCreateRequest 
     * @return MedicationResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun createMedication(householdId: kotlin.Int, medicationCreateRequest: MedicationCreateRequest) : MedicationResponse {
        val localVarResponse = createMedicationWithHttpInfo(householdId = householdId, medicationCreateRequest = medicationCreateRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MedicationResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /households/{household_id}/medications
     * Create a medication.
     * 
     * @param householdId 
     * @param medicationCreateRequest 
     * @return ApiResponse<MedicationResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun createMedicationWithHttpInfo(householdId: kotlin.Int, medicationCreateRequest: MedicationCreateRequest) : ApiResponse<MedicationResponse?> {
        val localVariableConfig = createMedicationRequestConfig(householdId = householdId, medicationCreateRequest = medicationCreateRequest)

        return request<MedicationCreateRequest, MedicationResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createMedication
     *
     * @param householdId 
     * @param medicationCreateRequest 
     * @return RequestConfig
     */
    fun createMedicationRequestConfig(householdId: kotlin.Int, medicationCreateRequest: MedicationCreateRequest) : RequestConfig<MedicationCreateRequest> {
        val localVariableBody = medicationCreateRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/households/{household_id}/medications".replace("{"+"household_id"+"}", encodeURIComponent(householdId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /households/{household_id}/medications/{id}
     * Read a medication.
     * 
     * @param householdId 
     * @param id 
     * @return MedicationResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getMedication(householdId: kotlin.Int, id: kotlin.String) : MedicationResponse {
        val localVarResponse = getMedicationWithHttpInfo(householdId = householdId, id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MedicationResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /households/{household_id}/medications/{id}
     * Read a medication.
     * 
     * @param householdId 
     * @param id 
     * @return ApiResponse<MedicationResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getMedicationWithHttpInfo(householdId: kotlin.Int, id: kotlin.String) : ApiResponse<MedicationResponse?> {
        val localVariableConfig = getMedicationRequestConfig(householdId = householdId, id = id)

        return request<Unit, MedicationResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getMedication
     *
     * @param householdId 
     * @param id 
     * @return RequestConfig
     */
    fun getMedicationRequestConfig(householdId: kotlin.Int, id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/households/{household_id}/medications/{id}".replace("{"+"household_id"+"}", encodeURIComponent(householdId.toString())).replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /households/{household_id}/medications
     * List visible medications.
     * 
     * @param householdId 
     * @param page  (optional, default to 1)
     * @param perPage  (optional, default to 20)
     * @param updatedSince  (optional)
     * @return MedicationCollectionResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun listMedications(householdId: kotlin.Int, page: kotlin.Int? = 1, perPage: kotlin.Int? = 20, updatedSince: java.time.OffsetDateTime? = null) : MedicationCollectionResponse {
        val localVarResponse = listMedicationsWithHttpInfo(householdId = householdId, page = page, perPage = perPage, updatedSince = updatedSince)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MedicationCollectionResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /households/{household_id}/medications
     * List visible medications.
     * 
     * @param householdId 
     * @param page  (optional, default to 1)
     * @param perPage  (optional, default to 20)
     * @param updatedSince  (optional)
     * @return ApiResponse<MedicationCollectionResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun listMedicationsWithHttpInfo(householdId: kotlin.Int, page: kotlin.Int?, perPage: kotlin.Int?, updatedSince: java.time.OffsetDateTime?) : ApiResponse<MedicationCollectionResponse?> {
        val localVariableConfig = listMedicationsRequestConfig(householdId = householdId, page = page, perPage = perPage, updatedSince = updatedSince)

        return request<Unit, MedicationCollectionResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listMedications
     *
     * @param householdId 
     * @param page  (optional, default to 1)
     * @param perPage  (optional, default to 20)
     * @param updatedSince  (optional)
     * @return RequestConfig
     */
    fun listMedicationsRequestConfig(householdId: kotlin.Int, page: kotlin.Int?, perPage: kotlin.Int?, updatedSince: java.time.OffsetDateTime?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
                if (perPage != null) {
                    put("per_page", listOf(perPage.toString()))
                }
                if (updatedSince != null) {
                    put("updated_since", listOf(parseDateToQueryString(updatedSince)))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/households/{household_id}/medications".replace("{"+"household_id"+"}", encodeURIComponent(householdId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PATCH /households/{household_id}/medications/{id}/mark_as_ordered
     * Mark a medication reorder as ordered.
     * 
     * @param householdId 
     * @param id 
     * @param medicationOrderDetailsRequest  (optional)
     * @return MedicationResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun markMedicationAsOrdered(householdId: kotlin.Int, id: kotlin.String, medicationOrderDetailsRequest: MedicationOrderDetailsRequest? = null) : MedicationResponse {
        val localVarResponse = markMedicationAsOrderedWithHttpInfo(householdId = householdId, id = id, medicationOrderDetailsRequest = medicationOrderDetailsRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MedicationResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PATCH /households/{household_id}/medications/{id}/mark_as_ordered
     * Mark a medication reorder as ordered.
     * 
     * @param householdId 
     * @param id 
     * @param medicationOrderDetailsRequest  (optional)
     * @return ApiResponse<MedicationResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun markMedicationAsOrderedWithHttpInfo(householdId: kotlin.Int, id: kotlin.String, medicationOrderDetailsRequest: MedicationOrderDetailsRequest?) : ApiResponse<MedicationResponse?> {
        val localVariableConfig = markMedicationAsOrderedRequestConfig(householdId = householdId, id = id, medicationOrderDetailsRequest = medicationOrderDetailsRequest)

        return request<MedicationOrderDetailsRequest, MedicationResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation markMedicationAsOrdered
     *
     * @param householdId 
     * @param id 
     * @param medicationOrderDetailsRequest  (optional)
     * @return RequestConfig
     */
    fun markMedicationAsOrderedRequestConfig(householdId: kotlin.Int, id: kotlin.String, medicationOrderDetailsRequest: MedicationOrderDetailsRequest?) : RequestConfig<MedicationOrderDetailsRequest> {
        val localVariableBody = medicationOrderDetailsRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/households/{household_id}/medications/{id}/mark_as_ordered".replace("{"+"household_id"+"}", encodeURIComponent(householdId.toString())).replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PATCH /households/{household_id}/medications/{id}/mark_as_received
     * Mark a medication reorder as received.
     * 
     * @param householdId 
     * @param id 
     * @return MedicationResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun markMedicationAsReceived(householdId: kotlin.Int, id: kotlin.String) : MedicationResponse {
        val localVarResponse = markMedicationAsReceivedWithHttpInfo(householdId = householdId, id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MedicationResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PATCH /households/{household_id}/medications/{id}/mark_as_received
     * Mark a medication reorder as received.
     * 
     * @param householdId 
     * @param id 
     * @return ApiResponse<MedicationResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun markMedicationAsReceivedWithHttpInfo(householdId: kotlin.Int, id: kotlin.String) : ApiResponse<MedicationResponse?> {
        val localVariableConfig = markMedicationAsReceivedRequestConfig(householdId = householdId, id = id)

        return request<Unit, MedicationResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation markMedicationAsReceived
     *
     * @param householdId 
     * @param id 
     * @return RequestConfig
     */
    fun markMedicationAsReceivedRequestConfig(householdId: kotlin.Int, id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/households/{household_id}/medications/{id}/mark_as_received".replace("{"+"household_id"+"}", encodeURIComponent(householdId.toString())).replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /households/{household_id}/medications/{id}
     * Replace a medication.
     * 
     * @param householdId 
     * @param id 
     * @param medicationUpdateRequest 
     * @param ifMatch  (optional)
     * @return MedicationResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun replaceMedication(householdId: kotlin.Int, id: kotlin.String, medicationUpdateRequest: MedicationUpdateRequest, ifMatch: kotlin.String? = null) : MedicationResponse {
        val localVarResponse = replaceMedicationWithHttpInfo(householdId = householdId, id = id, medicationUpdateRequest = medicationUpdateRequest, ifMatch = ifMatch)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MedicationResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /households/{household_id}/medications/{id}
     * Replace a medication.
     * 
     * @param householdId 
     * @param id 
     * @param medicationUpdateRequest 
     * @param ifMatch  (optional)
     * @return ApiResponse<MedicationResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun replaceMedicationWithHttpInfo(householdId: kotlin.Int, id: kotlin.String, medicationUpdateRequest: MedicationUpdateRequest, ifMatch: kotlin.String?) : ApiResponse<MedicationResponse?> {
        val localVariableConfig = replaceMedicationRequestConfig(householdId = householdId, id = id, medicationUpdateRequest = medicationUpdateRequest, ifMatch = ifMatch)

        return request<MedicationUpdateRequest, MedicationResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation replaceMedication
     *
     * @param householdId 
     * @param id 
     * @param medicationUpdateRequest 
     * @param ifMatch  (optional)
     * @return RequestConfig
     */
    fun replaceMedicationRequestConfig(householdId: kotlin.Int, id: kotlin.String, medicationUpdateRequest: MedicationUpdateRequest, ifMatch: kotlin.String?) : RequestConfig<MedicationUpdateRequest> {
        val localVariableBody = medicationUpdateRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        ifMatch?.apply { localVariableHeaders["If-Match"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/households/{household_id}/medications/{id}".replace("{"+"household_id"+"}", encodeURIComponent(householdId.toString())).replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PATCH /households/{household_id}/medications/{id}
     * Update a medication.
     * 
     * @param householdId 
     * @param id 
     * @param medicationUpdateRequest 
     * @param ifMatch  (optional)
     * @return MedicationResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun updateMedication(householdId: kotlin.Int, id: kotlin.String, medicationUpdateRequest: MedicationUpdateRequest, ifMatch: kotlin.String? = null) : MedicationResponse {
        val localVarResponse = updateMedicationWithHttpInfo(householdId = householdId, id = id, medicationUpdateRequest = medicationUpdateRequest, ifMatch = ifMatch)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MedicationResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PATCH /households/{household_id}/medications/{id}
     * Update a medication.
     * 
     * @param householdId 
     * @param id 
     * @param medicationUpdateRequest 
     * @param ifMatch  (optional)
     * @return ApiResponse<MedicationResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun updateMedicationWithHttpInfo(householdId: kotlin.Int, id: kotlin.String, medicationUpdateRequest: MedicationUpdateRequest, ifMatch: kotlin.String?) : ApiResponse<MedicationResponse?> {
        val localVariableConfig = updateMedicationRequestConfig(householdId = householdId, id = id, medicationUpdateRequest = medicationUpdateRequest, ifMatch = ifMatch)

        return request<MedicationUpdateRequest, MedicationResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation updateMedication
     *
     * @param householdId 
     * @param id 
     * @param medicationUpdateRequest 
     * @param ifMatch  (optional)
     * @return RequestConfig
     */
    fun updateMedicationRequestConfig(householdId: kotlin.Int, id: kotlin.String, medicationUpdateRequest: MedicationUpdateRequest, ifMatch: kotlin.String?) : RequestConfig<MedicationUpdateRequest> {
        val localVariableBody = medicationUpdateRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        ifMatch?.apply { localVariableHeaders["If-Match"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/households/{household_id}/medications/{id}".replace("{"+"household_id"+"}", encodeURIComponent(householdId.toString())).replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
