/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.medtracker.client.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import io.medtracker.client.models.ErrorEnvelope
import io.medtracker.client.models.NotificationPreferenceResponse
import io.medtracker.client.models.NotificationPreferenceUpdateRequest
import io.medtracker.client.models.RateLimitErrorEnvelope

import com.squareup.moshi.Json

import io.medtracker.client.infrastructure.ApiClient
import io.medtracker.client.infrastructure.ApiResponse
import io.medtracker.client.infrastructure.ClientException
import io.medtracker.client.infrastructure.ClientError
import io.medtracker.client.infrastructure.ServerException
import io.medtracker.client.infrastructure.ServerError
import io.medtracker.client.infrastructure.MultiValueMap
import io.medtracker.client.infrastructure.PartConfig
import io.medtracker.client.infrastructure.RequestConfig
import io.medtracker.client.infrastructure.RequestMethod
import io.medtracker.client.infrastructure.ResponseType
import io.medtracker.client.infrastructure.Success
import io.medtracker.client.infrastructure.toMultiValue

open class NotificationPreferencesApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "/api/v1")
        }
    }

    /**
     * GET /households/{household_id}/notification_preference
     * Read the signed-in person&#39;s notification preference.
     * 
     * @param householdId 
     * @return NotificationPreferenceResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getNotificationPreference(householdId: kotlin.Int) : NotificationPreferenceResponse {
        val localVarResponse = getNotificationPreferenceWithHttpInfo(householdId = householdId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NotificationPreferenceResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /households/{household_id}/notification_preference
     * Read the signed-in person&#39;s notification preference.
     * 
     * @param householdId 
     * @return ApiResponse<NotificationPreferenceResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getNotificationPreferenceWithHttpInfo(householdId: kotlin.Int) : ApiResponse<NotificationPreferenceResponse?> {
        val localVariableConfig = getNotificationPreferenceRequestConfig(householdId = householdId)

        return request<Unit, NotificationPreferenceResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getNotificationPreference
     *
     * @param householdId 
     * @return RequestConfig
     */
    fun getNotificationPreferenceRequestConfig(householdId: kotlin.Int) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/households/{household_id}/notification_preference".replace("{"+"household_id"+"}", encodeURIComponent(householdId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /households/{household_id}/notification_preference
     * Replace the signed-in person&#39;s notification preference.
     * 
     * @param householdId 
     * @param notificationPreferenceUpdateRequest 
     * @return NotificationPreferenceResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun replaceNotificationPreference(householdId: kotlin.Int, notificationPreferenceUpdateRequest: NotificationPreferenceUpdateRequest) : NotificationPreferenceResponse {
        val localVarResponse = replaceNotificationPreferenceWithHttpInfo(householdId = householdId, notificationPreferenceUpdateRequest = notificationPreferenceUpdateRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NotificationPreferenceResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /households/{household_id}/notification_preference
     * Replace the signed-in person&#39;s notification preference.
     * 
     * @param householdId 
     * @param notificationPreferenceUpdateRequest 
     * @return ApiResponse<NotificationPreferenceResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun replaceNotificationPreferenceWithHttpInfo(householdId: kotlin.Int, notificationPreferenceUpdateRequest: NotificationPreferenceUpdateRequest) : ApiResponse<NotificationPreferenceResponse?> {
        val localVariableConfig = replaceNotificationPreferenceRequestConfig(householdId = householdId, notificationPreferenceUpdateRequest = notificationPreferenceUpdateRequest)

        return request<NotificationPreferenceUpdateRequest, NotificationPreferenceResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation replaceNotificationPreference
     *
     * @param householdId 
     * @param notificationPreferenceUpdateRequest 
     * @return RequestConfig
     */
    fun replaceNotificationPreferenceRequestConfig(householdId: kotlin.Int, notificationPreferenceUpdateRequest: NotificationPreferenceUpdateRequest) : RequestConfig<NotificationPreferenceUpdateRequest> {
        val localVariableBody = notificationPreferenceUpdateRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/households/{household_id}/notification_preference".replace("{"+"household_id"+"}", encodeURIComponent(householdId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PATCH /households/{household_id}/notification_preference
     * Update the signed-in person&#39;s notification preference.
     * 
     * @param householdId 
     * @param notificationPreferenceUpdateRequest 
     * @return NotificationPreferenceResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun updateNotificationPreference(householdId: kotlin.Int, notificationPreferenceUpdateRequest: NotificationPreferenceUpdateRequest) : NotificationPreferenceResponse {
        val localVarResponse = updateNotificationPreferenceWithHttpInfo(householdId = householdId, notificationPreferenceUpdateRequest = notificationPreferenceUpdateRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NotificationPreferenceResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PATCH /households/{household_id}/notification_preference
     * Update the signed-in person&#39;s notification preference.
     * 
     * @param householdId 
     * @param notificationPreferenceUpdateRequest 
     * @return ApiResponse<NotificationPreferenceResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun updateNotificationPreferenceWithHttpInfo(householdId: kotlin.Int, notificationPreferenceUpdateRequest: NotificationPreferenceUpdateRequest) : ApiResponse<NotificationPreferenceResponse?> {
        val localVariableConfig = updateNotificationPreferenceRequestConfig(householdId = householdId, notificationPreferenceUpdateRequest = notificationPreferenceUpdateRequest)

        return request<NotificationPreferenceUpdateRequest, NotificationPreferenceResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation updateNotificationPreference
     *
     * @param householdId 
     * @param notificationPreferenceUpdateRequest 
     * @return RequestConfig
     */
    fun updateNotificationPreferenceRequestConfig(householdId: kotlin.Int, notificationPreferenceUpdateRequest: NotificationPreferenceUpdateRequest) : RequestConfig<NotificationPreferenceUpdateRequest> {
        val localVariableBody = notificationPreferenceUpdateRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/households/{household_id}/notification_preference".replace("{"+"household_id"+"}", encodeURIComponent(householdId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
