/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.medtracker.client.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import io.medtracker.client.models.ErrorEnvelope
import io.medtracker.client.models.HouseholdProfileResponse
import io.medtracker.client.models.MeResponse
import io.medtracker.client.models.PersonCollectionResponse
import io.medtracker.client.models.PersonCreateRequest
import io.medtracker.client.models.PersonResponse
import io.medtracker.client.models.PersonUpdateRequest
import io.medtracker.client.models.RateLimitErrorEnvelope
import io.medtracker.client.models.UpdateHouseholdProfileWithPutRequest

import com.squareup.moshi.Json

import io.medtracker.client.infrastructure.ApiClient
import io.medtracker.client.infrastructure.ApiResponse
import io.medtracker.client.infrastructure.ClientException
import io.medtracker.client.infrastructure.ClientError
import io.medtracker.client.infrastructure.ServerException
import io.medtracker.client.infrastructure.ServerError
import io.medtracker.client.infrastructure.MultiValueMap
import io.medtracker.client.infrastructure.PartConfig
import io.medtracker.client.infrastructure.RequestConfig
import io.medtracker.client.infrastructure.RequestMethod
import io.medtracker.client.infrastructure.ResponseType
import io.medtracker.client.infrastructure.Success
import io.medtracker.client.infrastructure.toMultiValue

open class PeopleApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "/api/v1")
        }
    }

    /**
     * POST /households/{household_id}/people
     * Create a person in the household.
     * 
     * @param householdId 
     * @param personCreateRequest 
     * @return PersonResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun createPerson(householdId: kotlin.Int, personCreateRequest: PersonCreateRequest) : PersonResponse {
        val localVarResponse = createPersonWithHttpInfo(householdId = householdId, personCreateRequest = personCreateRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as PersonResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /households/{household_id}/people
     * Create a person in the household.
     * 
     * @param householdId 
     * @param personCreateRequest 
     * @return ApiResponse<PersonResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun createPersonWithHttpInfo(householdId: kotlin.Int, personCreateRequest: PersonCreateRequest) : ApiResponse<PersonResponse?> {
        val localVariableConfig = createPersonRequestConfig(householdId = householdId, personCreateRequest = personCreateRequest)

        return request<PersonCreateRequest, PersonResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createPerson
     *
     * @param householdId 
     * @param personCreateRequest 
     * @return RequestConfig
     */
    fun createPersonRequestConfig(householdId: kotlin.Int, personCreateRequest: PersonCreateRequest) : RequestConfig<PersonCreateRequest> {
        val localVariableBody = personCreateRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/households/{household_id}/people".replace("{"+"household_id"+"}", encodeURIComponent(householdId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /households/{household_id}/profile/avatar
     * Remove the current-person avatar.
     * Online only. Every request checks current person access. Multipart writes are not response-cached by Idempotency-Key.
     * @param householdId 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun deleteCurrentAvatar(householdId: kotlin.Int) : Unit {
        val localVarResponse = deleteCurrentAvatarWithHttpInfo(householdId = householdId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /households/{household_id}/profile/avatar
     * Remove the current-person avatar.
     * Online only. Every request checks current person access. Multipart writes are not response-cached by Idempotency-Key.
     * @param householdId 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun deleteCurrentAvatarWithHttpInfo(householdId: kotlin.Int) : ApiResponse<Unit?> {
        val localVariableConfig = deleteCurrentAvatarRequestConfig(householdId = householdId)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation deleteCurrentAvatar
     *
     * @param householdId 
     * @return RequestConfig
     */
    fun deleteCurrentAvatarRequestConfig(householdId: kotlin.Int) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/households/{household_id}/profile/avatar".replace("{"+"household_id"+"}", encodeURIComponent(householdId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /households/{household_id}/profile/avatar
     * Download the protected current-person avatar.
     * Online only. Every request checks current person access. Multipart writes are not response-cached by Idempotency-Key.
     * @param householdId 
     * @return java.io.File
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun downloadCurrentAvatar(householdId: kotlin.Int) : java.io.File {
        val localVarResponse = downloadCurrentAvatarWithHttpInfo(householdId = householdId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as java.io.File
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /households/{household_id}/profile/avatar
     * Download the protected current-person avatar.
     * Online only. Every request checks current person access. Multipart writes are not response-cached by Idempotency-Key.
     * @param householdId 
     * @return ApiResponse<java.io.File?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun downloadCurrentAvatarWithHttpInfo(householdId: kotlin.Int) : ApiResponse<java.io.File?> {
        val localVariableConfig = downloadCurrentAvatarRequestConfig(householdId = householdId)

        return request<Unit, java.io.File>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation downloadCurrentAvatar
     *
     * @param householdId 
     * @return RequestConfig
     */
    fun downloadCurrentAvatarRequestConfig(householdId: kotlin.Int) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/households/{household_id}/profile/avatar".replace("{"+"household_id"+"}", encodeURIComponent(householdId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /households/{household_id}/me
     * Read the current account and person profile for a household session.
     * 
     * @param householdId 
     * @return MeResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getCurrentProfile(householdId: kotlin.Int) : MeResponse {
        val localVarResponse = getCurrentProfileWithHttpInfo(householdId = householdId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MeResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /households/{household_id}/me
     * Read the current account and person profile for a household session.
     * 
     * @param householdId 
     * @return ApiResponse<MeResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getCurrentProfileWithHttpInfo(householdId: kotlin.Int) : ApiResponse<MeResponse?> {
        val localVariableConfig = getCurrentProfileRequestConfig(householdId = householdId)

        return request<Unit, MeResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getCurrentProfile
     *
     * @param householdId 
     * @return RequestConfig
     */
    fun getCurrentProfileRequestConfig(householdId: kotlin.Int) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/households/{household_id}/me".replace("{"+"household_id"+"}", encodeURIComponent(householdId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /households/{household_id}/profile
     * Read the current account preferences and household person profile.
     * 
     * @param householdId 
     * @return HouseholdProfileResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getHouseholdProfile(householdId: kotlin.Int) : HouseholdProfileResponse {
        val localVarResponse = getHouseholdProfileWithHttpInfo(householdId = householdId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as HouseholdProfileResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /households/{household_id}/profile
     * Read the current account preferences and household person profile.
     * 
     * @param householdId 
     * @return ApiResponse<HouseholdProfileResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getHouseholdProfileWithHttpInfo(householdId: kotlin.Int) : ApiResponse<HouseholdProfileResponse?> {
        val localVariableConfig = getHouseholdProfileRequestConfig(householdId = householdId)

        return request<Unit, HouseholdProfileResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getHouseholdProfile
     *
     * @param householdId 
     * @return RequestConfig
     */
    fun getHouseholdProfileRequestConfig(householdId: kotlin.Int) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/households/{household_id}/profile".replace("{"+"household_id"+"}", encodeURIComponent(householdId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /households/{household_id}/people/{id}
     * Read a person.
     * 
     * @param householdId 
     * @param id 
     * @return PersonResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getPerson(householdId: kotlin.Int, id: kotlin.Int) : PersonResponse {
        val localVarResponse = getPersonWithHttpInfo(householdId = householdId, id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as PersonResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /households/{household_id}/people/{id}
     * Read a person.
     * 
     * @param householdId 
     * @param id 
     * @return ApiResponse<PersonResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getPersonWithHttpInfo(householdId: kotlin.Int, id: kotlin.Int) : ApiResponse<PersonResponse?> {
        val localVariableConfig = getPersonRequestConfig(householdId = householdId, id = id)

        return request<Unit, PersonResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getPerson
     *
     * @param householdId 
     * @param id 
     * @return RequestConfig
     */
    fun getPersonRequestConfig(householdId: kotlin.Int, id: kotlin.Int) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/households/{household_id}/people/{id}".replace("{"+"household_id"+"}", encodeURIComponent(householdId.toString())).replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /households/{household_id}/people
     * List visible people in the household.
     * 
     * @param householdId 
     * @param page  (optional, default to 1)
     * @param perPage  (optional, default to 20)
     * @param updatedSince  (optional)
     * @return PersonCollectionResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun listPeople(householdId: kotlin.Int, page: kotlin.Int? = 1, perPage: kotlin.Int? = 20, updatedSince: java.time.OffsetDateTime? = null) : PersonCollectionResponse {
        val localVarResponse = listPeopleWithHttpInfo(householdId = householdId, page = page, perPage = perPage, updatedSince = updatedSince)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as PersonCollectionResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /households/{household_id}/people
     * List visible people in the household.
     * 
     * @param householdId 
     * @param page  (optional, default to 1)
     * @param perPage  (optional, default to 20)
     * @param updatedSince  (optional)
     * @return ApiResponse<PersonCollectionResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun listPeopleWithHttpInfo(householdId: kotlin.Int, page: kotlin.Int?, perPage: kotlin.Int?, updatedSince: java.time.OffsetDateTime?) : ApiResponse<PersonCollectionResponse?> {
        val localVariableConfig = listPeopleRequestConfig(householdId = householdId, page = page, perPage = perPage, updatedSince = updatedSince)

        return request<Unit, PersonCollectionResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listPeople
     *
     * @param householdId 
     * @param page  (optional, default to 1)
     * @param perPage  (optional, default to 20)
     * @param updatedSince  (optional)
     * @return RequestConfig
     */
    fun listPeopleRequestConfig(householdId: kotlin.Int, page: kotlin.Int?, perPage: kotlin.Int?, updatedSince: java.time.OffsetDateTime?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
                if (perPage != null) {
                    put("per_page", listOf(perPage.toString()))
                }
                if (updatedSince != null) {
                    put("updated_since", listOf(parseDateToQueryString(updatedSince)))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/households/{household_id}/people".replace("{"+"household_id"+"}", encodeURIComponent(householdId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PATCH /households/{household_id}/profile
     * Atomically save non-security preferences and date of birth online.
     * 
     * @param householdId 
     * @param updateHouseholdProfileWithPutRequest 
     * @return HouseholdProfileResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun updateHouseholdProfile(householdId: kotlin.Int, updateHouseholdProfileWithPutRequest: UpdateHouseholdProfileWithPutRequest) : HouseholdProfileResponse {
        val localVarResponse = updateHouseholdProfileWithHttpInfo(householdId = householdId, updateHouseholdProfileWithPutRequest = updateHouseholdProfileWithPutRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as HouseholdProfileResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PATCH /households/{household_id}/profile
     * Atomically save non-security preferences and date of birth online.
     * 
     * @param householdId 
     * @param updateHouseholdProfileWithPutRequest 
     * @return ApiResponse<HouseholdProfileResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun updateHouseholdProfileWithHttpInfo(householdId: kotlin.Int, updateHouseholdProfileWithPutRequest: UpdateHouseholdProfileWithPutRequest) : ApiResponse<HouseholdProfileResponse?> {
        val localVariableConfig = updateHouseholdProfileRequestConfig(householdId = householdId, updateHouseholdProfileWithPutRequest = updateHouseholdProfileWithPutRequest)

        return request<UpdateHouseholdProfileWithPutRequest, HouseholdProfileResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation updateHouseholdProfile
     *
     * @param householdId 
     * @param updateHouseholdProfileWithPutRequest 
     * @return RequestConfig
     */
    fun updateHouseholdProfileRequestConfig(householdId: kotlin.Int, updateHouseholdProfileWithPutRequest: UpdateHouseholdProfileWithPutRequest) : RequestConfig<UpdateHouseholdProfileWithPutRequest> {
        val localVariableBody = updateHouseholdProfileWithPutRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/households/{household_id}/profile".replace("{"+"household_id"+"}", encodeURIComponent(householdId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /households/{household_id}/profile
     * Atomically save non-security preferences and date of birth online.
     * 
     * @param householdId 
     * @param updateHouseholdProfileWithPutRequest 
     * @return HouseholdProfileResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun updateHouseholdProfileWithPut(householdId: kotlin.Int, updateHouseholdProfileWithPutRequest: UpdateHouseholdProfileWithPutRequest) : HouseholdProfileResponse {
        val localVarResponse = updateHouseholdProfileWithPutWithHttpInfo(householdId = householdId, updateHouseholdProfileWithPutRequest = updateHouseholdProfileWithPutRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as HouseholdProfileResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /households/{household_id}/profile
     * Atomically save non-security preferences and date of birth online.
     * 
     * @param householdId 
     * @param updateHouseholdProfileWithPutRequest 
     * @return ApiResponse<HouseholdProfileResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun updateHouseholdProfileWithPutWithHttpInfo(householdId: kotlin.Int, updateHouseholdProfileWithPutRequest: UpdateHouseholdProfileWithPutRequest) : ApiResponse<HouseholdProfileResponse?> {
        val localVariableConfig = updateHouseholdProfileWithPutRequestConfig(householdId = householdId, updateHouseholdProfileWithPutRequest = updateHouseholdProfileWithPutRequest)

        return request<UpdateHouseholdProfileWithPutRequest, HouseholdProfileResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation updateHouseholdProfileWithPut
     *
     * @param householdId 
     * @param updateHouseholdProfileWithPutRequest 
     * @return RequestConfig
     */
    fun updateHouseholdProfileWithPutRequestConfig(householdId: kotlin.Int, updateHouseholdProfileWithPutRequest: UpdateHouseholdProfileWithPutRequest) : RequestConfig<UpdateHouseholdProfileWithPutRequest> {
        val localVariableBody = updateHouseholdProfileWithPutRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/households/{household_id}/profile".replace("{"+"household_id"+"}", encodeURIComponent(householdId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PATCH /households/{household_id}/people/{id}
     * Update a person.
     * 
     * @param householdId 
     * @param id 
     * @param personUpdateRequest 
     * @return PersonResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun updatePerson(householdId: kotlin.Int, id: kotlin.Int, personUpdateRequest: PersonUpdateRequest) : PersonResponse {
        val localVarResponse = updatePersonWithHttpInfo(householdId = householdId, id = id, personUpdateRequest = personUpdateRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as PersonResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PATCH /households/{household_id}/people/{id}
     * Update a person.
     * 
     * @param householdId 
     * @param id 
     * @param personUpdateRequest 
     * @return ApiResponse<PersonResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun updatePersonWithHttpInfo(householdId: kotlin.Int, id: kotlin.Int, personUpdateRequest: PersonUpdateRequest) : ApiResponse<PersonResponse?> {
        val localVariableConfig = updatePersonRequestConfig(householdId = householdId, id = id, personUpdateRequest = personUpdateRequest)

        return request<PersonUpdateRequest, PersonResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation updatePerson
     *
     * @param householdId 
     * @param id 
     * @param personUpdateRequest 
     * @return RequestConfig
     */
    fun updatePersonRequestConfig(householdId: kotlin.Int, id: kotlin.Int, personUpdateRequest: PersonUpdateRequest) : RequestConfig<PersonUpdateRequest> {
        val localVariableBody = personUpdateRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/households/{household_id}/people/{id}".replace("{"+"household_id"+"}", encodeURIComponent(householdId.toString())).replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /households/{household_id}/people/{id}
     * Update a person using the PUT route.
     * 
     * @param householdId 
     * @param id 
     * @param personUpdateRequest 
     * @return PersonResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun updatePersonWithPut(householdId: kotlin.Int, id: kotlin.Int, personUpdateRequest: PersonUpdateRequest) : PersonResponse {
        val localVarResponse = updatePersonWithPutWithHttpInfo(householdId = householdId, id = id, personUpdateRequest = personUpdateRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as PersonResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /households/{household_id}/people/{id}
     * Update a person using the PUT route.
     * 
     * @param householdId 
     * @param id 
     * @param personUpdateRequest 
     * @return ApiResponse<PersonResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun updatePersonWithPutWithHttpInfo(householdId: kotlin.Int, id: kotlin.Int, personUpdateRequest: PersonUpdateRequest) : ApiResponse<PersonResponse?> {
        val localVariableConfig = updatePersonWithPutRequestConfig(householdId = householdId, id = id, personUpdateRequest = personUpdateRequest)

        return request<PersonUpdateRequest, PersonResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation updatePersonWithPut
     *
     * @param householdId 
     * @param id 
     * @param personUpdateRequest 
     * @return RequestConfig
     */
    fun updatePersonWithPutRequestConfig(householdId: kotlin.Int, id: kotlin.Int, personUpdateRequest: PersonUpdateRequest) : RequestConfig<PersonUpdateRequest> {
        val localVariableBody = personUpdateRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/households/{household_id}/people/{id}".replace("{"+"household_id"+"}", encodeURIComponent(householdId.toString())).replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /households/{household_id}/profile/avatar
     * Upload a PNG, JPEG or WebP image of at most 5 MiB.
     * Online only. Every request checks current person access. Multipart writes are not response-cached by Idempotency-Key.
     * @param householdId 
     * @param avatar 
     * @return HouseholdProfileResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun uploadCurrentAvatar(householdId: kotlin.Int, avatar: java.io.File) : HouseholdProfileResponse {
        val localVarResponse = uploadCurrentAvatarWithHttpInfo(householdId = householdId, avatar = avatar)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as HouseholdProfileResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /households/{household_id}/profile/avatar
     * Upload a PNG, JPEG or WebP image of at most 5 MiB.
     * Online only. Every request checks current person access. Multipart writes are not response-cached by Idempotency-Key.
     * @param householdId 
     * @param avatar 
     * @return ApiResponse<HouseholdProfileResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun uploadCurrentAvatarWithHttpInfo(householdId: kotlin.Int, avatar: java.io.File) : ApiResponse<HouseholdProfileResponse?> {
        val localVariableConfig = uploadCurrentAvatarRequestConfig(householdId = householdId, avatar = avatar)

        return request<Map<String, PartConfig<*>>, HouseholdProfileResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation uploadCurrentAvatar
     *
     * @param householdId 
     * @param avatar 
     * @return RequestConfig
     */
    fun uploadCurrentAvatarRequestConfig(householdId: kotlin.Int, avatar: java.io.File) : RequestConfig<Map<String, PartConfig<*>>> {
        val localVariableBody = mapOf(
            "avatar" to PartConfig(body = avatar, headers = mutableMapOf()),)
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf("Content-Type" to "multipart/form-data")
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/households/{household_id}/profile/avatar".replace("{"+"household_id"+"}", encodeURIComponent(householdId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
