test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

persistent:
  service: Disk
  root: <%= ENV.fetch("ACTIVE_STORAGE_ROOT", "/app/storage") %>

s3:
  service: S3
  endpoint: <%= ENV["ACTIVE_STORAGE_S3_ENDPOINT"] %>
  bucket: <%= ENV["ACTIVE_STORAGE_S3_BUCKET"] %>
  region: <%= ENV["ACTIVE_STORAGE_S3_REGION"] %>
  access_key_id: <%= ENV["ACTIVE_STORAGE_S3_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["ACTIVE_STORAGE_S3_SECRET_ACCESS_KEY"] %>
  force_path_style: <%= ENV.fetch("ACTIVE_STORAGE_S3_FORCE_PATH_STYLE", "true") == "true" %>

persistent_with_s3_mirror:
  service: Mirror
  primary: persistent
  mirrors: [ s3 ]

s3_with_persistent_mirror:
  service: Mirror
  primary: s3
  mirrors: [ persistent ]
