---
services:
  postgres:
    image: postgres:18-alpine
    ports:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-medtracker}"]
      interval: 10s
      timeout: 5s
      retries: 5

  rails:
    build:
      context: ..
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
