---
services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: medtracker
      POSTGRES_PASSWORD: medtracker_password
      POSTGRES_DB: medtracker
    ports:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  rails:
    build:
      context: ..
      dockerfile: Dockerfile
    entrypoint: ["/app/bin/docker-entrypoint-web"]
    ports:
      - "3000"
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/up || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 120s
