package io.medtracker.client.infrastructure

import com.squareup.moshi.Moshi
import com.squareup.moshi.adapters.EnumJsonAdapter

object SerializerHelper {
    fun addEnumUnknownDefaultCase(moshiBuilder: Moshi.Builder): Moshi.Builder {
        return moshiBuilder
            .add(io.medtracker.client.models.AdminWriteForbiddenError.Code::class.java, EnumJsonAdapter.create(io.medtracker.client.models.AdminWriteForbiddenError.Code::class.java)
                .withUnknownFallback(io.medtracker.client.models.AdminWriteForbiddenError.Code.unknown_default_open_api))
            .add(io.medtracker.client.models.AiMedicationDoseSuggestion.Unit::class.java, EnumJsonAdapter.create(io.medtracker.client.models.AiMedicationDoseSuggestion.Unit::class.java)
                .withUnknownFallback(io.medtracker.client.models.AiMedicationDoseSuggestion.Unit.unknown_default_open_api))
            .add(io.medtracker.client.models.AiMedicationDoseSuggestion.DefaultDoseCycle::class.java, EnumJsonAdapter.create(io.medtracker.client.models.AiMedicationDoseSuggestion.DefaultDoseCycle::class.java)
                .withUnknownFallback(io.medtracker.client.models.AiMedicationDoseSuggestion.DefaultDoseCycle.unknown_default_open_api))
            .add(io.medtracker.client.models.AuthHouseholdMembership.Role::class.java, EnumJsonAdapter.create(io.medtracker.client.models.AuthHouseholdMembership.Role::class.java)
                .withUnknownFallback(io.medtracker.client.models.AuthHouseholdMembership.Role.unknown_default_open_api))
            .add(io.medtracker.client.models.BackupZipResponseData.ContentType::class.java, EnumJsonAdapter.create(io.medtracker.client.models.BackupZipResponseData.ContentType::class.java)
                .withUnknownFallback(io.medtracker.client.models.BackupZipResponseData.ContentType.unknown_default_open_api))
            .add(io.medtracker.client.models.Capabilities.Format::class.java, EnumJsonAdapter.create(io.medtracker.client.models.Capabilities.Format::class.java)
                .withUnknownFallback(io.medtracker.client.models.Capabilities.Format.unknown_default_open_api))
            .add(io.medtracker.client.models.Capabilities.ApiVersion::class.java, EnumJsonAdapter.create(io.medtracker.client.models.Capabilities.ApiVersion::class.java)
                .withUnknownFallback(io.medtracker.client.models.Capabilities.ApiVersion.unknown_default_open_api))
            .add(io.medtracker.client.models.Capabilities.PortableFormats::class.java, EnumJsonAdapter.create(io.medtracker.client.models.Capabilities.PortableFormats::class.java)
                .withUnknownFallback(io.medtracker.client.models.Capabilities.PortableFormats.unknown_default_open_api))
            .add(io.medtracker.client.models.CapabilityAuthentication.Methods::class.java, EnumJsonAdapter.create(io.medtracker.client.models.CapabilityAuthentication.Methods::class.java)
                .withUnknownFallback(io.medtracker.client.models.CapabilityAuthentication.Methods.unknown_default_open_api))
            .add(io.medtracker.client.models.CapabilityAuthentication.HostedMobile::class.java, EnumJsonAdapter.create(io.medtracker.client.models.CapabilityAuthentication.HostedMobile::class.java)
                .withUnknownFallback(io.medtracker.client.models.CapabilityAuthentication.HostedMobile.unknown_default_open_api))
            .add(io.medtracker.client.models.CapabilityAuthentication.PasswordLogin::class.java, EnumJsonAdapter.create(io.medtracker.client.models.CapabilityAuthentication.PasswordLogin::class.java)
                .withUnknownFallback(io.medtracker.client.models.CapabilityAuthentication.PasswordLogin.unknown_default_open_api))
            .add(io.medtracker.client.models.CapabilityCli.Status::class.java, EnumJsonAdapter.create(io.medtracker.client.models.CapabilityCli.Status::class.java)
                .withUnknownFallback(io.medtracker.client.models.CapabilityCli.Status.unknown_default_open_api))
            .add(io.medtracker.client.models.CapabilityCli.Binary::class.java, EnumJsonAdapter.create(io.medtracker.client.models.CapabilityCli.Binary::class.java)
                .withUnknownFallback(io.medtracker.client.models.CapabilityCli.Binary.unknown_default_open_api))
            .add(io.medtracker.client.models.CapabilityCli.ApiBoundary::class.java, EnumJsonAdapter.create(io.medtracker.client.models.CapabilityCli.ApiBoundary::class.java)
                .withUnknownFallback(io.medtracker.client.models.CapabilityCli.ApiBoundary.unknown_default_open_api))
            .add(io.medtracker.client.models.CapabilityCli.Distribution::class.java, EnumJsonAdapter.create(io.medtracker.client.models.CapabilityCli.Distribution::class.java)
                .withUnknownFallback(io.medtracker.client.models.CapabilityCli.Distribution.unknown_default_open_api))
            .add(io.medtracker.client.models.CapabilityClientTools.Diagnostics::class.java, EnumJsonAdapter.create(io.medtracker.client.models.CapabilityClientTools.Diagnostics::class.java)
                .withUnknownFallback(io.medtracker.client.models.CapabilityClientTools.Diagnostics.unknown_default_open_api))
            .add(io.medtracker.client.models.CapabilityFhir.Version::class.java, EnumJsonAdapter.create(io.medtracker.client.models.CapabilityFhir.Version::class.java)
                .withUnknownFallback(io.medtracker.client.models.CapabilityFhir.Version.unknown_default_open_api))
            .add(io.medtracker.client.models.CapabilityFhir.Resources::class.java, EnumJsonAdapter.create(io.medtracker.client.models.CapabilityFhir.Resources::class.java)
                .withUnknownFallback(io.medtracker.client.models.CapabilityFhir.Resources.unknown_default_open_api))
            .add(io.medtracker.client.models.CapabilityMcpServer.Transport::class.java, EnumJsonAdapter.create(io.medtracker.client.models.CapabilityMcpServer.Transport::class.java)
                .withUnknownFallback(io.medtracker.client.models.CapabilityMcpServer.Transport.unknown_default_open_api))
            .add(io.medtracker.client.models.CapabilityMcpServer.Endpoint::class.java, EnumJsonAdapter.create(io.medtracker.client.models.CapabilityMcpServer.Endpoint::class.java)
                .withUnknownFallback(io.medtracker.client.models.CapabilityMcpServer.Endpoint.unknown_default_open_api))
            .add(io.medtracker.client.models.CapabilityMcpServer.StdioBinary::class.java, EnumJsonAdapter.create(io.medtracker.client.models.CapabilityMcpServer.StdioBinary::class.java)
                .withUnknownFallback(io.medtracker.client.models.CapabilityMcpServer.StdioBinary.unknown_default_open_api))
            .add(io.medtracker.client.models.CapabilitySync.NumericIds::class.java, EnumJsonAdapter.create(io.medtracker.client.models.CapabilitySync.NumericIds::class.java)
                .withUnknownFallback(io.medtracker.client.models.CapabilitySync.NumericIds.unknown_default_open_api))
            .add(io.medtracker.client.models.DataExportResponseData.Format::class.java, EnumJsonAdapter.create(io.medtracker.client.models.DataExportResponseData.Format::class.java)
                .withUnknownFallback(io.medtracker.client.models.DataExportResponseData.Format.unknown_default_open_api))
            .add(io.medtracker.client.models.DataExportResponseData.Scope::class.java, EnumJsonAdapter.create(io.medtracker.client.models.DataExportResponseData.Scope::class.java)
                .withUnknownFallback(io.medtracker.client.models.DataExportResponseData.Scope.unknown_default_open_api))
            .add(io.medtracker.client.models.DataExportResponseData.Cipher::class.java, EnumJsonAdapter.create(io.medtracker.client.models.DataExportResponseData.Cipher::class.java)
                .withUnknownFallback(io.medtracker.client.models.DataExportResponseData.Cipher.unknown_default_open_api))
            .add(io.medtracker.client.models.DataExportResponseData.Kdf::class.java, EnumJsonAdapter.create(io.medtracker.client.models.DataExportResponseData.Kdf::class.java)
                .withUnknownFallback(io.medtracker.client.models.DataExportResponseData.Kdf.unknown_default_open_api))
            .add(io.medtracker.client.models.DataExportResponseData.ContentType::class.java, EnumJsonAdapter.create(io.medtracker.client.models.DataExportResponseData.ContentType::class.java)
                .withUnknownFallback(io.medtracker.client.models.DataExportResponseData.ContentType.unknown_default_open_api))
            .add(io.medtracker.client.models.DosageOption.DefaultDoseCycle::class.java, EnumJsonAdapter.create(io.medtracker.client.models.DosageOption.DefaultDoseCycle::class.java)
                .withUnknownFallback(io.medtracker.client.models.DosageOption.DefaultDoseCycle.unknown_default_open_api))
            .add(io.medtracker.client.models.DosageOptionCreateAttributes.DefaultDoseCycle::class.java, EnumJsonAdapter.create(io.medtracker.client.models.DosageOptionCreateAttributes.DefaultDoseCycle::class.java)
                .withUnknownFallback(io.medtracker.client.models.DosageOptionCreateAttributes.DefaultDoseCycle.unknown_default_open_api))
            .add(io.medtracker.client.models.DosageOptionUpdateAttributes.DefaultDoseCycle::class.java, EnumJsonAdapter.create(io.medtracker.client.models.DosageOptionUpdateAttributes.DefaultDoseCycle::class.java)
                .withUnknownFallback(io.medtracker.client.models.DosageOptionUpdateAttributes.DefaultDoseCycle.unknown_default_open_api))
            .add(io.medtracker.client.models.HealthDataExportResponseData.Format::class.java, EnumJsonAdapter.create(io.medtracker.client.models.HealthDataExportResponseData.Format::class.java)
                .withUnknownFallback(io.medtracker.client.models.HealthDataExportResponseData.Format.unknown_default_open_api))
            .add(io.medtracker.client.models.HealthDataExportResponseData.Scope::class.java, EnumJsonAdapter.create(io.medtracker.client.models.HealthDataExportResponseData.Scope::class.java)
                .withUnknownFallback(io.medtracker.client.models.HealthDataExportResponseData.Scope.unknown_default_open_api))
            .add(io.medtracker.client.models.HealthEvent.EventKind::class.java, EnumJsonAdapter.create(io.medtracker.client.models.HealthEvent.EventKind::class.java)
                .withUnknownFallback(io.medtracker.client.models.HealthEvent.EventKind.unknown_default_open_api))
            .add(io.medtracker.client.models.HealthEvent.Severity::class.java, EnumJsonAdapter.create(io.medtracker.client.models.HealthEvent.Severity::class.java)
                .withUnknownFallback(io.medtracker.client.models.HealthEvent.Severity.unknown_default_open_api))
            .add(io.medtracker.client.models.HealthEventAttributes.EventKind::class.java, EnumJsonAdapter.create(io.medtracker.client.models.HealthEventAttributes.EventKind::class.java)
                .withUnknownFallback(io.medtracker.client.models.HealthEventAttributes.EventKind.unknown_default_open_api))
            .add(io.medtracker.client.models.HealthEventAttributes.Severity::class.java, EnumJsonAdapter.create(io.medtracker.client.models.HealthEventAttributes.Severity::class.java)
                .withUnknownFallback(io.medtracker.client.models.HealthEventAttributes.Severity.unknown_default_open_api))
            .add(io.medtracker.client.models.HealthEventCreateRequestHealthEvent.EventKind::class.java, EnumJsonAdapter.create(io.medtracker.client.models.HealthEventCreateRequestHealthEvent.EventKind::class.java)
                .withUnknownFallback(io.medtracker.client.models.HealthEventCreateRequestHealthEvent.EventKind.unknown_default_open_api))
            .add(io.medtracker.client.models.HealthEventCreateRequestHealthEvent.Severity::class.java, EnumJsonAdapter.create(io.medtracker.client.models.HealthEventCreateRequestHealthEvent.Severity::class.java)
                .withUnknownFallback(io.medtracker.client.models.HealthEventCreateRequestHealthEvent.Severity.unknown_default_open_api))
            .add(io.medtracker.client.models.HouseholdAdminSettings.SubscriptionPlan::class.java, EnumJsonAdapter.create(io.medtracker.client.models.HouseholdAdminSettings.SubscriptionPlan::class.java)
                .withUnknownFallback(io.medtracker.client.models.HouseholdAdminSettings.SubscriptionPlan.unknown_default_open_api))
            .add(io.medtracker.client.models.HouseholdAdminSettingsAttributes.SubscriptionPlan::class.java, EnumJsonAdapter.create(io.medtracker.client.models.HouseholdAdminSettingsAttributes.SubscriptionPlan::class.java)
                .withUnknownFallback(io.medtracker.client.models.HouseholdAdminSettingsAttributes.SubscriptionPlan.unknown_default_open_api))
            .add(io.medtracker.client.models.HouseholdInvitation.MembershipRole::class.java, EnumJsonAdapter.create(io.medtracker.client.models.HouseholdInvitation.MembershipRole::class.java)
                .withUnknownFallback(io.medtracker.client.models.HouseholdInvitation.MembershipRole.unknown_default_open_api))
            .add(io.medtracker.client.models.HouseholdInvitationAttributes.MembershipRole::class.java, EnumJsonAdapter.create(io.medtracker.client.models.HouseholdInvitationAttributes.MembershipRole::class.java)
                .withUnknownFallback(io.medtracker.client.models.HouseholdInvitationAttributes.MembershipRole.unknown_default_open_api))
            .add(io.medtracker.client.models.HouseholdMembership.Role::class.java, EnumJsonAdapter.create(io.medtracker.client.models.HouseholdMembership.Role::class.java)
                .withUnknownFallback(io.medtracker.client.models.HouseholdMembership.Role.unknown_default_open_api))
            .add(io.medtracker.client.models.HouseholdMembership.Status::class.java, EnumJsonAdapter.create(io.medtracker.client.models.HouseholdMembership.Status::class.java)
                .withUnknownFallback(io.medtracker.client.models.HouseholdMembership.Status.unknown_default_open_api))
            .add(io.medtracker.client.models.HouseholdMembershipAttributes.Role::class.java, EnumJsonAdapter.create(io.medtracker.client.models.HouseholdMembershipAttributes.Role::class.java)
                .withUnknownFallback(io.medtracker.client.models.HouseholdMembershipAttributes.Role.unknown_default_open_api))
            .add(io.medtracker.client.models.HouseholdMembershipAttributes.Status::class.java, EnumJsonAdapter.create(io.medtracker.client.models.HouseholdMembershipAttributes.Status::class.java)
                .withUnknownFallback(io.medtracker.client.models.HouseholdMembershipAttributes.Status.unknown_default_open_api))
            .add(io.medtracker.client.models.Me.MembershipRole::class.java, EnumJsonAdapter.create(io.medtracker.client.models.Me.MembershipRole::class.java)
                .withUnknownFallback(io.medtracker.client.models.Me.MembershipRole.unknown_default_open_api))
            .add(io.medtracker.client.models.MeAccount.Status::class.java, EnumJsonAdapter.create(io.medtracker.client.models.MeAccount.Status::class.java)
                .withUnknownFallback(io.medtracker.client.models.MeAccount.Status.unknown_default_open_api))
            .add(io.medtracker.client.models.Medication.ReorderStatus::class.java, EnumJsonAdapter.create(io.medtracker.client.models.Medication.ReorderStatus::class.java)
                .withUnknownFallback(io.medtracker.client.models.Medication.ReorderStatus.unknown_default_open_api))
            .add(io.medtracker.client.models.MedicationCreateAttributes.DoseUnit::class.java, EnumJsonAdapter.create(io.medtracker.client.models.MedicationCreateAttributes.DoseUnit::class.java)
                .withUnknownFallback(io.medtracker.client.models.MedicationCreateAttributes.DoseUnit.unknown_default_open_api))
            .add(io.medtracker.client.models.MedicationCreateAttributes.DefaultScheduleType::class.java, EnumJsonAdapter.create(io.medtracker.client.models.MedicationCreateAttributes.DefaultScheduleType::class.java)
                .withUnknownFallback(io.medtracker.client.models.MedicationCreateAttributes.DefaultScheduleType.unknown_default_open_api))
            .add(io.medtracker.client.models.MedicationLookupBarcodeResolution.Status::class.java, EnumJsonAdapter.create(io.medtracker.client.models.MedicationLookupBarcodeResolution.Status::class.java)
                .withUnknownFallback(io.medtracker.client.models.MedicationLookupBarcodeResolution.Status.unknown_default_open_api))
            .add(io.medtracker.client.models.MedicationLookupReviewGuidance.Status::class.java, EnumJsonAdapter.create(io.medtracker.client.models.MedicationLookupReviewGuidance.Status::class.java)
                .withUnknownFallback(io.medtracker.client.models.MedicationLookupReviewGuidance.Status.unknown_default_open_api))
            .add(io.medtracker.client.models.MedicationLookupReviewPrompt.RiskLevel::class.java, EnumJsonAdapter.create(io.medtracker.client.models.MedicationLookupReviewPrompt.RiskLevel::class.java)
                .withUnknownFallback(io.medtracker.client.models.MedicationLookupReviewPrompt.RiskLevel.unknown_default_open_api))
            .add(io.medtracker.client.models.MedicationLookupReviewPrompt.MatchConfidence::class.java, EnumJsonAdapter.create(io.medtracker.client.models.MedicationLookupReviewPrompt.MatchConfidence::class.java)
                .withUnknownFallback(io.medtracker.client.models.MedicationLookupReviewPrompt.MatchConfidence.unknown_default_open_api))
            .add(io.medtracker.client.models.MedicationLookupReviewPrompt.MatchType::class.java, EnumJsonAdapter.create(io.medtracker.client.models.MedicationLookupReviewPrompt.MatchType::class.java)
                .withUnknownFallback(io.medtracker.client.models.MedicationLookupReviewPrompt.MatchType.unknown_default_open_api))
            .add(io.medtracker.client.models.MedicationLookupUnavailableError::class.java, EnumJsonAdapter.create(io.medtracker.client.models.MedicationLookupUnavailableError::class.java)
                .withUnknownFallback(io.medtracker.client.models.MedicationLookupUnavailableError.unknown_default_open_api))
            .add(io.medtracker.client.models.MedicationTakeCreateRequestMedicationTake.SourceType::class.java, EnumJsonAdapter.create(io.medtracker.client.models.MedicationTakeCreateRequestMedicationTake.SourceType::class.java)
                .withUnknownFallback(io.medtracker.client.models.MedicationTakeCreateRequestMedicationTake.SourceType.unknown_default_open_api))
            .add(io.medtracker.client.models.MedicationUpdateAttributes.DoseUnit::class.java, EnumJsonAdapter.create(io.medtracker.client.models.MedicationUpdateAttributes.DoseUnit::class.java)
                .withUnknownFallback(io.medtracker.client.models.MedicationUpdateAttributes.DoseUnit.unknown_default_open_api))
            .add(io.medtracker.client.models.MedicationUpdateAttributes.DefaultScheduleType::class.java, EnumJsonAdapter.create(io.medtracker.client.models.MedicationUpdateAttributes.DefaultScheduleType::class.java)
                .withUnknownFallback(io.medtracker.client.models.MedicationUpdateAttributes.DefaultScheduleType.unknown_default_open_api))
            .add(io.medtracker.client.models.NativeDeviceTokenAttributes.Platform::class.java, EnumJsonAdapter.create(io.medtracker.client.models.NativeDeviceTokenAttributes.Platform::class.java)
                .withUnknownFallback(io.medtracker.client.models.NativeDeviceTokenAttributes.Platform.unknown_default_open_api))
            .add(io.medtracker.client.models.Person.PersonType::class.java, EnumJsonAdapter.create(io.medtracker.client.models.Person.PersonType::class.java)
                .withUnknownFallback(io.medtracker.client.models.Person.PersonType.unknown_default_open_api))
            .add(io.medtracker.client.models.PersonAccessGrant.AccessLevel::class.java, EnumJsonAdapter.create(io.medtracker.client.models.PersonAccessGrant.AccessLevel::class.java)
                .withUnknownFallback(io.medtracker.client.models.PersonAccessGrant.AccessLevel.unknown_default_open_api))
            .add(io.medtracker.client.models.PersonAccessGrant.RelationshipType::class.java, EnumJsonAdapter.create(io.medtracker.client.models.PersonAccessGrant.RelationshipType::class.java)
                .withUnknownFallback(io.medtracker.client.models.PersonAccessGrant.RelationshipType.unknown_default_open_api))
            .add(io.medtracker.client.models.PersonAccessGrantAttributes.AccessLevel::class.java, EnumJsonAdapter.create(io.medtracker.client.models.PersonAccessGrantAttributes.AccessLevel::class.java)
                .withUnknownFallback(io.medtracker.client.models.PersonAccessGrantAttributes.AccessLevel.unknown_default_open_api))
            .add(io.medtracker.client.models.PersonAccessGrantAttributes.RelationshipType::class.java, EnumJsonAdapter.create(io.medtracker.client.models.PersonAccessGrantAttributes.RelationshipType::class.java)
                .withUnknownFallback(io.medtracker.client.models.PersonAccessGrantAttributes.RelationshipType.unknown_default_open_api))
            .add(io.medtracker.client.models.PersonAttributes.PersonType::class.java, EnumJsonAdapter.create(io.medtracker.client.models.PersonAttributes.PersonType::class.java)
                .withUnknownFallback(io.medtracker.client.models.PersonAttributes.PersonType.unknown_default_open_api))
            .add(io.medtracker.client.models.PersonCreateRequestPerson.PersonType::class.java, EnumJsonAdapter.create(io.medtracker.client.models.PersonCreateRequestPerson.PersonType::class.java)
                .withUnknownFallback(io.medtracker.client.models.PersonCreateRequestPerson.PersonType.unknown_default_open_api))
            .add(io.medtracker.client.models.PersonMedication.DoseCycle::class.java, EnumJsonAdapter.create(io.medtracker.client.models.PersonMedication.DoseCycle::class.java)
                .withUnknownFallback(io.medtracker.client.models.PersonMedication.DoseCycle.unknown_default_open_api))
            .add(io.medtracker.client.models.PersonMedication.AdministrationKind::class.java, EnumJsonAdapter.create(io.medtracker.client.models.PersonMedication.AdministrationKind::class.java)
                .withUnknownFallback(io.medtracker.client.models.PersonMedication.AdministrationKind.unknown_default_open_api))
            .add(io.medtracker.client.models.PersonMedicationAttributes.AdministrationKind::class.java, EnumJsonAdapter.create(io.medtracker.client.models.PersonMedicationAttributes.AdministrationKind::class.java)
                .withUnknownFallback(io.medtracker.client.models.PersonMedicationAttributes.AdministrationKind.unknown_default_open_api))
            .add(io.medtracker.client.models.PersonMedicationAttributes.DoseCycle::class.java, EnumJsonAdapter.create(io.medtracker.client.models.PersonMedicationAttributes.DoseCycle::class.java)
                .withUnknownFallback(io.medtracker.client.models.PersonMedicationAttributes.DoseCycle.unknown_default_open_api))
            .add(io.medtracker.client.models.PersonMedicationCreateRequestPersonMedication.AdministrationKind::class.java, EnumJsonAdapter.create(io.medtracker.client.models.PersonMedicationCreateRequestPersonMedication.AdministrationKind::class.java)
                .withUnknownFallback(io.medtracker.client.models.PersonMedicationCreateRequestPersonMedication.AdministrationKind.unknown_default_open_api))
            .add(io.medtracker.client.models.PersonMedicationCreateRequestPersonMedication.DoseCycle::class.java, EnumJsonAdapter.create(io.medtracker.client.models.PersonMedicationCreateRequestPersonMedication.DoseCycle::class.java)
                .withUnknownFallback(io.medtracker.client.models.PersonMedicationCreateRequestPersonMedication.DoseCycle.unknown_default_open_api))
            .add(io.medtracker.client.models.PersonMedicationReorderRequest.Direction::class.java, EnumJsonAdapter.create(io.medtracker.client.models.PersonMedicationReorderRequest.Direction::class.java)
                .withUnknownFallback(io.medtracker.client.models.PersonMedicationReorderRequest.Direction.unknown_default_open_api))
            .add(io.medtracker.client.models.PortableEnvelope.Format::class.java, EnumJsonAdapter.create(io.medtracker.client.models.PortableEnvelope.Format::class.java)
                .withUnknownFallback(io.medtracker.client.models.PortableEnvelope.Format.unknown_default_open_api))
            .add(io.medtracker.client.models.PortableEnvelope.Cipher::class.java, EnumJsonAdapter.create(io.medtracker.client.models.PortableEnvelope.Cipher::class.java)
                .withUnknownFallback(io.medtracker.client.models.PortableEnvelope.Cipher.unknown_default_open_api))
            .add(io.medtracker.client.models.PortableEnvelope.Kdf::class.java, EnumJsonAdapter.create(io.medtracker.client.models.PortableEnvelope.Kdf::class.java)
                .withUnknownFallback(io.medtracker.client.models.PortableEnvelope.Kdf.unknown_default_open_api))
            .add(io.medtracker.client.models.PortableImportConflict.RecordType::class.java, EnumJsonAdapter.create(io.medtracker.client.models.PortableImportConflict.RecordType::class.java)
                .withUnknownFallback(io.medtracker.client.models.PortableImportConflict.RecordType.unknown_default_open_api))
            .add(io.medtracker.client.models.PortableImportConflictField::class.java, EnumJsonAdapter.create(io.medtracker.client.models.PortableImportConflictField::class.java)
                .withUnknownFallback(io.medtracker.client.models.PortableImportConflictField.unknown_default_open_api))
            .add(io.medtracker.client.models.PortableSnapshot.Format::class.java, EnumJsonAdapter.create(io.medtracker.client.models.PortableSnapshot.Format::class.java)
                .withUnknownFallback(io.medtracker.client.models.PortableSnapshot.Format.unknown_default_open_api))
            .add(io.medtracker.client.models.PortableSnapshot.Scope::class.java, EnumJsonAdapter.create(io.medtracker.client.models.PortableSnapshot.Scope::class.java)
                .withUnknownFallback(io.medtracker.client.models.PortableSnapshot.Scope.unknown_default_open_api))
            .add(io.medtracker.client.models.PushTestFailedError.Code::class.java, EnumJsonAdapter.create(io.medtracker.client.models.PushTestFailedError.Code::class.java)
                .withUnknownFallback(io.medtracker.client.models.PushTestFailedError.Code.unknown_default_open_api))
            .add(io.medtracker.client.models.PushTestFailedError.Message::class.java, EnumJsonAdapter.create(io.medtracker.client.models.PushTestFailedError.Message::class.java)
                .withUnknownFallback(io.medtracker.client.models.PushTestFailedError.Message.unknown_default_open_api))
            .add(io.medtracker.client.models.RateLimitError.Code::class.java, EnumJsonAdapter.create(io.medtracker.client.models.RateLimitError.Code::class.java)
                .withUnknownFallback(io.medtracker.client.models.RateLimitError.Code.unknown_default_open_api))
            .add(io.medtracker.client.models.Schedule.DoseCycle::class.java, EnumJsonAdapter.create(io.medtracker.client.models.Schedule.DoseCycle::class.java)
                .withUnknownFallback(io.medtracker.client.models.Schedule.DoseCycle.unknown_default_open_api))
            .add(io.medtracker.client.models.ScheduleAttributes.DoseCycle::class.java, EnumJsonAdapter.create(io.medtracker.client.models.ScheduleAttributes.DoseCycle::class.java)
                .withUnknownFallback(io.medtracker.client.models.ScheduleAttributes.DoseCycle.unknown_default_open_api))
            .add(io.medtracker.client.models.ScheduleAttributes.ScheduleType::class.java, EnumJsonAdapter.create(io.medtracker.client.models.ScheduleAttributes.ScheduleType::class.java)
                .withUnknownFallback(io.medtracker.client.models.ScheduleAttributes.ScheduleType.unknown_default_open_api))
            .add(io.medtracker.client.models.ScheduleCreateRequestSchedule.DoseCycle::class.java, EnumJsonAdapter.create(io.medtracker.client.models.ScheduleCreateRequestSchedule.DoseCycle::class.java)
                .withUnknownFallback(io.medtracker.client.models.ScheduleCreateRequestSchedule.DoseCycle.unknown_default_open_api))
            .add(io.medtracker.client.models.ScheduleCreateRequestSchedule.ScheduleType::class.java, EnumJsonAdapter.create(io.medtracker.client.models.ScheduleCreateRequestSchedule.ScheduleType::class.java)
                .withUnknownFallback(io.medtracker.client.models.ScheduleCreateRequestSchedule.ScheduleType.unknown_default_open_api))
            .add(io.medtracker.client.models.SyncBatchOperation.Action::class.java, EnumJsonAdapter.create(io.medtracker.client.models.SyncBatchOperation.Action::class.java)
                .withUnknownFallback(io.medtracker.client.models.SyncBatchOperation.Action.unknown_default_open_api))
            .add(io.medtracker.client.models.SyncBatchOperation.ResourceType::class.java, EnumJsonAdapter.create(io.medtracker.client.models.SyncBatchOperation.ResourceType::class.java)
                .withUnknownFallback(io.medtracker.client.models.SyncBatchOperation.ResourceType.unknown_default_open_api))
            .add(io.medtracker.client.models.SyncBatchResult.Action::class.java, EnumJsonAdapter.create(io.medtracker.client.models.SyncBatchResult.Action::class.java)
                .withUnknownFallback(io.medtracker.client.models.SyncBatchResult.Action.unknown_default_open_api))
            .add(io.medtracker.client.models.SyncBatchResult.RecordType::class.java, EnumJsonAdapter.create(io.medtracker.client.models.SyncBatchResult.RecordType::class.java)
                .withUnknownFallback(io.medtracker.client.models.SyncBatchResult.RecordType.unknown_default_open_api))
            .add(io.medtracker.client.models.SyncChange.Action::class.java, EnumJsonAdapter.create(io.medtracker.client.models.SyncChange.Action::class.java)
                .withUnknownFallback(io.medtracker.client.models.SyncChange.Action.unknown_default_open_api))
            .add(io.medtracker.client.models.SyncSnapshot.Format::class.java, EnumJsonAdapter.create(io.medtracker.client.models.SyncSnapshot.Format::class.java)
                .withUnknownFallback(io.medtracker.client.models.SyncSnapshot.Format.unknown_default_open_api))
            .add(io.medtracker.client.models.SyncSnapshot.Scope::class.java, EnumJsonAdapter.create(io.medtracker.client.models.SyncSnapshot.Scope::class.java)
                .withUnknownFallback(io.medtracker.client.models.SyncSnapshot.Scope.unknown_default_open_api))
            .add(io.medtracker.client.models.SyncTombstone.Action::class.java, EnumJsonAdapter.create(io.medtracker.client.models.SyncTombstone.Action::class.java)
                .withUnknownFallback(io.medtracker.client.models.SyncTombstone.Action.unknown_default_open_api))
    }
}
