use crate::api_request_guards::{cookie_api_csrf, private_api_cache};
use crate::{
    admin_settings, app_tokens, audit_logs, auth_sessions, dosage_options, dose, dose_occurrences,
    external_integrations, health_events, invitations, locations, medication_management,
    medication_reads, memberships, native_device_tokens, notification_preferences, oauth,
    pause_lifecycle, people, person_grants, person_medication_writes, portable_exports,
    portable_imports, profile, push_subscriptions, read_resources, reports, review_prompts,
    schedule_writes, stock_removals, sync_batch, sync_reads, ui_capabilities, AppState,
};
use axum::{middleware, routing::get, Router};

pub(super) fn api_router(state: AppState) -> Router {
    let csrf_state = state.clone();
    Router::new()
        .route(
            "/api/v1/households/{household_id}/ui_capabilities",
            get(ui_capabilities::show),
        )
        .merge(oauth::api_routes())
        .merge(auth_sessions::routes())
        .merge(health_events::routes())
        .merge(profile::routes())
        .merge(reports::routes())
        .merge(portable_imports::routes())
        .merge(sync_batch::routes())
        .route(
            "/api/v1/households/{household_id}/portable_export",
            get(portable_exports::portable_export),
        )
        .route(
            "/api/v1/households/{household_id}/mobile_snapshot",
            get(portable_exports::mobile_snapshot),
        )
        .route(
            "/api/v1/households/{household_id}/data_exports/{mode}",
            get(portable_exports::data_export),
        )
        .route(
            "/api/v1/households/{household_id}/sync/snapshot",
            get(sync_reads::snapshot),
        )
        .route(
            "/api/v1/households/{household_id}/sync/changes",
            get(sync_reads::changes),
        )
        .route(
            "/api/v1/households/{household_id}/medication_lookup",
            get(external_integrations::medication_lookup),
        )
        .route(
            "/api/v1/households/{household_id}/ai_medication_suggestions",
            axum::routing::post(external_integrations::ai_medication_suggestions),
        )
        .route(
            "/api/v1/households/{household_id}/push_subscription/test",
            axum::routing::post(external_integrations::test_push_subscription),
        )
        .route(
            "/api/v1/households/{household_id}/medications",
            get(medication_reads::index).post(medication_management::create),
        )
        .route(
            "/api/v1/households/{household_id}/medication_takes",
            get(dose::index).post(dose::create),
        )
        .route(
            "/api/v1/households/{household_id}/medications/{id}",
            get(medication_reads::show)
                .patch(medication_management::patch)
                .put(medication_management::put),
        )
        .route(
            "/api/v1/households/{household_id}/dosage_options",
            get(dosage_options::index).post(dosage_options::create),
        )
        .route(
            "/api/v1/households/{household_id}/dosage_options/{id}",
            get(dosage_options::show)
                .patch(dosage_options::patch)
                .put(dosage_options::put),
        )
        .route(
            "/api/v1/households/{household_id}/medications/{id}/adjust_inventory",
            axum::routing::patch(medication_management::adjust_inventory),
        )
        .route(
            "/api/v1/households/{household_id}/medications/{id}/mark_as_ordered",
            axum::routing::patch(medication_management::mark_as_ordered),
        )
        .route(
            "/api/v1/households/{household_id}/medications/{id}/mark_as_received",
            axum::routing::patch(medication_management::mark_as_received),
        )
        .route(
            "/api/v1/households/{household_id}/medications/{id}/stock_removals",
            get(stock_removals::index).post(stock_removals::create),
        )
        .route(
            "/api/v1/households/{household_id}/admin/audit_logs",
            get(audit_logs::index),
        )
        .route(
            "/api/v1/households/{household_id}/admin/settings",
            get(admin_settings::show)
                .patch(admin_settings::patch)
                .put(admin_settings::put),
        )
        .route(
            "/api/v1/households/{household_id}/admin/app_tokens",
            get(app_tokens::index).post(app_tokens::create),
        )
        .route(
            "/api/v1/households/{household_id}/admin/app_tokens/{id}",
            axum::routing::delete(app_tokens::destroy),
        )
        .route(
            "/api/v1/households/{household_id}/admin/memberships",
            get(memberships::index),
        )
        .route(
            "/api/v1/households/{household_id}/admin/memberships/{id}",
            axum::routing::patch(memberships::patch)
                .put(memberships::put)
                .delete(memberships::delete),
        )
        .route(
            "/api/v1/households/{household_id}/admin/person_access_grants",
            get(person_grants::index).post(person_grants::create),
        )
        .route(
            "/api/v1/households/{household_id}/admin/person_access_grants/{id}",
            axum::routing::delete(person_grants::destroy),
        )
        .route(
            "/api/v1/households/{household_id}/admin/invitations",
            get(invitations::index).post(invitations::create),
        )
        .route(
            "/api/v1/households/{household_id}/admin/invitations/{id}",
            axum::routing::delete(invitations::destroy),
        )
        .route(
            "/api/v1/households/{household_id}/admin/invitations/{id}/resend",
            axum::routing::post(invitations::resend),
        )
        .route(
            "/api/v1/invitations/accept",
            axum::routing::post(invitations::accept),
        )
        .route(
            "/api/v1/households/{household_id}/people",
            get(read_resources::people_index).post(people::create),
        )
        .route("/api/v1/households/{household_id}/me", get(people::show_me))
        .route(
            "/api/v1/households/{household_id}/locations",
            get(read_resources::locations_index).post(locations::create),
        )
        .route(
            "/api/v1/households/{household_id}/locations/{id}",
            get(read_resources::locations_show)
                .patch(locations::patch)
                .put(locations::put)
                .delete(locations::delete),
        )
        .route(
            "/api/v1/households/{household_id}/locations/{location_id}/location_memberships",
            axum::routing::post(locations::create_membership),
        )
        .route(
            "/api/v1/households/{household_id}/locations/{location_id}/location_memberships/{id}",
            axum::routing::delete(locations::delete_membership),
        )
        .route(
            "/api/v1/households/{household_id}/notification_preference",
            get(notification_preferences::show)
                .patch(notification_preferences::patch)
                .put(notification_preferences::put),
        )
        .route(
            "/api/v1/households/{household_id}/native_device_tokens",
            axum::routing::post(native_device_tokens::create),
        )
        .route(
            "/api/v1/households/{household_id}/native_device_tokens/{id}",
            axum::routing::delete(native_device_tokens::delete),
        )
        .route(
            "/api/v1/households/{household_id}/push_subscription",
            axum::routing::post(push_subscriptions::create).delete(push_subscriptions::delete),
        )
        .route(
            "/api/v1/households/{household_id}/people/{id}",
            get(read_resources::people_show)
                .patch(people::patch)
                .put(people::put),
        )
        .route(
            "/api/v1/households/{household_id}/schedules",
            get(read_resources::schedules_index).post(schedule_writes::create),
        )
        .route(
            "/api/v1/households/{household_id}/schedules/{id}",
            get(read_resources::schedules_show)
                .patch(schedule_writes::patch)
                .put(schedule_writes::put),
        )
        .route(
            "/api/v1/households/{household_id}/schedules/{id}/pause",
            axum::routing::patch(pause_lifecycle::pause_schedule),
        )
        .route(
            "/api/v1/households/{household_id}/schedules/{id}/resume",
            axum::routing::patch(pause_lifecycle::resume_schedule),
        )
        .route(
            "/api/v1/households/{household_id}/schedules/{id}/dose_occurrences",
            get(dose_occurrences::list_schedule),
        )
        .route(
            "/api/v1/households/{household_id}/schedules/{id}/dose_occurrences/not_taken",
            axum::routing::post(dose_occurrences::not_taken_schedule),
        )
        .route(
            "/api/v1/households/{household_id}/schedules/{id}/dose_occurrences/reopen",
            axum::routing::patch(dose_occurrences::reopen_schedule),
        )
        .route(
            "/api/v1/households/{household_id}/schedules/{id}/dose_occurrences/take",
            axum::routing::post(dose_occurrences::take_schedule),
        )
        .route(
            "/api/v1/households/{household_id}/person_medications",
            get(read_resources::person_medications_index).post(person_medication_writes::create),
        )
        .route(
            "/api/v1/households/{household_id}/person_medications/{id}",
            get(read_resources::person_medications_show)
                .patch(person_medication_writes::patch)
                .put(person_medication_writes::put),
        )
        .route(
            "/api/v1/households/{household_id}/person_medications/{id}/pause",
            axum::routing::patch(pause_lifecycle::pause_assignment),
        )
        .route(
            "/api/v1/households/{household_id}/person_medications/{id}/resume",
            axum::routing::patch(pause_lifecycle::resume_assignment),
        )
        .route(
            "/api/v1/households/{household_id}/person_medications/{id}/dose_occurrences",
            get(dose_occurrences::list_assignment),
        )
        .route(
            "/api/v1/households/{household_id}/person_medications/{id}/dose_occurrences/not_taken",
            axum::routing::post(dose_occurrences::not_taken_assignment),
        )
        .route(
            "/api/v1/households/{household_id}/person_medications/{id}/dose_occurrences/reopen",
            axum::routing::patch(dose_occurrences::reopen_assignment),
        )
        .route(
            "/api/v1/households/{household_id}/person_medications/{id}/dose_occurrences/take",
            axum::routing::post(dose_occurrences::take_assignment),
        )
        .route(
            "/api/v1/households/{household_id}/person_medications/{id}/reorder",
            axum::routing::patch(pause_lifecycle::reorder_assignment),
        )
        .route(
            "/api/v1/households/{household_id}/medication_pause_periods",
            get(pause_lifecycle::index).post(pause_lifecycle::create),
        )
        .route(
            "/api/v1/households/{household_id}/medication_pause_periods/{id}/resume",
            axum::routing::post(pause_lifecycle::resume),
        )
        .merge(review_prompts::routes())
        .layer(middleware::from_fn_with_state(csrf_state, cookie_api_csrf))
        .layer(middleware::from_fn(private_api_cache))
        .with_state(state)
}
